/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AbstractPageLinks
 */
export interface AbstractPageLinks {
    /**
     * Web UI link of the content.
     * @type {string}
     * @memberof AbstractPageLinks
     */
    webui?: string;
    /**
     * Edit UI link of the content.
     * @type {string}
     * @memberof AbstractPageLinks
     */
    editui?: string;
    /**
     * Web UI link of the content.
     * @type {string}
     * @memberof AbstractPageLinks
     */
    tinyui?: string;
}

/**
 * Check if a given object implements the AbstractPageLinks interface.
 */
export function instanceOfAbstractPageLinks(value: object): value is AbstractPageLinks {
    return true;
}

export function AbstractPageLinksFromJSON(json: any): AbstractPageLinks {
    return AbstractPageLinksFromJSONTyped(json, false);
}

export function AbstractPageLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): AbstractPageLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'webui': json['webui'] == null ? undefined : json['webui'],
        'editui': json['editui'] == null ? undefined : json['editui'],
        'tinyui': json['tinyui'] == null ? undefined : json['tinyui'],
    };
}

export function AbstractPageLinksToJSON(json: any): AbstractPageLinks {
    return AbstractPageLinksToJSONTyped(json, false);
}

export function AbstractPageLinksToJSONTyped(value?: AbstractPageLinks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'webui': value['webui'],
        'editui': value['editui'],
        'tinyui': value['tinyui'],
    };
}

