/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The account type of the user.
 * @export
 */
export const AccountType = {
    Atlassian: 'atlassian',
    App: 'app',
    Customer: 'customer',
    Unknown: 'unknown'
} as const;
export type AccountType = typeof AccountType[keyof typeof AccountType];


export function instanceOfAccountType(value: any): boolean {
    for (const key in AccountType) {
        if (Object.prototype.hasOwnProperty.call(AccountType, key)) {
            if (AccountType[key as keyof typeof AccountType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AccountTypeFromJSON(json: any): AccountType {
    return AccountTypeFromJSONTyped(json, false);
}

export function AccountTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountType {
    return json as AccountType;
}

export function AccountTypeToJSON(value?: AccountType | null): any {
    return value as any;
}

export function AccountTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AccountType {
    return value as AccountType;
}

