/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The account status of the user.
 * @export
 */
export const AccountStatus = {
    Active: 'active',
    Inactive: 'inactive',
    Closed: 'closed',
    Unknown: 'unknown'
} as const;
export type AccountStatus = typeof AccountStatus[keyof typeof AccountStatus];


export function instanceOfAccountStatus(value: any): boolean {
    for (const key in AccountStatus) {
        if (Object.prototype.hasOwnProperty.call(AccountStatus, key)) {
            if (AccountStatus[key as keyof typeof AccountStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AccountStatusFromJSON(json: any): AccountStatus {
    return AccountStatusFromJSONTyped(json, false);
}

export function AccountStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountStatus {
    return json as AccountStatus;
}

export function AccountStatusToJSON(value?: AccountStatus | null): any {
    return value as any;
}

export function AccountStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): AccountStatus {
    return value as AccountStatus;
}

