/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminKeyResponse
 */
export interface AdminKeyResponse {
    /**
     * User identifier.
     * @type {string}
     * @memberof AdminKeyResponse
     */
    accountId?: string;
    /**
     * Timestamp in UTC that represents when the admin key will expire. In format "YYYY-MM-DDTHH:mm:ss.sssZ".
     * @type {Date}
     * @memberof AdminKeyResponse
     */
    expirationTime?: Date;
}

/**
 * Check if a given object implements the AdminKeyResponse interface.
 */
export function instanceOfAdminKeyResponse(value: object): value is AdminKeyResponse {
    return true;
}

export function AdminKeyResponseFromJSON(json: any): AdminKeyResponse {
    return AdminKeyResponseFromJSONTyped(json, false);
}

export function AdminKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'expirationTime': json['expirationTime'] == null ? undefined : (new Date(json['expirationTime'])),
    };
}

export function AdminKeyResponseToJSON(json: any): AdminKeyResponse {
    return AdminKeyResponseToJSONTyped(json, false);
}

export function AdminKeyResponseToJSONTyped(value?: AdminKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'expirationTime': value['expirationTime'] == null ? value['expirationTime'] : value['expirationTime'].toISOString(),
    };
}

