/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AncestorType } from './AncestorType';
import {
    AncestorTypeFromJSON,
    AncestorTypeFromJSONTyped,
    AncestorTypeToJSON,
    AncestorTypeToJSONTyped,
} from './AncestorType';

/**
 * 
 * @export
 * @interface Ancestor
 */
export interface Ancestor {
    /**
     * ID of the ancestor
     * @type {string}
     * @memberof Ancestor
     */
    id?: string;
    /**
     * 
     * @type {AncestorType}
     * @memberof Ancestor
     */
    type?: AncestorType;
}



/**
 * Check if a given object implements the Ancestor interface.
 */
export function instanceOfAncestor(value: object): value is Ancestor {
    return true;
}

export function AncestorFromJSON(json: any): Ancestor {
    return AncestorFromJSONTyped(json, false);
}

export function AncestorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ancestor {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : AncestorTypeFromJSON(json['type']),
    };
}

export function AncestorToJSON(json: any): Ancestor {
    return AncestorToJSONTyped(json, false);
}

export function AncestorToJSONTyped(value?: Ancestor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': AncestorTypeToJSON(value['type']),
    };
}

