/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentProperty } from './ContentProperty';
import {
    ContentPropertyFromJSON,
    ContentPropertyFromJSONTyped,
    ContentPropertyToJSON,
    ContentPropertyToJSONTyped,
} from './ContentProperty';
import type { OptionalFieldLinks } from './OptionalFieldLinks';
import {
    OptionalFieldLinksFromJSON,
    OptionalFieldLinksFromJSONTyped,
    OptionalFieldLinksToJSON,
    OptionalFieldLinksToJSONTyped,
} from './OptionalFieldLinks';
import type { OptionalFieldMeta } from './OptionalFieldMeta';
import {
    OptionalFieldMetaFromJSON,
    OptionalFieldMetaFromJSONTyped,
    OptionalFieldMetaToJSON,
    OptionalFieldMetaToJSONTyped,
} from './OptionalFieldMeta';

/**
 * 
 * @export
 * @interface AttachmentSingleProperties
 */
export interface AttachmentSingleProperties {
    /**
     * 
     * @type {Array<ContentProperty>}
     * @memberof AttachmentSingleProperties
     */
    results?: Array<ContentProperty>;
    /**
     * 
     * @type {OptionalFieldMeta}
     * @memberof AttachmentSingleProperties
     */
    meta?: OptionalFieldMeta;
    /**
     * 
     * @type {OptionalFieldLinks}
     * @memberof AttachmentSingleProperties
     */
    links?: OptionalFieldLinks;
}

/**
 * Check if a given object implements the AttachmentSingleProperties interface.
 */
export function instanceOfAttachmentSingleProperties(value: object): value is AttachmentSingleProperties {
    return true;
}

export function AttachmentSinglePropertiesFromJSON(json: any): AttachmentSingleProperties {
    return AttachmentSinglePropertiesFromJSONTyped(json, false);
}

export function AttachmentSinglePropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentSingleProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(ContentPropertyFromJSON)),
        'meta': json['meta'] == null ? undefined : OptionalFieldMetaFromJSON(json['meta']),
        'links': json['_links'] == null ? undefined : OptionalFieldLinksFromJSON(json['_links']),
    };
}

export function AttachmentSinglePropertiesToJSON(json: any): AttachmentSingleProperties {
    return AttachmentSinglePropertiesToJSONTyped(json, false);
}

export function AttachmentSinglePropertiesToJSONTyped(value?: AttachmentSingleProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(ContentPropertyToJSON)),
        'meta': OptionalFieldMetaToJSON(value['meta']),
        '_links': OptionalFieldLinksToJSON(value['links']),
    };
}

