/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The sort fields for attachments. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`.
 * @export
 */
export const AttachmentSortOrder = {
    CreatedDate: 'created-date',
    CreatedDate2: '-created-date',
    ModifiedDate: 'modified-date',
    ModifiedDate2: '-modified-date'
} as const;
export type AttachmentSortOrder = typeof AttachmentSortOrder[keyof typeof AttachmentSortOrder];


export function instanceOfAttachmentSortOrder(value: any): boolean {
    for (const key in AttachmentSortOrder) {
        if (Object.prototype.hasOwnProperty.call(AttachmentSortOrder, key)) {
            if (AttachmentSortOrder[key as keyof typeof AttachmentSortOrder] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AttachmentSortOrderFromJSON(json: any): AttachmentSortOrder {
    return AttachmentSortOrderFromJSONTyped(json, false);
}

export function AttachmentSortOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentSortOrder {
    return json as AttachmentSortOrder;
}

export function AttachmentSortOrderToJSON(value?: AttachmentSortOrder | null): any {
    return value as any;
}

export function AttachmentSortOrderToJSONTyped(value: any, ignoreDiscriminator: boolean): AttachmentSortOrder {
    return value as AttachmentSortOrder;
}

