/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Label } from './Label';
import {
    LabelFromJSON,
    LabelFromJSONTyped,
    LabelToJSON,
    LabelToJSONTyped,
} from './Label';
import type { OptionalFieldLinks } from './OptionalFieldLinks';
import {
    OptionalFieldLinksFromJSON,
    OptionalFieldLinksFromJSONTyped,
    OptionalFieldLinksToJSON,
    OptionalFieldLinksToJSONTyped,
} from './OptionalFieldLinks';
import type { OptionalFieldMeta } from './OptionalFieldMeta';
import {
    OptionalFieldMetaFromJSON,
    OptionalFieldMetaFromJSONTyped,
    OptionalFieldMetaToJSON,
    OptionalFieldMetaToJSONTyped,
} from './OptionalFieldMeta';

/**
 * 
 * @export
 * @interface AttachmentSingleLabels
 */
export interface AttachmentSingleLabels {
    /**
     * 
     * @type {Array<Label>}
     * @memberof AttachmentSingleLabels
     */
    results?: Array<Label>;
    /**
     * 
     * @type {OptionalFieldMeta}
     * @memberof AttachmentSingleLabels
     */
    meta?: OptionalFieldMeta;
    /**
     * 
     * @type {OptionalFieldLinks}
     * @memberof AttachmentSingleLabels
     */
    links?: OptionalFieldLinks;
}

/**
 * Check if a given object implements the AttachmentSingleLabels interface.
 */
export function instanceOfAttachmentSingleLabels(value: object): value is AttachmentSingleLabels {
    return true;
}

export function AttachmentSingleLabelsFromJSON(json: any): AttachmentSingleLabels {
    return AttachmentSingleLabelsFromJSONTyped(json, false);
}

export function AttachmentSingleLabelsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentSingleLabels {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(LabelFromJSON)),
        'meta': json['meta'] == null ? undefined : OptionalFieldMetaFromJSON(json['meta']),
        'links': json['_links'] == null ? undefined : OptionalFieldLinksFromJSON(json['_links']),
    };
}

export function AttachmentSingleLabelsToJSON(json: any): AttachmentSingleLabels {
    return AttachmentSingleLabelsToJSONTyped(json, false);
}

export function AttachmentSingleLabelsToJSONTyped(value?: AttachmentSingleLabels | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(LabelToJSON)),
        'meta': OptionalFieldMetaToJSON(value['meta']),
        '_links': OptionalFieldLinksToJSON(value['links']),
    };
}

