/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttachmentLinks } from './AttachmentLinks';
import {
    AttachmentLinksFromJSON,
    AttachmentLinksFromJSONTyped,
    AttachmentLinksToJSON,
    AttachmentLinksToJSONTyped,
} from './AttachmentLinks';
import type { Version } from './Version';
import {
    VersionFromJSON,
    VersionFromJSONTyped,
    VersionToJSON,
    VersionToJSONTyped,
} from './Version';
import type { ContentStatus } from './ContentStatus';
import {
    ContentStatusFromJSON,
    ContentStatusFromJSONTyped,
    ContentStatusToJSON,
    ContentStatusToJSONTyped,
} from './ContentStatus';

/**
 * 
 * @export
 * @interface AttachmentBulk
 */
export interface AttachmentBulk {
    /**
     * ID of the attachment.
     * @type {string}
     * @memberof AttachmentBulk
     */
    id?: string;
    /**
     * 
     * @type {ContentStatus}
     * @memberof AttachmentBulk
     */
    status?: ContentStatus;
    /**
     * Title of the comment.
     * @type {string}
     * @memberof AttachmentBulk
     */
    title?: string;
    /**
     * Date and time when the attachment was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ".
     * @type {Date}
     * @memberof AttachmentBulk
     */
    createdAt?: Date;
    /**
     * ID of the containing page.
     * 
     * Note: This is only returned if the attachment has a container that is a page.
     * @type {string}
     * @memberof AttachmentBulk
     */
    pageId?: string;
    /**
     * ID of the containing blog post.
     * 
     * Note: This is only returned if the attachment has a container that is a blog post.
     * @type {string}
     * @memberof AttachmentBulk
     */
    blogPostId?: string;
    /**
     * ID of the containing custom content.
     * 
     * Note: This is only returned if the attachment has a container that is custom content.
     * @type {string}
     * @memberof AttachmentBulk
     */
    customContentId?: string;
    /**
     * Media Type for the attachment.
     * @type {string}
     * @memberof AttachmentBulk
     */
    mediaType?: string;
    /**
     * Media Type description for the attachment.
     * @type {string}
     * @memberof AttachmentBulk
     */
    mediaTypeDescription?: string;
    /**
     * Comment for the attachment.
     * @type {string}
     * @memberof AttachmentBulk
     */
    comment?: string;
    /**
     * File ID of the attachment. This is the ID referenced in `atlas_doc_format` bodies and is distinct from the attachment ID.
     * @type {string}
     * @memberof AttachmentBulk
     */
    fileId?: string;
    /**
     * File size of the attachment.
     * @type {number}
     * @memberof AttachmentBulk
     */
    fileSize?: number;
    /**
     * WebUI link of the attachment.
     * @type {string}
     * @memberof AttachmentBulk
     */
    webuiLink?: string;
    /**
     * Download link of the attachment.
     * @type {string}
     * @memberof AttachmentBulk
     */
    downloadLink?: string;
    /**
     * 
     * @type {Version}
     * @memberof AttachmentBulk
     */
    version?: Version;
    /**
     * 
     * @type {AttachmentLinks}
     * @memberof AttachmentBulk
     */
    links?: AttachmentLinks;
}



/**
 * Check if a given object implements the AttachmentBulk interface.
 */
export function instanceOfAttachmentBulk(value: object): value is AttachmentBulk {
    return true;
}

export function AttachmentBulkFromJSON(json: any): AttachmentBulk {
    return AttachmentBulkFromJSONTyped(json, false);
}

export function AttachmentBulkFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentBulk {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : ContentStatusFromJSON(json['status']),
        'title': json['title'] == null ? undefined : json['title'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'pageId': json['pageId'] == null ? undefined : json['pageId'],
        'blogPostId': json['blogPostId'] == null ? undefined : json['blogPostId'],
        'customContentId': json['customContentId'] == null ? undefined : json['customContentId'],
        'mediaType': json['mediaType'] == null ? undefined : json['mediaType'],
        'mediaTypeDescription': json['mediaTypeDescription'] == null ? undefined : json['mediaTypeDescription'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'fileId': json['fileId'] == null ? undefined : json['fileId'],
        'fileSize': json['fileSize'] == null ? undefined : json['fileSize'],
        'webuiLink': json['webuiLink'] == null ? undefined : json['webuiLink'],
        'downloadLink': json['downloadLink'] == null ? undefined : json['downloadLink'],
        'version': json['version'] == null ? undefined : VersionFromJSON(json['version']),
        'links': json['_links'] == null ? undefined : AttachmentLinksFromJSON(json['_links']),
    };
}

export function AttachmentBulkToJSON(json: any): AttachmentBulk {
    return AttachmentBulkToJSONTyped(json, false);
}

export function AttachmentBulkToJSONTyped(value?: AttachmentBulk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': ContentStatusToJSON(value['status']),
        'title': value['title'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'pageId': value['pageId'],
        'blogPostId': value['blogPostId'],
        'customContentId': value['customContentId'],
        'mediaType': value['mediaType'],
        'mediaTypeDescription': value['mediaTypeDescription'],
        'comment': value['comment'],
        'fileId': value['fileId'],
        'fileSize': value['fileSize'],
        'webuiLink': value['webuiLink'],
        'downloadLink': value['downloadLink'],
        'version': VersionToJSON(value['version']),
        '_links': AttachmentLinksToJSON(value['links']),
    };
}

