/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlogPostBodyWrite } from './BlogPostBodyWrite';
import {
    BlogPostBodyWriteFromJSON,
    BlogPostBodyWriteFromJSONTyped,
    BlogPostBodyWriteToJSON,
    BlogPostBodyWriteToJSONTyped,
} from './BlogPostBodyWrite';

/**
 * Body of the blog post. Only one body format should be specified as the property
 * for this object, e.g. `storage`.
 * @export
 * @interface BlogPostNestedBodyWrite
 */
export interface BlogPostNestedBodyWrite {
    /**
     * 
     * @type {BlogPostBodyWrite}
     * @memberof BlogPostNestedBodyWrite
     */
    storage?: BlogPostBodyWrite;
    /**
     * 
     * @type {BlogPostBodyWrite}
     * @memberof BlogPostNestedBodyWrite
     */
    atlasDocFormat?: BlogPostBodyWrite;
    /**
     * 
     * @type {BlogPostBodyWrite}
     * @memberof BlogPostNestedBodyWrite
     */
    wiki?: BlogPostBodyWrite;
}

/**
 * Check if a given object implements the BlogPostNestedBodyWrite interface.
 */
export function instanceOfBlogPostNestedBodyWrite(value: object): value is BlogPostNestedBodyWrite {
    return true;
}

export function BlogPostNestedBodyWriteFromJSON(json: any): BlogPostNestedBodyWrite {
    return BlogPostNestedBodyWriteFromJSONTyped(json, false);
}

export function BlogPostNestedBodyWriteFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogPostNestedBodyWrite {
    if (json == null) {
        return json;
    }
    return {
        
        'storage': json['storage'] == null ? undefined : BlogPostBodyWriteFromJSON(json['storage']),
        'atlasDocFormat': json['atlas_doc_format'] == null ? undefined : BlogPostBodyWriteFromJSON(json['atlas_doc_format']),
        'wiki': json['wiki'] == null ? undefined : BlogPostBodyWriteFromJSON(json['wiki']),
    };
}

export function BlogPostNestedBodyWriteToJSON(json: any): BlogPostNestedBodyWrite {
    return BlogPostNestedBodyWriteToJSONTyped(json, false);
}

export function BlogPostNestedBodyWriteToJSONTyped(value?: BlogPostNestedBodyWrite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'storage': BlogPostBodyWriteToJSON(value['storage']),
        'atlas_doc_format': BlogPostBodyWriteToJSON(value['atlasDocFormat']),
        'wiki': BlogPostBodyWriteToJSON(value['wiki']),
    };
}

