/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AbstractPageLinks } from './AbstractPageLinks';
import {
    AbstractPageLinksFromJSON,
    AbstractPageLinksFromJSONTyped,
    AbstractPageLinksToJSON,
    AbstractPageLinksToJSONTyped,
} from './AbstractPageLinks';
import type { AttachmentSingleProperties } from './AttachmentSingleProperties';
import {
    AttachmentSinglePropertiesFromJSON,
    AttachmentSinglePropertiesFromJSONTyped,
    AttachmentSinglePropertiesToJSON,
    AttachmentSinglePropertiesToJSONTyped,
} from './AttachmentSingleProperties';
import type { BlogPostSingleLikes } from './BlogPostSingleLikes';
import {
    BlogPostSingleLikesFromJSON,
    BlogPostSingleLikesFromJSONTyped,
    BlogPostSingleLikesToJSON,
    BlogPostSingleLikesToJSONTyped,
} from './BlogPostSingleLikes';
import type { Version } from './Version';
import {
    VersionFromJSON,
    VersionFromJSONTyped,
    VersionToJSON,
    VersionToJSONTyped,
} from './Version';
import type { AttachmentSingleOperations } from './AttachmentSingleOperations';
import {
    AttachmentSingleOperationsFromJSON,
    AttachmentSingleOperationsFromJSONTyped,
    AttachmentSingleOperationsToJSON,
    AttachmentSingleOperationsToJSONTyped,
} from './AttachmentSingleOperations';
import type { AttachmentSingleLabels } from './AttachmentSingleLabels';
import {
    AttachmentSingleLabelsFromJSON,
    AttachmentSingleLabelsFromJSONTyped,
    AttachmentSingleLabelsToJSON,
    AttachmentSingleLabelsToJSONTyped,
} from './AttachmentSingleLabels';
import type { BlogPostContentStatus } from './BlogPostContentStatus';
import {
    BlogPostContentStatusFromJSON,
    BlogPostContentStatusFromJSONTyped,
    BlogPostContentStatusToJSON,
    BlogPostContentStatusToJSONTyped,
} from './BlogPostContentStatus';
import type { BodySingle } from './BodySingle';
import {
    BodySingleFromJSON,
    BodySingleFromJSONTyped,
    BodySingleToJSON,
    BodySingleToJSONTyped,
} from './BodySingle';
import type { AttachmentSingleVersions } from './AttachmentSingleVersions';
import {
    AttachmentSingleVersionsFromJSON,
    AttachmentSingleVersionsFromJSONTyped,
    AttachmentSingleVersionsToJSON,
    AttachmentSingleVersionsToJSONTyped,
} from './AttachmentSingleVersions';

/**
 * 
 * @export
 * @interface BlogPostSingle
 */
export interface BlogPostSingle {
    /**
     * ID of the blog post.
     * @type {string}
     * @memberof BlogPostSingle
     */
    id?: string;
    /**
     * 
     * @type {BlogPostContentStatus}
     * @memberof BlogPostSingle
     */
    status?: BlogPostContentStatus;
    /**
     * Title of the blog post.
     * @type {string}
     * @memberof BlogPostSingle
     */
    title?: string;
    /**
     * ID of the space the blog post is in.
     * @type {string}
     * @memberof BlogPostSingle
     */
    spaceId?: string;
    /**
     * The account ID of the user who created this blog post originally.
     * @type {string}
     * @memberof BlogPostSingle
     */
    authorId?: string;
    /**
     * Date and time when the blog post was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ".
     * @type {Date}
     * @memberof BlogPostSingle
     */
    createdAt?: Date;
    /**
     * 
     * @type {Version}
     * @memberof BlogPostSingle
     */
    version?: Version;
    /**
     * 
     * @type {BodySingle}
     * @memberof BlogPostSingle
     */
    body?: BodySingle;
    /**
     * 
     * @type {AttachmentSingleLabels}
     * @memberof BlogPostSingle
     */
    labels?: AttachmentSingleLabels;
    /**
     * 
     * @type {AttachmentSingleProperties}
     * @memberof BlogPostSingle
     */
    properties?: AttachmentSingleProperties;
    /**
     * 
     * @type {AttachmentSingleOperations}
     * @memberof BlogPostSingle
     */
    operations?: AttachmentSingleOperations;
    /**
     * 
     * @type {BlogPostSingleLikes}
     * @memberof BlogPostSingle
     */
    likes?: BlogPostSingleLikes;
    /**
     * 
     * @type {AttachmentSingleVersions}
     * @memberof BlogPostSingle
     */
    versions?: AttachmentSingleVersions;
    /**
     * Whether the blog post has been favorited by the current user.
     * @type {boolean}
     * @memberof BlogPostSingle
     */
    isFavoritedByCurrentUser?: boolean;
    /**
     * 
     * @type {AbstractPageLinks}
     * @memberof BlogPostSingle
     */
    links?: AbstractPageLinks;
}



/**
 * Check if a given object implements the BlogPostSingle interface.
 */
export function instanceOfBlogPostSingle(value: object): value is BlogPostSingle {
    return true;
}

export function BlogPostSingleFromJSON(json: any): BlogPostSingle {
    return BlogPostSingleFromJSONTyped(json, false);
}

export function BlogPostSingleFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogPostSingle {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : BlogPostContentStatusFromJSON(json['status']),
        'title': json['title'] == null ? undefined : json['title'],
        'spaceId': json['spaceId'] == null ? undefined : json['spaceId'],
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'version': json['version'] == null ? undefined : VersionFromJSON(json['version']),
        'body': json['body'] == null ? undefined : BodySingleFromJSON(json['body']),
        'labels': json['labels'] == null ? undefined : AttachmentSingleLabelsFromJSON(json['labels']),
        'properties': json['properties'] == null ? undefined : AttachmentSinglePropertiesFromJSON(json['properties']),
        'operations': json['operations'] == null ? undefined : AttachmentSingleOperationsFromJSON(json['operations']),
        'likes': json['likes'] == null ? undefined : BlogPostSingleLikesFromJSON(json['likes']),
        'versions': json['versions'] == null ? undefined : AttachmentSingleVersionsFromJSON(json['versions']),
        'isFavoritedByCurrentUser': json['isFavoritedByCurrentUser'] == null ? undefined : json['isFavoritedByCurrentUser'],
        'links': json['_links'] == null ? undefined : AbstractPageLinksFromJSON(json['_links']),
    };
}

export function BlogPostSingleToJSON(json: any): BlogPostSingle {
    return BlogPostSingleToJSONTyped(json, false);
}

export function BlogPostSingleToJSONTyped(value?: BlogPostSingle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': BlogPostContentStatusToJSON(value['status']),
        'title': value['title'],
        'spaceId': value['spaceId'],
        'authorId': value['authorId'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'version': VersionToJSON(value['version']),
        'body': BodySingleToJSON(value['body']),
        'labels': AttachmentSingleLabelsToJSON(value['labels']),
        'properties': AttachmentSinglePropertiesToJSON(value['properties']),
        'operations': AttachmentSingleOperationsToJSON(value['operations']),
        'likes': BlogPostSingleLikesToJSON(value['likes']),
        'versions': AttachmentSingleVersionsToJSON(value['versions']),
        'isFavoritedByCurrentUser': value['isFavoritedByCurrentUser'],
        '_links': AbstractPageLinksToJSON(value['links']),
    };
}

