/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Like } from './Like';
import {
    LikeFromJSON,
    LikeFromJSONTyped,
    LikeToJSON,
    LikeToJSONTyped,
} from './Like';
import type { OptionalFieldLinks } from './OptionalFieldLinks';
import {
    OptionalFieldLinksFromJSON,
    OptionalFieldLinksFromJSONTyped,
    OptionalFieldLinksToJSON,
    OptionalFieldLinksToJSONTyped,
} from './OptionalFieldLinks';
import type { OptionalFieldMeta } from './OptionalFieldMeta';
import {
    OptionalFieldMetaFromJSON,
    OptionalFieldMetaFromJSONTyped,
    OptionalFieldMetaToJSON,
    OptionalFieldMetaToJSONTyped,
} from './OptionalFieldMeta';

/**
 * 
 * @export
 * @interface BlogPostSingleLikes
 */
export interface BlogPostSingleLikes {
    /**
     * 
     * @type {Array<Like>}
     * @memberof BlogPostSingleLikes
     */
    results?: Array<Like>;
    /**
     * 
     * @type {OptionalFieldMeta}
     * @memberof BlogPostSingleLikes
     */
    meta?: OptionalFieldMeta;
    /**
     * 
     * @type {OptionalFieldLinks}
     * @memberof BlogPostSingleLikes
     */
    links?: OptionalFieldLinks;
}

/**
 * Check if a given object implements the BlogPostSingleLikes interface.
 */
export function instanceOfBlogPostSingleLikes(value: object): value is BlogPostSingleLikes {
    return true;
}

export function BlogPostSingleLikesFromJSON(json: any): BlogPostSingleLikes {
    return BlogPostSingleLikesFromJSONTyped(json, false);
}

export function BlogPostSingleLikesFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogPostSingleLikes {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(LikeFromJSON)),
        'meta': json['meta'] == null ? undefined : OptionalFieldMetaFromJSON(json['meta']),
        'links': json['_links'] == null ? undefined : OptionalFieldLinksFromJSON(json['_links']),
    };
}

export function BlogPostSingleLikesToJSON(json: any): BlogPostSingleLikes {
    return BlogPostSingleLikesToJSONTyped(json, false);
}

export function BlogPostSingleLikesToJSONTyped(value?: BlogPostSingleLikes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(LikeToJSON)),
        'meta': OptionalFieldMetaToJSON(value['meta']),
        '_links': OptionalFieldLinksToJSON(value['links']),
    };
}

