/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlogPostBodyWrite
 */
export interface BlogPostBodyWrite {
    /**
     * Type of content representation used for the value field.
     * @type {string}
     * @memberof BlogPostBodyWrite
     */
    representation?: BlogPostBodyWriteRepresentationEnum;
    /**
     * Body of the blog post, in the format found in the representation field.
     * @type {string}
     * @memberof BlogPostBodyWrite
     */
    value?: string;
}


/**
 * @export
 */
export const BlogPostBodyWriteRepresentationEnum = {
    Storage: 'storage',
    AtlasDocFormat: 'atlas_doc_format',
    Wiki: 'wiki'
} as const;
export type BlogPostBodyWriteRepresentationEnum = typeof BlogPostBodyWriteRepresentationEnum[keyof typeof BlogPostBodyWriteRepresentationEnum];


/**
 * Check if a given object implements the BlogPostBodyWrite interface.
 */
export function instanceOfBlogPostBodyWrite(value: object): value is BlogPostBodyWrite {
    return true;
}

export function BlogPostBodyWriteFromJSON(json: any): BlogPostBodyWrite {
    return BlogPostBodyWriteFromJSONTyped(json, false);
}

export function BlogPostBodyWriteFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogPostBodyWrite {
    if (json == null) {
        return json;
    }
    return {
        
        'representation': json['representation'] == null ? undefined : json['representation'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function BlogPostBodyWriteToJSON(json: any): BlogPostBodyWrite {
    return BlogPostBodyWriteToJSONTyped(json, false);
}

export function BlogPostBodyWriteToJSONTyped(value?: BlogPostBodyWrite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'representation': value['representation'],
        'value': value['value'],
    };
}

