/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The sort fields for blog posts. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`.
 * @export
 */
export const BlogPostSortOrder = {
    Id: 'id',
    Id2: '-id',
    CreatedDate: 'created-date',
    CreatedDate2: '-created-date',
    ModifiedDate: 'modified-date',
    ModifiedDate2: '-modified-date'
} as const;
export type BlogPostSortOrder = typeof BlogPostSortOrder[keyof typeof BlogPostSortOrder];


export function instanceOfBlogPostSortOrder(value: any): boolean {
    for (const key in BlogPostSortOrder) {
        if (Object.prototype.hasOwnProperty.call(BlogPostSortOrder, key)) {
            if (BlogPostSortOrder[key as keyof typeof BlogPostSortOrder] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BlogPostSortOrderFromJSON(json: any): BlogPostSortOrder {
    return BlogPostSortOrderFromJSONTyped(json, false);
}

export function BlogPostSortOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogPostSortOrder {
    return json as BlogPostSortOrder;
}

export function BlogPostSortOrderToJSON(value?: BlogPostSortOrder | null): any {
    return value as any;
}

export function BlogPostSortOrderToJSONTyped(value: any, ignoreDiscriminator: boolean): BlogPostSortOrder {
    return value as BlogPostSortOrder;
}

