/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The status of the content.
 * @export
 */
export const BlogPostContentStatus = {
    Current: 'current',
    Draft: 'draft',
    Historical: 'historical',
    Trashed: 'trashed',
    Deleted: 'deleted',
    Any: 'any'
} as const;
export type BlogPostContentStatus = typeof BlogPostContentStatus[keyof typeof BlogPostContentStatus];


export function instanceOfBlogPostContentStatus(value: any): boolean {
    for (const key in BlogPostContentStatus) {
        if (Object.prototype.hasOwnProperty.call(BlogPostContentStatus, key)) {
            if (BlogPostContentStatus[key as keyof typeof BlogPostContentStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BlogPostContentStatusFromJSON(json: any): BlogPostContentStatus {
    return BlogPostContentStatusFromJSONTyped(json, false);
}

export function BlogPostContentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogPostContentStatus {
    return json as BlogPostContentStatus;
}

export function BlogPostContentStatusToJSON(value?: BlogPostContentStatus | null): any {
    return value as any;
}

export function BlogPostContentStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): BlogPostContentStatus {
    return value as BlogPostContentStatus;
}

