/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyType
 */
export interface BodyType {
    /**
     * Type of content representation used for the value field.
     * @type {string}
     * @memberof BodyType
     */
    representation?: string;
    /**
     * Body of the content, in the format found in the representation field.
     * @type {string}
     * @memberof BodyType
     */
    value?: string;
}

/**
 * Check if a given object implements the BodyType interface.
 */
export function instanceOfBodyType(value: object): value is BodyType {
    return true;
}

export function BodyTypeFromJSON(json: any): BodyType {
    return BodyTypeFromJSONTyped(json, false);
}

export function BodyTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyType {
    if (json == null) {
        return json;
    }
    return {
        
        'representation': json['representation'] == null ? undefined : json['representation'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function BodyTypeToJSON(json: any): BodyType {
    return BodyTypeToJSONTyped(json, false);
}

export function BodyTypeToJSONTyped(value?: BodyType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'representation': value['representation'],
        'value': value['value'],
    };
}

