/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckAccessByEmail200Response
 */
export interface CheckAccessByEmail200Response {
    /**
     * List of emails that do not have access to site.
     * @type {Array<string>}
     * @memberof CheckAccessByEmail200Response
     */
    emailsWithoutAccess?: Array<string>;
    /**
     * List of invalid emails provided in the request.
     * @type {Array<string>}
     * @memberof CheckAccessByEmail200Response
     */
    invalidEmails?: Array<string>;
}

/**
 * Check if a given object implements the CheckAccessByEmail200Response interface.
 */
export function instanceOfCheckAccessByEmail200Response(value: object): value is CheckAccessByEmail200Response {
    return true;
}

export function CheckAccessByEmail200ResponseFromJSON(json: any): CheckAccessByEmail200Response {
    return CheckAccessByEmail200ResponseFromJSONTyped(json, false);
}

export function CheckAccessByEmail200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckAccessByEmail200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'emailsWithoutAccess': json['emailsWithoutAccess'] == null ? undefined : json['emailsWithoutAccess'],
        'invalidEmails': json['invalidEmails'] == null ? undefined : json['invalidEmails'],
    };
}

export function CheckAccessByEmail200ResponseToJSON(json: any): CheckAccessByEmail200Response {
    return CheckAccessByEmail200ResponseToJSONTyped(json, false);
}

export function CheckAccessByEmail200ResponseToJSONTyped(value?: CheckAccessByEmail200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'emailsWithoutAccess': value['emailsWithoutAccess'],
        'invalidEmails': value['invalidEmails'],
    };
}

