/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Version } from './Version';
import {
    VersionFromJSON,
    VersionFromJSONTyped,
    VersionToJSON,
    VersionToJSONTyped,
} from './Version';
import type { BodyBulk } from './BodyBulk';
import {
    BodyBulkFromJSON,
    BodyBulkFromJSONTyped,
    BodyBulkToJSON,
    BodyBulkToJSONTyped,
} from './BodyBulk';
import type { CommentLinks } from './CommentLinks';
import {
    CommentLinksFromJSON,
    CommentLinksFromJSONTyped,
    CommentLinksToJSON,
    CommentLinksToJSONTyped,
} from './CommentLinks';
import type { ContentStatus } from './ContentStatus';
import {
    ContentStatusFromJSON,
    ContentStatusFromJSONTyped,
    ContentStatusToJSON,
    ContentStatusToJSONTyped,
} from './ContentStatus';

/**
 * 
 * @export
 * @interface ChildrenCommentModel
 */
export interface ChildrenCommentModel {
    /**
     * ID of the comment.
     * @type {string}
     * @memberof ChildrenCommentModel
     */
    id?: string;
    /**
     * 
     * @type {ContentStatus}
     * @memberof ChildrenCommentModel
     */
    status?: ContentStatus;
    /**
     * Title of the comment.
     * @type {string}
     * @memberof ChildrenCommentModel
     */
    title?: string;
    /**
     * ID of the parent comment the child comment is in.
     * @type {string}
     * @memberof ChildrenCommentModel
     */
    parentCommentId?: string;
    /**
     * 
     * @type {Version}
     * @memberof ChildrenCommentModel
     */
    version?: Version;
    /**
     * 
     * @type {BodyBulk}
     * @memberof ChildrenCommentModel
     */
    body?: BodyBulk;
    /**
     * 
     * @type {CommentLinks}
     * @memberof ChildrenCommentModel
     */
    links?: CommentLinks;
}



/**
 * Check if a given object implements the ChildrenCommentModel interface.
 */
export function instanceOfChildrenCommentModel(value: object): value is ChildrenCommentModel {
    return true;
}

export function ChildrenCommentModelFromJSON(json: any): ChildrenCommentModel {
    return ChildrenCommentModelFromJSONTyped(json, false);
}

export function ChildrenCommentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChildrenCommentModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : ContentStatusFromJSON(json['status']),
        'title': json['title'] == null ? undefined : json['title'],
        'parentCommentId': json['parentCommentId'] == null ? undefined : json['parentCommentId'],
        'version': json['version'] == null ? undefined : VersionFromJSON(json['version']),
        'body': json['body'] == null ? undefined : BodyBulkFromJSON(json['body']),
        'links': json['_links'] == null ? undefined : CommentLinksFromJSON(json['_links']),
    };
}

export function ChildrenCommentModelToJSON(json: any): ChildrenCommentModel {
    return ChildrenCommentModelToJSONTyped(json, false);
}

export function ChildrenCommentModelToJSONTyped(value?: ChildrenCommentModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': ContentStatusToJSON(value['status']),
        'title': value['title'],
        'parentCommentId': value['parentCommentId'],
        'version': VersionToJSON(value['version']),
        'body': BodyBulkToJSON(value['body']),
        '_links': CommentLinksToJSON(value['links']),
    };
}

