/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OnlyArchivedAndCurrentContentStatus } from './OnlyArchivedAndCurrentContentStatus';
import {
    OnlyArchivedAndCurrentContentStatusFromJSON,
    OnlyArchivedAndCurrentContentStatusFromJSONTyped,
    OnlyArchivedAndCurrentContentStatusToJSON,
    OnlyArchivedAndCurrentContentStatusToJSONTyped,
} from './OnlyArchivedAndCurrentContentStatus';

/**
 * 
 * @export
 * @interface ChildrenResponse
 */
export interface ChildrenResponse {
    /**
     * ID of the child content.
     * @type {string}
     * @memberof ChildrenResponse
     */
    id?: string;
    /**
     * 
     * @type {OnlyArchivedAndCurrentContentStatus}
     * @memberof ChildrenResponse
     */
    status?: OnlyArchivedAndCurrentContentStatus;
    /**
     * Title of the child content.
     * @type {string}
     * @memberof ChildrenResponse
     */
    title?: string;
    /**
     * Hierarchical content type (database/embed/folder/page/whiteboard).
     * @type {string}
     * @memberof ChildrenResponse
     */
    type?: string;
    /**
     * ID of the space the content is in.
     * @type {string}
     * @memberof ChildrenResponse
     */
    spaceId?: string;
    /**
     * Numerical value indicating position of the content relative to its siblings (with the same parentId) within the content tree.
     * If the content is sorted by childPosition, it will reflect the default content ordering within the content tree.
     * @type {number}
     * @memberof ChildrenResponse
     */
    childPosition?: number | null;
}



/**
 * Check if a given object implements the ChildrenResponse interface.
 */
export function instanceOfChildrenResponse(value: object): value is ChildrenResponse {
    return true;
}

export function ChildrenResponseFromJSON(json: any): ChildrenResponse {
    return ChildrenResponseFromJSONTyped(json, false);
}

export function ChildrenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChildrenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : OnlyArchivedAndCurrentContentStatusFromJSON(json['status']),
        'title': json['title'] == null ? undefined : json['title'],
        'type': json['type'] == null ? undefined : json['type'],
        'spaceId': json['spaceId'] == null ? undefined : json['spaceId'],
        'childPosition': json['childPosition'] == null ? undefined : json['childPosition'],
    };
}

export function ChildrenResponseToJSON(json: any): ChildrenResponse {
    return ChildrenResponseToJSONTyped(json, false);
}

export function ChildrenResponseToJSONTyped(value?: ChildrenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': OnlyArchivedAndCurrentContentStatusToJSON(value['status']),
        'title': value['title'],
        'type': value['type'],
        'spaceId': value['spaceId'],
        'childPosition': value['childPosition'],
    };
}

