/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ClassificationLevelColor = {
    Red: 'RED',
    RedBold: 'RED_BOLD',
    Orange: 'ORANGE',
    Yellow: 'YELLOW',
    Green: 'GREEN',
    Blue: 'BLUE',
    Navy: 'NAVY',
    Teal: 'TEAL',
    Purple: 'PURPLE',
    Grey: 'GREY',
    Lime: 'LIME'
} as const;
export type ClassificationLevelColor = typeof ClassificationLevelColor[keyof typeof ClassificationLevelColor];


export function instanceOfClassificationLevelColor(value: any): boolean {
    for (const key in ClassificationLevelColor) {
        if (Object.prototype.hasOwnProperty.call(ClassificationLevelColor, key)) {
            if (ClassificationLevelColor[key as keyof typeof ClassificationLevelColor] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ClassificationLevelColorFromJSON(json: any): ClassificationLevelColor {
    return ClassificationLevelColorFromJSONTyped(json, false);
}

export function ClassificationLevelColorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassificationLevelColor {
    return json as ClassificationLevelColor;
}

export function ClassificationLevelColorToJSON(value?: ClassificationLevelColor | null): any {
    return value as any;
}

export function ClassificationLevelColorToJSONTyped(value: any, ignoreDiscriminator: boolean): ClassificationLevelColor {
    return value as ClassificationLevelColor;
}

