/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VersionedEntity } from './VersionedEntity';
import {
    VersionedEntityFromJSON,
    VersionedEntityFromJSONTyped,
    VersionedEntityToJSON,
    VersionedEntityToJSONTyped,
} from './VersionedEntity';

/**
 * 
 * @export
 * @interface CommentVersion
 */
export interface CommentVersion {
    /**
     * Date and time when the version was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ".
     * @type {Date}
     * @memberof CommentVersion
     */
    createdAt?: Date;
    /**
     * Message associated with the current version.
     * @type {string}
     * @memberof CommentVersion
     */
    message?: string;
    /**
     * The version number.
     * @type {number}
     * @memberof CommentVersion
     */
    number?: number;
    /**
     * Describes if this version is a minor version. Email notifications and activity stream updates are not created for minor versions.
     * @type {boolean}
     * @memberof CommentVersion
     */
    minorEdit?: boolean;
    /**
     * The account ID of the user who created this version.
     * @type {string}
     * @memberof CommentVersion
     */
    authorId?: string;
    /**
     * 
     * @type {VersionedEntity}
     * @memberof CommentVersion
     */
    comment?: VersionedEntity;
}

/**
 * Check if a given object implements the CommentVersion interface.
 */
export function instanceOfCommentVersion(value: object): value is CommentVersion {
    return true;
}

export function CommentVersionFromJSON(json: any): CommentVersion {
    return CommentVersionFromJSONTyped(json, false);
}

export function CommentVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'message': json['message'] == null ? undefined : json['message'],
        'number': json['number'] == null ? undefined : json['number'],
        'minorEdit': json['minorEdit'] == null ? undefined : json['minorEdit'],
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
        'comment': json['comment'] == null ? undefined : VersionedEntityFromJSON(json['comment']),
    };
}

export function CommentVersionToJSON(json: any): CommentVersion {
    return CommentVersionToJSONTyped(json, false);
}

export function CommentVersionToJSONTyped(value?: CommentVersion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'message': value['message'],
        'number': value['number'],
        'minorEdit': value['minorEdit'],
        'authorId': value['authorId'],
        'comment': VersionedEntityToJSON(value['comment']),
    };
}

