/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommentBodyWrite } from './CommentBodyWrite';
import {
    CommentBodyWriteFromJSON,
    CommentBodyWriteFromJSONTyped,
    CommentBodyWriteToJSON,
    CommentBodyWriteToJSONTyped,
} from './CommentBodyWrite';

/**
 * Body of the comment. Only one body format should be specified as the property
 * for this object, e.g. `storage`.
 * @export
 * @interface CommentNestedBodyWrite
 */
export interface CommentNestedBodyWrite {
    /**
     * 
     * @type {CommentBodyWrite}
     * @memberof CommentNestedBodyWrite
     */
    storage?: CommentBodyWrite;
    /**
     * 
     * @type {CommentBodyWrite}
     * @memberof CommentNestedBodyWrite
     */
    atlasDocFormat?: CommentBodyWrite;
    /**
     * 
     * @type {CommentBodyWrite}
     * @memberof CommentNestedBodyWrite
     */
    wiki?: CommentBodyWrite;
}

/**
 * Check if a given object implements the CommentNestedBodyWrite interface.
 */
export function instanceOfCommentNestedBodyWrite(value: object): value is CommentNestedBodyWrite {
    return true;
}

export function CommentNestedBodyWriteFromJSON(json: any): CommentNestedBodyWrite {
    return CommentNestedBodyWriteFromJSONTyped(json, false);
}

export function CommentNestedBodyWriteFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentNestedBodyWrite {
    if (json == null) {
        return json;
    }
    return {
        
        'storage': json['storage'] == null ? undefined : CommentBodyWriteFromJSON(json['storage']),
        'atlasDocFormat': json['atlas_doc_format'] == null ? undefined : CommentBodyWriteFromJSON(json['atlas_doc_format']),
        'wiki': json['wiki'] == null ? undefined : CommentBodyWriteFromJSON(json['wiki']),
    };
}

export function CommentNestedBodyWriteToJSON(json: any): CommentNestedBodyWrite {
    return CommentNestedBodyWriteToJSONTyped(json, false);
}

export function CommentNestedBodyWriteToJSONTyped(value?: CommentNestedBodyWrite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'storage': CommentBodyWriteToJSON(value['storage']),
        'atlas_doc_format': CommentBodyWriteToJSON(value['atlasDocFormat']),
        'wiki': CommentBodyWriteToJSON(value['wiki']),
    };
}

