/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The sort fields for comments. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`.
 * @export
 */
export const CommentSortOrder = {
    CreatedDate: 'created-date',
    CreatedDate2: '-created-date',
    ModifiedDate: 'modified-date',
    ModifiedDate2: '-modified-date'
} as const;
export type CommentSortOrder = typeof CommentSortOrder[keyof typeof CommentSortOrder];


export function instanceOfCommentSortOrder(value: any): boolean {
    for (const key in CommentSortOrder) {
        if (Object.prototype.hasOwnProperty.call(CommentSortOrder, key)) {
            if (CommentSortOrder[key as keyof typeof CommentSortOrder] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CommentSortOrderFromJSON(json: any): CommentSortOrder {
    return CommentSortOrderFromJSONTyped(json, false);
}

export function CommentSortOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentSortOrder {
    return json as CommentSortOrder;
}

export function CommentSortOrderToJSON(value?: CommentSortOrder | null): any {
    return value as any;
}

export function CommentSortOrderToJSONTyped(value: any, ignoreDiscriminator: boolean): CommentSortOrder {
    return value as CommentSortOrder;
}

