/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentLinks
 */
export interface CommentLinks {
    /**
     * Web UI link of the content.
     * @type {string}
     * @memberof CommentLinks
     */
    webui?: string;
}

/**
 * Check if a given object implements the CommentLinks interface.
 */
export function instanceOfCommentLinks(value: object): value is CommentLinks {
    return true;
}

export function CommentLinksFromJSON(json: any): CommentLinks {
    return CommentLinksFromJSONTyped(json, false);
}

export function CommentLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'webui': json['webui'] == null ? undefined : json['webui'],
    };
}

export function CommentLinksToJSON(json: any): CommentLinks {
    return CommentLinksToJSONTyped(json, false);
}

export function CommentLinksToJSONTyped(value?: CommentLinks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'webui': value['webui'],
    };
}

