/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The sort fields for hierarchical content types. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`.
 * @export
 */
export const ContentSortOrder = {
    CreatedDate: 'created-date',
    CreatedDate2: '-created-date',
    Id: 'id',
    Id2: '-id',
    ModifiedDate: 'modified-date',
    ModifiedDate2: '-modified-date',
    ChildPosition: 'child-position',
    ChildPosition2: '-child-position',
    Title: 'title',
    Title2: '-title'
} as const;
export type ContentSortOrder = typeof ContentSortOrder[keyof typeof ContentSortOrder];


export function instanceOfContentSortOrder(value: any): boolean {
    for (const key in ContentSortOrder) {
        if (Object.prototype.hasOwnProperty.call(ContentSortOrder, key)) {
            if (ContentSortOrder[key as keyof typeof ContentSortOrder] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ContentSortOrderFromJSON(json: any): ContentSortOrder {
    return ContentSortOrderFromJSONTyped(json, false);
}

export function ContentSortOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentSortOrder {
    return json as ContentSortOrder;
}

export function ContentSortOrderToJSON(value?: ContentSortOrder | null): any {
    return value as any;
}

export function ContentSortOrderToJSONTyped(value: any, ignoreDiscriminator: boolean): ContentSortOrder {
    return value as ContentSortOrder;
}

