/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentIdToContentTypeResponseResultsValue } from './ContentIdToContentTypeResponseResultsValue';
import {
    ContentIdToContentTypeResponseResultsValueFromJSON,
    ContentIdToContentTypeResponseResultsValueFromJSONTyped,
    ContentIdToContentTypeResponseResultsValueToJSON,
    ContentIdToContentTypeResponseResultsValueToJSONTyped,
} from './ContentIdToContentTypeResponseResultsValue';

/**
 * 
 * @export
 * @interface ContentIdToContentTypeResponse
 */
export interface ContentIdToContentTypeResponse {
    /**
     * JSON object containing all requested content ids as keys and their associated content types as the values.
     * Duplicate content ids in the request will be returned under a single key in the response. For built-in content
     * types, the enumerations are as specified. Custom content ids will be mapped to their associated type.
     * @type {{ [key: string]: ContentIdToContentTypeResponseResultsValue; }}
     * @memberof ContentIdToContentTypeResponse
     */
    results?: { [key: string]: ContentIdToContentTypeResponseResultsValue; };
}

/**
 * Check if a given object implements the ContentIdToContentTypeResponse interface.
 */
export function instanceOfContentIdToContentTypeResponse(value: object): value is ContentIdToContentTypeResponse {
    return true;
}

export function ContentIdToContentTypeResponseFromJSON(json: any): ContentIdToContentTypeResponse {
    return ContentIdToContentTypeResponseFromJSONTyped(json, false);
}

export function ContentIdToContentTypeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentIdToContentTypeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : (mapValues(json['results'], ContentIdToContentTypeResponseResultsValueFromJSON)),
    };
}

export function ContentIdToContentTypeResponseToJSON(json: any): ContentIdToContentTypeResponse {
    return ContentIdToContentTypeResponseToJSONTyped(json, false);
}

export function ContentIdToContentTypeResponseToJSONTyped(value?: ContentIdToContentTypeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : (mapValues(value['results'], ContentIdToContentTypeResponseResultsValueToJSON)),
    };
}

