/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The status of the content.
 * @export
 */
export const ContentStatus = {
    Current: 'current',
    Draft: 'draft',
    Archived: 'archived',
    Historical: 'historical',
    Trashed: 'trashed',
    Deleted: 'deleted',
    Any: 'any'
} as const;
export type ContentStatus = typeof ContentStatus[keyof typeof ContentStatus];


export function instanceOfContentStatus(value: any): boolean {
    for (const key in ContentStatus) {
        if (Object.prototype.hasOwnProperty.call(ContentStatus, key)) {
            if (ContentStatus[key as keyof typeof ContentStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ContentStatusFromJSON(json: any): ContentStatus {
    return ContentStatusFromJSONTyped(json, false);
}

export function ContentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentStatus {
    return json as ContentStatus;
}

export function ContentStatusToJSON(value?: ContentStatus | null): any {
    return value as any;
}

export function ContentStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ContentStatus {
    return value as ContentStatus;
}

