/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The sort fields for content properties. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`.
 * @export
 */
export const ContentPropertySortOrder = {
    Key: 'key',
    Key2: '-key'
} as const;
export type ContentPropertySortOrder = typeof ContentPropertySortOrder[keyof typeof ContentPropertySortOrder];


export function instanceOfContentPropertySortOrder(value: any): boolean {
    for (const key in ContentPropertySortOrder) {
        if (Object.prototype.hasOwnProperty.call(ContentPropertySortOrder, key)) {
            if (ContentPropertySortOrder[key as keyof typeof ContentPropertySortOrder] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ContentPropertySortOrderFromJSON(json: any): ContentPropertySortOrder {
    return ContentPropertySortOrderFromJSONTyped(json, false);
}

export function ContentPropertySortOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentPropertySortOrder {
    return json as ContentPropertySortOrder;
}

export function ContentPropertySortOrderToJSON(value?: ContentPropertySortOrder | null): any {
    return value as any;
}

export function ContentPropertySortOrderToJSONTyped(value: any, ignoreDiscriminator: boolean): ContentPropertySortOrder {
    return value as ContentPropertySortOrder;
}

