/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConvertContentIdsToContentTypesRequestContentIdsInner } from './ConvertContentIdsToContentTypesRequestContentIdsInner';
import {
    ConvertContentIdsToContentTypesRequestContentIdsInnerFromJSON,
    ConvertContentIdsToContentTypesRequestContentIdsInnerFromJSONTyped,
    ConvertContentIdsToContentTypesRequestContentIdsInnerToJSON,
    ConvertContentIdsToContentTypesRequestContentIdsInnerToJSONTyped,
} from './ConvertContentIdsToContentTypesRequestContentIdsInner';

/**
 * 
 * @export
 * @interface ConvertContentIdsToContentTypesRequest
 */
export interface ConvertContentIdsToContentTypesRequest {
    /**
     * The content ids to convert. They may be provided as strings or numbers.
     * @type {Array<ConvertContentIdsToContentTypesRequestContentIdsInner>}
     * @memberof ConvertContentIdsToContentTypesRequest
     */
    contentIds: Array<ConvertContentIdsToContentTypesRequestContentIdsInner>;
}

/**
 * Check if a given object implements the ConvertContentIdsToContentTypesRequest interface.
 */
export function instanceOfConvertContentIdsToContentTypesRequest(value: object): value is ConvertContentIdsToContentTypesRequest {
    if (!('contentIds' in value) || value['contentIds'] === undefined) return false;
    return true;
}

export function ConvertContentIdsToContentTypesRequestFromJSON(json: any): ConvertContentIdsToContentTypesRequest {
    return ConvertContentIdsToContentTypesRequestFromJSONTyped(json, false);
}

export function ConvertContentIdsToContentTypesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConvertContentIdsToContentTypesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'contentIds': ((json['contentIds'] as Array<any>).map(ConvertContentIdsToContentTypesRequestContentIdsInnerFromJSON)),
    };
}

export function ConvertContentIdsToContentTypesRequestToJSON(json: any): ConvertContentIdsToContentTypesRequest {
    return ConvertContentIdsToContentTypesRequestToJSONTyped(json, false);
}

export function ConvertContentIdsToContentTypesRequestToJSONTyped(value?: ConvertContentIdsToContentTypesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contentIds': ((value['contentIds'] as Array<any>).map(ConvertContentIdsToContentTypesRequestContentIdsInnerToJSON)),
    };
}

