/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateFooterCommentModelBody } from './CreateFooterCommentModelBody';
import {
    CreateFooterCommentModelBodyFromJSON,
    CreateFooterCommentModelBodyFromJSONTyped,
    CreateFooterCommentModelBodyToJSON,
    CreateFooterCommentModelBodyToJSONTyped,
} from './CreateFooterCommentModelBody';
import type { CreateInlineCommentModelInlineCommentProperties } from './CreateInlineCommentModelInlineCommentProperties';
import {
    CreateInlineCommentModelInlineCommentPropertiesFromJSON,
    CreateInlineCommentModelInlineCommentPropertiesFromJSONTyped,
    CreateInlineCommentModelInlineCommentPropertiesToJSON,
    CreateInlineCommentModelInlineCommentPropertiesToJSONTyped,
} from './CreateInlineCommentModelInlineCommentProperties';

/**
 * 
 * @export
 * @interface CreateInlineCommentModel
 */
export interface CreateInlineCommentModel {
    /**
     * ID of the containing blog post, if intending to create a top level footer comment. Do not provide if creating a reply.
     * @type {string}
     * @memberof CreateInlineCommentModel
     */
    blogPostId?: string;
    /**
     * ID of the containing page, if intending to create a top level footer comment. Do not provide if creating a reply.
     * @type {string}
     * @memberof CreateInlineCommentModel
     */
    pageId?: string;
    /**
     * ID of the parent comment, if intending to create a reply. Do not provide if creating a top level comment.
     * @type {string}
     * @memberof CreateInlineCommentModel
     */
    parentCommentId?: string;
    /**
     * 
     * @type {CreateFooterCommentModelBody}
     * @memberof CreateInlineCommentModel
     */
    body?: CreateFooterCommentModelBody;
    /**
     * 
     * @type {CreateInlineCommentModelInlineCommentProperties}
     * @memberof CreateInlineCommentModel
     */
    inlineCommentProperties?: CreateInlineCommentModelInlineCommentProperties;
}

/**
 * Check if a given object implements the CreateInlineCommentModel interface.
 */
export function instanceOfCreateInlineCommentModel(value: object): value is CreateInlineCommentModel {
    return true;
}

export function CreateInlineCommentModelFromJSON(json: any): CreateInlineCommentModel {
    return CreateInlineCommentModelFromJSONTyped(json, false);
}

export function CreateInlineCommentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInlineCommentModel {
    if (json == null) {
        return json;
    }
    return {
        
        'blogPostId': json['blogPostId'] == null ? undefined : json['blogPostId'],
        'pageId': json['pageId'] == null ? undefined : json['pageId'],
        'parentCommentId': json['parentCommentId'] == null ? undefined : json['parentCommentId'],
        'body': json['body'] == null ? undefined : CreateFooterCommentModelBodyFromJSON(json['body']),
        'inlineCommentProperties': json['inlineCommentProperties'] == null ? undefined : CreateInlineCommentModelInlineCommentPropertiesFromJSON(json['inlineCommentProperties']),
    };
}

export function CreateInlineCommentModelToJSON(json: any): CreateInlineCommentModel {
    return CreateInlineCommentModelToJSONTyped(json, false);
}

export function CreateInlineCommentModelToJSONTyped(value?: CreateInlineCommentModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'blogPostId': value['blogPostId'],
        'pageId': value['pageId'],
        'parentCommentId': value['parentCommentId'],
        'body': CreateFooterCommentModelBodyToJSON(value['body']),
        'inlineCommentProperties': CreateInlineCommentModelInlineCommentPropertiesToJSON(value['inlineCommentProperties']),
    };
}

