/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttachmentSingleProperties } from './AttachmentSingleProperties';
import {
    AttachmentSinglePropertiesFromJSON,
    AttachmentSinglePropertiesFromJSONTyped,
    AttachmentSinglePropertiesToJSON,
    AttachmentSinglePropertiesToJSONTyped,
} from './AttachmentSingleProperties';
import type { BlogPostSingleLikes } from './BlogPostSingleLikes';
import {
    BlogPostSingleLikesFromJSON,
    BlogPostSingleLikesFromJSONTyped,
    BlogPostSingleLikesToJSON,
    BlogPostSingleLikesToJSONTyped,
} from './BlogPostSingleLikes';
import type { Version } from './Version';
import {
    VersionFromJSON,
    VersionFromJSONTyped,
    VersionToJSON,
    VersionToJSONTyped,
} from './Version';
import type { AttachmentSingleOperations } from './AttachmentSingleOperations';
import {
    AttachmentSingleOperationsFromJSON,
    AttachmentSingleOperationsFromJSONTyped,
    AttachmentSingleOperationsToJSON,
    AttachmentSingleOperationsToJSONTyped,
} from './AttachmentSingleOperations';
import type { AttachmentSingleLabels } from './AttachmentSingleLabels';
import {
    AttachmentSingleLabelsFromJSON,
    AttachmentSingleLabelsFromJSONTyped,
    AttachmentSingleLabelsToJSON,
    AttachmentSingleLabelsToJSONTyped,
} from './AttachmentSingleLabels';
import type { GetAttachmentById200ResponseAllOfLinks } from './GetAttachmentById200ResponseAllOfLinks';
import {
    GetAttachmentById200ResponseAllOfLinksFromJSON,
    GetAttachmentById200ResponseAllOfLinksFromJSONTyped,
    GetAttachmentById200ResponseAllOfLinksToJSON,
    GetAttachmentById200ResponseAllOfLinksToJSONTyped,
} from './GetAttachmentById200ResponseAllOfLinks';
import type { BodySingle } from './BodySingle';
import {
    BodySingleFromJSON,
    BodySingleFromJSONTyped,
    BodySingleToJSON,
    BodySingleToJSONTyped,
} from './BodySingle';
import type { ParentContentType } from './ParentContentType';
import {
    ParentContentTypeFromJSON,
    ParentContentTypeFromJSONTyped,
    ParentContentTypeToJSON,
    ParentContentTypeToJSONTyped,
} from './ParentContentType';
import type { AttachmentSingleVersions } from './AttachmentSingleVersions';
import {
    AttachmentSingleVersionsFromJSON,
    AttachmentSingleVersionsFromJSONTyped,
    AttachmentSingleVersionsToJSON,
    AttachmentSingleVersionsToJSONTyped,
} from './AttachmentSingleVersions';
import type { ContentStatus } from './ContentStatus';
import {
    ContentStatusFromJSON,
    ContentStatusFromJSONTyped,
    ContentStatusToJSON,
    ContentStatusToJSONTyped,
} from './ContentStatus';

/**
 * 
 * @export
 * @interface CreatePage200Response
 */
export interface CreatePage200Response {
    /**
     * ID of the page.
     * @type {string}
     * @memberof CreatePage200Response
     */
    id?: string;
    /**
     * 
     * @type {ContentStatus}
     * @memberof CreatePage200Response
     */
    status?: ContentStatus;
    /**
     * Title of the page.
     * @type {string}
     * @memberof CreatePage200Response
     */
    title?: string;
    /**
     * ID of the space the page is in.
     * @type {string}
     * @memberof CreatePage200Response
     */
    spaceId?: string;
    /**
     * ID of the parent page, or null if there is no parent page.
     * @type {string}
     * @memberof CreatePage200Response
     */
    parentId?: string;
    /**
     * 
     * @type {ParentContentType}
     * @memberof CreatePage200Response
     */
    parentType?: ParentContentType;
    /**
     * Position of child page within the given parent page tree.
     * @type {number}
     * @memberof CreatePage200Response
     */
    position?: number | null;
    /**
     * The account ID of the user who created this page originally.
     * @type {string}
     * @memberof CreatePage200Response
     */
    authorId?: string;
    /**
     * The account ID of the user who owns this page.
     * @type {string}
     * @memberof CreatePage200Response
     */
    ownerId?: string | null;
    /**
     * The account ID of the user who owned this page previously, or null if there is no previous owner.
     * @type {string}
     * @memberof CreatePage200Response
     */
    lastOwnerId?: string | null;
    /**
     * Date and time when the page was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ".
     * @type {Date}
     * @memberof CreatePage200Response
     */
    createdAt?: Date;
    /**
     * 
     * @type {Version}
     * @memberof CreatePage200Response
     */
    version?: Version;
    /**
     * 
     * @type {BodySingle}
     * @memberof CreatePage200Response
     */
    body?: BodySingle;
    /**
     * 
     * @type {AttachmentSingleLabels}
     * @memberof CreatePage200Response
     */
    labels?: AttachmentSingleLabels;
    /**
     * 
     * @type {AttachmentSingleProperties}
     * @memberof CreatePage200Response
     */
    properties?: AttachmentSingleProperties;
    /**
     * 
     * @type {AttachmentSingleOperations}
     * @memberof CreatePage200Response
     */
    operations?: AttachmentSingleOperations;
    /**
     * 
     * @type {BlogPostSingleLikes}
     * @memberof CreatePage200Response
     */
    likes?: BlogPostSingleLikes;
    /**
     * 
     * @type {AttachmentSingleVersions}
     * @memberof CreatePage200Response
     */
    versions?: AttachmentSingleVersions;
    /**
     * Whether the page has been favorited by the current user.
     * @type {boolean}
     * @memberof CreatePage200Response
     */
    isFavoritedByCurrentUser?: boolean;
    /**
     * 
     * @type {GetAttachmentById200ResponseAllOfLinks}
     * @memberof CreatePage200Response
     */
    links?: GetAttachmentById200ResponseAllOfLinks;
}



/**
 * Check if a given object implements the CreatePage200Response interface.
 */
export function instanceOfCreatePage200Response(value: object): value is CreatePage200Response {
    return true;
}

export function CreatePage200ResponseFromJSON(json: any): CreatePage200Response {
    return CreatePage200ResponseFromJSONTyped(json, false);
}

export function CreatePage200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePage200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : ContentStatusFromJSON(json['status']),
        'title': json['title'] == null ? undefined : json['title'],
        'spaceId': json['spaceId'] == null ? undefined : json['spaceId'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'parentType': json['parentType'] == null ? undefined : ParentContentTypeFromJSON(json['parentType']),
        'position': json['position'] == null ? undefined : json['position'],
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
        'lastOwnerId': json['lastOwnerId'] == null ? undefined : json['lastOwnerId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'version': json['version'] == null ? undefined : VersionFromJSON(json['version']),
        'body': json['body'] == null ? undefined : BodySingleFromJSON(json['body']),
        'labels': json['labels'] == null ? undefined : AttachmentSingleLabelsFromJSON(json['labels']),
        'properties': json['properties'] == null ? undefined : AttachmentSinglePropertiesFromJSON(json['properties']),
        'operations': json['operations'] == null ? undefined : AttachmentSingleOperationsFromJSON(json['operations']),
        'likes': json['likes'] == null ? undefined : BlogPostSingleLikesFromJSON(json['likes']),
        'versions': json['versions'] == null ? undefined : AttachmentSingleVersionsFromJSON(json['versions']),
        'isFavoritedByCurrentUser': json['isFavoritedByCurrentUser'] == null ? undefined : json['isFavoritedByCurrentUser'],
        'links': json['_links'] == null ? undefined : GetAttachmentById200ResponseAllOfLinksFromJSON(json['_links']),
    };
}

export function CreatePage200ResponseToJSON(json: any): CreatePage200Response {
    return CreatePage200ResponseToJSONTyped(json, false);
}

export function CreatePage200ResponseToJSONTyped(value?: CreatePage200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': ContentStatusToJSON(value['status']),
        'title': value['title'],
        'spaceId': value['spaceId'],
        'parentId': value['parentId'],
        'parentType': ParentContentTypeToJSON(value['parentType']),
        'position': value['position'],
        'authorId': value['authorId'],
        'ownerId': value['ownerId'],
        'lastOwnerId': value['lastOwnerId'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'version': VersionToJSON(value['version']),
        'body': BodySingleToJSON(value['body']),
        'labels': AttachmentSingleLabelsToJSON(value['labels']),
        'properties': AttachmentSinglePropertiesToJSON(value['properties']),
        'operations': AttachmentSingleOperationsToJSON(value['operations']),
        'likes': BlogPostSingleLikesToJSON(value['likes']),
        'versions': AttachmentSingleVersionsToJSON(value['versions']),
        'isFavoritedByCurrentUser': value['isFavoritedByCurrentUser'],
        '_links': GetAttachmentById200ResponseAllOfLinksToJSON(value['links']),
    };
}

