/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlogPostSingleLikes } from './BlogPostSingleLikes';
import {
    BlogPostSingleLikesFromJSON,
    BlogPostSingleLikesFromJSONTyped,
    BlogPostSingleLikesToJSON,
    BlogPostSingleLikesToJSONTyped,
} from './BlogPostSingleLikes';
import type { Version } from './Version';
import {
    VersionFromJSON,
    VersionFromJSONTyped,
    VersionToJSON,
    VersionToJSONTyped,
} from './Version';
import type { AttachmentSingleOperations } from './AttachmentSingleOperations';
import {
    AttachmentSingleOperationsFromJSON,
    AttachmentSingleOperationsFromJSONTyped,
    AttachmentSingleOperationsToJSON,
    AttachmentSingleOperationsToJSONTyped,
} from './AttachmentSingleOperations';
import type { InlineCommentResolutionStatus } from './InlineCommentResolutionStatus';
import {
    InlineCommentResolutionStatusFromJSON,
    InlineCommentResolutionStatusFromJSONTyped,
    InlineCommentResolutionStatusToJSON,
    InlineCommentResolutionStatusToJSONTyped,
} from './InlineCommentResolutionStatus';
import type { GetAttachmentById200ResponseAllOfLinks } from './GetAttachmentById200ResponseAllOfLinks';
import {
    GetAttachmentById200ResponseAllOfLinksFromJSON,
    GetAttachmentById200ResponseAllOfLinksFromJSONTyped,
    GetAttachmentById200ResponseAllOfLinksToJSON,
    GetAttachmentById200ResponseAllOfLinksToJSONTyped,
} from './GetAttachmentById200ResponseAllOfLinks';
import type { InlineCommentModelProperties } from './InlineCommentModelProperties';
import {
    InlineCommentModelPropertiesFromJSON,
    InlineCommentModelPropertiesFromJSONTyped,
    InlineCommentModelPropertiesToJSON,
    InlineCommentModelPropertiesToJSONTyped,
} from './InlineCommentModelProperties';
import type { BodySingle } from './BodySingle';
import {
    BodySingleFromJSON,
    BodySingleFromJSONTyped,
    BodySingleToJSON,
    BodySingleToJSONTyped,
} from './BodySingle';
import type { AttachmentSingleVersions } from './AttachmentSingleVersions';
import {
    AttachmentSingleVersionsFromJSON,
    AttachmentSingleVersionsFromJSONTyped,
    AttachmentSingleVersionsToJSON,
    AttachmentSingleVersionsToJSONTyped,
} from './AttachmentSingleVersions';
import type { ContentStatus } from './ContentStatus';
import {
    ContentStatusFromJSON,
    ContentStatusFromJSONTyped,
    ContentStatusToJSON,
    ContentStatusToJSONTyped,
} from './ContentStatus';

/**
 * 
 * @export
 * @interface CreateInlineComment201Response
 */
export interface CreateInlineComment201Response {
    /**
     * ID of the comment.
     * @type {string}
     * @memberof CreateInlineComment201Response
     */
    id?: string;
    /**
     * 
     * @type {ContentStatus}
     * @memberof CreateInlineComment201Response
     */
    status?: ContentStatus;
    /**
     * Title of the comment.
     * @type {string}
     * @memberof CreateInlineComment201Response
     */
    title?: string;
    /**
     * ID of the blog post containing the comment if the comment is on a blog post.
     * @type {string}
     * @memberof CreateInlineComment201Response
     */
    blogPostId?: string;
    /**
     * ID of the page containing the comment if the comment is on a page.
     * @type {string}
     * @memberof CreateInlineComment201Response
     */
    pageId?: string;
    /**
     * ID of the parent comment if the comment is a reply.
     * @type {string}
     * @memberof CreateInlineComment201Response
     */
    parentCommentId?: string;
    /**
     * 
     * @type {Version}
     * @memberof CreateInlineComment201Response
     */
    version?: Version;
    /**
     * 
     * @type {BodySingle}
     * @memberof CreateInlineComment201Response
     */
    body?: BodySingle;
    /**
     * Atlassian Account ID of last person who modified the resolve state of the comment. Null until comment is resolved or reopened.
     * @type {string}
     * @memberof CreateInlineComment201Response
     */
    resolutionLastModifierId?: string;
    /**
     * Timestamp of the last modification to the comment's resolution status. Null until comment is resolved or reopened.
     * @type {Date}
     * @memberof CreateInlineComment201Response
     */
    resolutionLastModifiedAt?: Date;
    /**
     * 
     * @type {InlineCommentResolutionStatus}
     * @memberof CreateInlineComment201Response
     */
    resolutionStatus?: InlineCommentResolutionStatus;
    /**
     * 
     * @type {InlineCommentModelProperties}
     * @memberof CreateInlineComment201Response
     */
    properties?: InlineCommentModelProperties;
    /**
     * 
     * @type {AttachmentSingleOperations}
     * @memberof CreateInlineComment201Response
     */
    operations?: AttachmentSingleOperations;
    /**
     * 
     * @type {BlogPostSingleLikes}
     * @memberof CreateInlineComment201Response
     */
    likes?: BlogPostSingleLikes;
    /**
     * 
     * @type {AttachmentSingleVersions}
     * @memberof CreateInlineComment201Response
     */
    versions?: AttachmentSingleVersions;
    /**
     * 
     * @type {GetAttachmentById200ResponseAllOfLinks}
     * @memberof CreateInlineComment201Response
     */
    links?: GetAttachmentById200ResponseAllOfLinks;
}



/**
 * Check if a given object implements the CreateInlineComment201Response interface.
 */
export function instanceOfCreateInlineComment201Response(value: object): value is CreateInlineComment201Response {
    return true;
}

export function CreateInlineComment201ResponseFromJSON(json: any): CreateInlineComment201Response {
    return CreateInlineComment201ResponseFromJSONTyped(json, false);
}

export function CreateInlineComment201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInlineComment201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : ContentStatusFromJSON(json['status']),
        'title': json['title'] == null ? undefined : json['title'],
        'blogPostId': json['blogPostId'] == null ? undefined : json['blogPostId'],
        'pageId': json['pageId'] == null ? undefined : json['pageId'],
        'parentCommentId': json['parentCommentId'] == null ? undefined : json['parentCommentId'],
        'version': json['version'] == null ? undefined : VersionFromJSON(json['version']),
        'body': json['body'] == null ? undefined : BodySingleFromJSON(json['body']),
        'resolutionLastModifierId': json['resolutionLastModifierId'] == null ? undefined : json['resolutionLastModifierId'],
        'resolutionLastModifiedAt': json['resolutionLastModifiedAt'] == null ? undefined : (new Date(json['resolutionLastModifiedAt'])),
        'resolutionStatus': json['resolutionStatus'] == null ? undefined : InlineCommentResolutionStatusFromJSON(json['resolutionStatus']),
        'properties': json['properties'] == null ? undefined : InlineCommentModelPropertiesFromJSON(json['properties']),
        'operations': json['operations'] == null ? undefined : AttachmentSingleOperationsFromJSON(json['operations']),
        'likes': json['likes'] == null ? undefined : BlogPostSingleLikesFromJSON(json['likes']),
        'versions': json['versions'] == null ? undefined : AttachmentSingleVersionsFromJSON(json['versions']),
        'links': json['_links'] == null ? undefined : GetAttachmentById200ResponseAllOfLinksFromJSON(json['_links']),
    };
}

export function CreateInlineComment201ResponseToJSON(json: any): CreateInlineComment201Response {
    return CreateInlineComment201ResponseToJSONTyped(json, false);
}

export function CreateInlineComment201ResponseToJSONTyped(value?: CreateInlineComment201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': ContentStatusToJSON(value['status']),
        'title': value['title'],
        'blogPostId': value['blogPostId'],
        'pageId': value['pageId'],
        'parentCommentId': value['parentCommentId'],
        'version': VersionToJSON(value['version']),
        'body': BodySingleToJSON(value['body']),
        'resolutionLastModifierId': value['resolutionLastModifierId'],
        'resolutionLastModifiedAt': value['resolutionLastModifiedAt'] == null ? value['resolutionLastModifiedAt'] : value['resolutionLastModifiedAt'].toISOString(),
        'resolutionStatus': InlineCommentResolutionStatusToJSON(value['resolutionStatus']),
        'properties': InlineCommentModelPropertiesToJSON(value['properties']),
        'operations': AttachmentSingleOperationsToJSON(value['operations']),
        'likes': BlogPostSingleLikesToJSON(value['likes']),
        'versions': AttachmentSingleVersionsToJSON(value['versions']),
        '_links': GetAttachmentById200ResponseAllOfLinksToJSON(value['links']),
    };
}

