/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSmartLinkRequest
 */
export interface CreateSmartLinkRequest {
    /**
     * ID of the space.
     * @type {string}
     * @memberof CreateSmartLinkRequest
     */
    spaceId: string;
    /**
     * Title of the Smart Link in the content tree.
     * @type {string}
     * @memberof CreateSmartLinkRequest
     */
    title?: string;
    /**
     * The parent content ID of the Smart Link in the content tree.
     * @type {string}
     * @memberof CreateSmartLinkRequest
     */
    parentId?: string;
    /**
     * The URL that the Smart Link in the content tree should be populated with.
     * @type {string}
     * @memberof CreateSmartLinkRequest
     */
    embedUrl?: string;
}

/**
 * Check if a given object implements the CreateSmartLinkRequest interface.
 */
export function instanceOfCreateSmartLinkRequest(value: object): value is CreateSmartLinkRequest {
    if (!('spaceId' in value) || value['spaceId'] === undefined) return false;
    return true;
}

export function CreateSmartLinkRequestFromJSON(json: any): CreateSmartLinkRequest {
    return CreateSmartLinkRequestFromJSONTyped(json, false);
}

export function CreateSmartLinkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSmartLinkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'spaceId': json['spaceId'],
        'title': json['title'] == null ? undefined : json['title'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'embedUrl': json['embedUrl'] == null ? undefined : json['embedUrl'],
    };
}

export function CreateSmartLinkRequestToJSON(json: any): CreateSmartLinkRequest {
    return CreateSmartLinkRequestToJSONTyped(json, false);
}

export function CreateSmartLinkRequestToJSONTyped(value?: CreateSmartLinkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'spaceId': value['spaceId'],
        'title': value['title'],
        'parentId': value['parentId'],
        'embedUrl': value['embedUrl'],
    };
}

