/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateFooterCommentModelBody } from './CreateFooterCommentModelBody';
import {
    CreateFooterCommentModelBodyFromJSON,
    CreateFooterCommentModelBodyFromJSONTyped,
    CreateFooterCommentModelBodyToJSON,
    CreateFooterCommentModelBodyToJSONTyped,
} from './CreateFooterCommentModelBody';

/**
 * 
 * @export
 * @interface CreateFooterCommentModel
 */
export interface CreateFooterCommentModel {
    /**
     * ID of the containing blog post, if intending to create a top level footer comment. Do not provide if creating a reply.
     * @type {string}
     * @memberof CreateFooterCommentModel
     */
    blogPostId?: string;
    /**
     * ID of the containing page, if intending to create a top level footer comment. Do not provide if creating a reply.
     * @type {string}
     * @memberof CreateFooterCommentModel
     */
    pageId?: string;
    /**
     * ID of the parent comment, if intending to create a reply. Do not provide if creating a top level comment.
     * @type {string}
     * @memberof CreateFooterCommentModel
     */
    parentCommentId?: string;
    /**
     * ID of the attachment, if intending to create a comment against an attachment.
     * @type {string}
     * @memberof CreateFooterCommentModel
     */
    attachmentId?: string;
    /**
     * ID of the custom content, if intending to create a comment against a custom content.
     * @type {string}
     * @memberof CreateFooterCommentModel
     */
    customContentId?: string;
    /**
     * 
     * @type {CreateFooterCommentModelBody}
     * @memberof CreateFooterCommentModel
     */
    body?: CreateFooterCommentModelBody;
}

/**
 * Check if a given object implements the CreateFooterCommentModel interface.
 */
export function instanceOfCreateFooterCommentModel(value: object): value is CreateFooterCommentModel {
    return true;
}

export function CreateFooterCommentModelFromJSON(json: any): CreateFooterCommentModel {
    return CreateFooterCommentModelFromJSONTyped(json, false);
}

export function CreateFooterCommentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFooterCommentModel {
    if (json == null) {
        return json;
    }
    return {
        
        'blogPostId': json['blogPostId'] == null ? undefined : json['blogPostId'],
        'pageId': json['pageId'] == null ? undefined : json['pageId'],
        'parentCommentId': json['parentCommentId'] == null ? undefined : json['parentCommentId'],
        'attachmentId': json['attachmentId'] == null ? undefined : json['attachmentId'],
        'customContentId': json['customContentId'] == null ? undefined : json['customContentId'],
        'body': json['body'] == null ? undefined : CreateFooterCommentModelBodyFromJSON(json['body']),
    };
}

export function CreateFooterCommentModelToJSON(json: any): CreateFooterCommentModel {
    return CreateFooterCommentModelToJSONTyped(json, false);
}

export function CreateFooterCommentModelToJSONTyped(value?: CreateFooterCommentModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'blogPostId': value['blogPostId'],
        'pageId': value['pageId'],
        'parentCommentId': value['parentCommentId'],
        'attachmentId': value['attachmentId'],
        'customContentId': value['customContentId'],
        'body': CreateFooterCommentModelBodyToJSON(value['body']),
    };
}

