/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFolderRequest
 */
export interface CreateFolderRequest {
    /**
     * ID of the space.
     * @type {string}
     * @memberof CreateFolderRequest
     */
    spaceId: string;
    /**
     * Title of the folder.
     * @type {string}
     * @memberof CreateFolderRequest
     */
    title?: string;
    /**
     * The parent content ID of the folder.
     * @type {string}
     * @memberof CreateFolderRequest
     */
    parentId?: string;
}

/**
 * Check if a given object implements the CreateFolderRequest interface.
 */
export function instanceOfCreateFolderRequest(value: object): value is CreateFolderRequest {
    if (!('spaceId' in value) || value['spaceId'] === undefined) return false;
    return true;
}

export function CreateFolderRequestFromJSON(json: any): CreateFolderRequest {
    return CreateFolderRequestFromJSONTyped(json, false);
}

export function CreateFolderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFolderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'spaceId': json['spaceId'],
        'title': json['title'] == null ? undefined : json['title'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
    };
}

export function CreateFolderRequestToJSON(json: any): CreateFolderRequest {
    return CreateFolderRequestToJSONTyped(json, false);
}

export function CreateFolderRequestToJSONTyped(value?: CreateFolderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'spaceId': value['spaceId'],
        'title': value['title'],
        'parentId': value['parentId'],
    };
}

