/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDatabaseRequest
 */
export interface CreateDatabaseRequest {
    /**
     * ID of the space.
     * @type {string}
     * @memberof CreateDatabaseRequest
     */
    spaceId: string;
    /**
     * Title of the database.
     * @type {string}
     * @memberof CreateDatabaseRequest
     */
    title?: string;
    /**
     * The parent content ID of the database.
     * @type {string}
     * @memberof CreateDatabaseRequest
     */
    parentId?: string;
}

/**
 * Check if a given object implements the CreateDatabaseRequest interface.
 */
export function instanceOfCreateDatabaseRequest(value: object): value is CreateDatabaseRequest {
    if (!('spaceId' in value) || value['spaceId'] === undefined) return false;
    return true;
}

export function CreateDatabaseRequestFromJSON(json: any): CreateDatabaseRequest {
    return CreateDatabaseRequestFromJSONTyped(json, false);
}

export function CreateDatabaseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDatabaseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'spaceId': json['spaceId'],
        'title': json['title'] == null ? undefined : json['title'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
    };
}

export function CreateDatabaseRequestToJSON(json: any): CreateDatabaseRequest {
    return CreateDatabaseRequestToJSONTyped(json, false);
}

export function CreateDatabaseRequestToJSONTyped(value?: CreateDatabaseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'spaceId': value['spaceId'],
        'title': value['title'],
        'parentId': value['parentId'],
    };
}

