/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateCustomContentRequestBody } from './CreateCustomContentRequestBody';
import {
    CreateCustomContentRequestBodyFromJSON,
    CreateCustomContentRequestBodyFromJSONTyped,
    CreateCustomContentRequestBodyToJSON,
    CreateCustomContentRequestBodyToJSONTyped,
} from './CreateCustomContentRequestBody';

/**
 * 
 * @export
 * @interface CreateCustomContentRequest
 */
export interface CreateCustomContentRequest {
    /**
     * Type of custom content.
     * @type {string}
     * @memberof CreateCustomContentRequest
     */
    type: string;
    /**
     * The status of the custom content. Defaults to `current` when status not provided.
     * @type {string}
     * @memberof CreateCustomContentRequest
     */
    status?: CreateCustomContentRequestStatusEnum;
    /**
     * ID of the containing space.
     * @type {string}
     * @memberof CreateCustomContentRequest
     */
    spaceId?: string;
    /**
     * ID of the containing page.
     * @type {string}
     * @memberof CreateCustomContentRequest
     */
    pageId?: string;
    /**
     * ID of the containing Blog Post.
     * @type {string}
     * @memberof CreateCustomContentRequest
     */
    blogPostId?: string;
    /**
     * ID of the containing custom content.
     * @type {string}
     * @memberof CreateCustomContentRequest
     */
    customContentId?: string;
    /**
     * Title of the custom content.
     * @type {string}
     * @memberof CreateCustomContentRequest
     */
    title: string;
    /**
     * 
     * @type {CreateCustomContentRequestBody}
     * @memberof CreateCustomContentRequest
     */
    body: CreateCustomContentRequestBody;
}


/**
 * @export
 */
export const CreateCustomContentRequestStatusEnum = {
    Current: 'current',
    Draft: 'draft'
} as const;
export type CreateCustomContentRequestStatusEnum = typeof CreateCustomContentRequestStatusEnum[keyof typeof CreateCustomContentRequestStatusEnum];


/**
 * Check if a given object implements the CreateCustomContentRequest interface.
 */
export function instanceOfCreateCustomContentRequest(value: object): value is CreateCustomContentRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function CreateCustomContentRequestFromJSON(json: any): CreateCustomContentRequest {
    return CreateCustomContentRequestFromJSONTyped(json, false);
}

export function CreateCustomContentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCustomContentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'status': json['status'] == null ? undefined : json['status'],
        'spaceId': json['spaceId'] == null ? undefined : json['spaceId'],
        'pageId': json['pageId'] == null ? undefined : json['pageId'],
        'blogPostId': json['blogPostId'] == null ? undefined : json['blogPostId'],
        'customContentId': json['customContentId'] == null ? undefined : json['customContentId'],
        'title': json['title'],
        'body': CreateCustomContentRequestBodyFromJSON(json['body']),
    };
}

export function CreateCustomContentRequestToJSON(json: any): CreateCustomContentRequest {
    return CreateCustomContentRequestToJSONTyped(json, false);
}

export function CreateCustomContentRequestToJSONTyped(value?: CreateCustomContentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'status': value['status'],
        'spaceId': value['spaceId'],
        'pageId': value['pageId'],
        'blogPostId': value['blogPostId'],
        'customContentId': value['customContentId'],
        'title': value['title'],
        'body': CreateCustomContentRequestBodyToJSON(value['body']),
    };
}

