/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSpaceRoleRequest
 */
export interface CreateSpaceRoleRequest {
    /**
     * Name of the space role
     * @type {string}
     * @memberof CreateSpaceRoleRequest
     */
    name: string;
    /**
     * Description for the space role
     * @type {string}
     * @memberof CreateSpaceRoleRequest
     */
    description: string;
    /**
     * The ids of the space permissions associated with the space role. Sample value "read/space"; retrieve ids from responses returned by [GET /space-permissions](https://developer.atlassian.com/cloud/confluence/rest/v2/api-group-space-permissions/#api-space-permissions-get) endpoint
     * @type {Array<string>}
     * @memberof CreateSpaceRoleRequest
     */
    spacePermissions: Array<string>;
}

/**
 * Check if a given object implements the CreateSpaceRoleRequest interface.
 */
export function instanceOfCreateSpaceRoleRequest(value: object): value is CreateSpaceRoleRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('spacePermissions' in value) || value['spacePermissions'] === undefined) return false;
    return true;
}

export function CreateSpaceRoleRequestFromJSON(json: any): CreateSpaceRoleRequest {
    return CreateSpaceRoleRequestFromJSONTyped(json, false);
}

export function CreateSpaceRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSpaceRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'spacePermissions': json['spacePermissions'],
    };
}

export function CreateSpaceRoleRequestToJSON(json: any): CreateSpaceRoleRequest {
    return CreateSpaceRoleRequestToJSONTyped(json, false);
}

export function CreateSpaceRoleRequestToJSONTyped(value?: CreateSpaceRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'spacePermissions': value['spacePermissions'],
    };
}

