/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Object describing the text to highlight on the page/blog post. Only applicable for top level inline comments (not replies) and required in that case.
 * @export
 * @interface CreateInlineCommentModelInlineCommentProperties
 */
export interface CreateInlineCommentModelInlineCommentProperties {
    /**
     * The text to highlight
     * @type {string}
     * @memberof CreateInlineCommentModelInlineCommentProperties
     */
    textSelection?: string;
    /**
     * The number of matches for the selected text on the page (should be strictly greater than textSelectionMatchIndex)
     * @type {number}
     * @memberof CreateInlineCommentModelInlineCommentProperties
     */
    textSelectionMatchCount?: number;
    /**
     * The match index to highlight. This is zero-based. E.g. if you have 3 occurrences of "hello world" on a page 
     * and you want to highlight the second occurrence, you should pass 1 for textSelectionMatchIndex and 3 for textSelectionMatchCount.
     * @type {number}
     * @memberof CreateInlineCommentModelInlineCommentProperties
     */
    textSelectionMatchIndex?: number;
}

/**
 * Check if a given object implements the CreateInlineCommentModelInlineCommentProperties interface.
 */
export function instanceOfCreateInlineCommentModelInlineCommentProperties(value: object): value is CreateInlineCommentModelInlineCommentProperties {
    return true;
}

export function CreateInlineCommentModelInlineCommentPropertiesFromJSON(json: any): CreateInlineCommentModelInlineCommentProperties {
    return CreateInlineCommentModelInlineCommentPropertiesFromJSONTyped(json, false);
}

export function CreateInlineCommentModelInlineCommentPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInlineCommentModelInlineCommentProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'textSelection': json['textSelection'] == null ? undefined : json['textSelection'],
        'textSelectionMatchCount': json['textSelectionMatchCount'] == null ? undefined : json['textSelectionMatchCount'],
        'textSelectionMatchIndex': json['textSelectionMatchIndex'] == null ? undefined : json['textSelectionMatchIndex'],
    };
}

export function CreateInlineCommentModelInlineCommentPropertiesToJSON(json: any): CreateInlineCommentModelInlineCommentProperties {
    return CreateInlineCommentModelInlineCommentPropertiesToJSONTyped(json, false);
}

export function CreateInlineCommentModelInlineCommentPropertiesToJSONTyped(value?: CreateInlineCommentModelInlineCommentProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'textSelection': value['textSelection'],
        'textSelectionMatchCount': value['textSelectionMatchCount'],
        'textSelectionMatchIndex': value['textSelectionMatchIndex'],
    };
}

