/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateBlogPostRequestBody } from './CreateBlogPostRequestBody';
import {
    CreateBlogPostRequestBodyFromJSON,
    CreateBlogPostRequestBodyFromJSONTyped,
    CreateBlogPostRequestBodyToJSON,
    CreateBlogPostRequestBodyToJSONTyped,
} from './CreateBlogPostRequestBody';

/**
 * 
 * @export
 * @interface CreateBlogPostRequest
 */
export interface CreateBlogPostRequest {
    /**
     * ID of the space
     * @type {string}
     * @memberof CreateBlogPostRequest
     */
    spaceId: string;
    /**
     * The status of the blog post, specifies if the blog post will be created as a new blog post or a draft
     * @type {string}
     * @memberof CreateBlogPostRequest
     */
    status?: CreateBlogPostRequestStatusEnum;
    /**
     * Title of the blog post, required if creating non-draft.
     * @type {string}
     * @memberof CreateBlogPostRequest
     */
    title?: string;
    /**
     * 
     * @type {CreateBlogPostRequestBody}
     * @memberof CreateBlogPostRequest
     */
    body?: CreateBlogPostRequestBody;
    /**
     * Created date of the blog post in the format of "yyyy-MM-ddTHH:mm:ss.SSSZ".
     * @type {string}
     * @memberof CreateBlogPostRequest
     */
    createdAt?: string;
}


/**
 * @export
 */
export const CreateBlogPostRequestStatusEnum = {
    Current: 'current',
    Draft: 'draft'
} as const;
export type CreateBlogPostRequestStatusEnum = typeof CreateBlogPostRequestStatusEnum[keyof typeof CreateBlogPostRequestStatusEnum];


/**
 * Check if a given object implements the CreateBlogPostRequest interface.
 */
export function instanceOfCreateBlogPostRequest(value: object): value is CreateBlogPostRequest {
    if (!('spaceId' in value) || value['spaceId'] === undefined) return false;
    return true;
}

export function CreateBlogPostRequestFromJSON(json: any): CreateBlogPostRequest {
    return CreateBlogPostRequestFromJSONTyped(json, false);
}

export function CreateBlogPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBlogPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'spaceId': json['spaceId'],
        'status': json['status'] == null ? undefined : json['status'],
        'title': json['title'] == null ? undefined : json['title'],
        'body': json['body'] == null ? undefined : CreateBlogPostRequestBodyFromJSON(json['body']),
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function CreateBlogPostRequestToJSON(json: any): CreateBlogPostRequest {
    return CreateBlogPostRequestToJSONTyped(json, false);
}

export function CreateBlogPostRequestToJSONTyped(value?: CreateBlogPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'spaceId': value['spaceId'],
        'status': value['status'],
        'title': value['title'],
        'body': CreateBlogPostRequestBodyToJSON(value['body']),
        'createdAt': value['createdAt'],
    };
}

