/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlogPostBodyWrite } from './BlogPostBodyWrite';
import {
    instanceOfBlogPostBodyWrite,
    BlogPostBodyWriteFromJSON,
    BlogPostBodyWriteFromJSONTyped,
    BlogPostBodyWriteToJSON,
} from './BlogPostBodyWrite';
import type { BlogPostNestedBodyWrite } from './BlogPostNestedBodyWrite';
import {
    instanceOfBlogPostNestedBodyWrite,
    BlogPostNestedBodyWriteFromJSON,
    BlogPostNestedBodyWriteFromJSONTyped,
    BlogPostNestedBodyWriteToJSON,
} from './BlogPostNestedBodyWrite';

/**
 * @type CreateBlogPostRequestBody
 * 
 * @export
 */
export type CreateBlogPostRequestBody = BlogPostBodyWrite | BlogPostNestedBodyWrite;

export function CreateBlogPostRequestBodyFromJSON(json: any): CreateBlogPostRequestBody {
    return CreateBlogPostRequestBodyFromJSONTyped(json, false);
}

export function CreateBlogPostRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBlogPostRequestBody {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfBlogPostBodyWrite(json)) {
        return BlogPostBodyWriteFromJSONTyped(json, true);
    }
    if (instanceOfBlogPostNestedBodyWrite(json)) {
        return BlogPostNestedBodyWriteFromJSONTyped(json, true);
    }
    return {} as any;
}

export function CreateBlogPostRequestBodyToJSON(json: any): any {
    return CreateBlogPostRequestBodyToJSONTyped(json, false);
}

export function CreateBlogPostRequestBodyToJSONTyped(value?: CreateBlogPostRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfBlogPostBodyWrite(value)) {
        return BlogPostBodyWriteToJSON(value as BlogPostBodyWrite);
    }
    if (instanceOfBlogPostNestedBodyWrite(value)) {
        return BlogPostNestedBodyWriteToJSON(value as BlogPostNestedBodyWrite);
    }
    return {};
}

