/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBulkUserLookupRequest
 */
export interface CreateBulkUserLookupRequest {
    /**
     * List of accountIds to retrieve user info for.
     * @type {Array<string>}
     * @memberof CreateBulkUserLookupRequest
     */
    accountIds: Array<string>;
}

/**
 * Check if a given object implements the CreateBulkUserLookupRequest interface.
 */
export function instanceOfCreateBulkUserLookupRequest(value: object): value is CreateBulkUserLookupRequest {
    if (!('accountIds' in value) || value['accountIds'] === undefined) return false;
    return true;
}

export function CreateBulkUserLookupRequestFromJSON(json: any): CreateBulkUserLookupRequest {
    return CreateBulkUserLookupRequestFromJSONTyped(json, false);
}

export function CreateBulkUserLookupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBulkUserLookupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountIds': json['accountIds'],
    };
}

export function CreateBulkUserLookupRequestToJSON(json: any): CreateBulkUserLookupRequest {
    return CreateBulkUserLookupRequestToJSONTyped(json, false);
}

export function CreateBulkUserLookupRequestToJSONTyped(value?: CreateBulkUserLookupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountIds': value['accountIds'],
    };
}

