/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CommentBodyWrite } from './CommentBodyWrite';
import {
    instanceOfCommentBodyWrite,
    CommentBodyWriteFromJSON,
    CommentBodyWriteFromJSONTyped,
    CommentBodyWriteToJSON,
} from './CommentBodyWrite';
import type { CommentNestedBodyWrite } from './CommentNestedBodyWrite';
import {
    instanceOfCommentNestedBodyWrite,
    CommentNestedBodyWriteFromJSON,
    CommentNestedBodyWriteFromJSONTyped,
    CommentNestedBodyWriteToJSON,
} from './CommentNestedBodyWrite';

/**
 * @type CreateFooterCommentModelBody
 * 
 * @export
 */
export type CreateFooterCommentModelBody = CommentBodyWrite | CommentNestedBodyWrite;

export function CreateFooterCommentModelBodyFromJSON(json: any): CreateFooterCommentModelBody {
    return CreateFooterCommentModelBodyFromJSONTyped(json, false);
}

export function CreateFooterCommentModelBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFooterCommentModelBody {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfCommentBodyWrite(json)) {
        return CommentBodyWriteFromJSONTyped(json, true);
    }
    if (instanceOfCommentNestedBodyWrite(json)) {
        return CommentNestedBodyWriteFromJSONTyped(json, true);
    }
    return {} as any;
}

export function CreateFooterCommentModelBodyToJSON(json: any): any {
    return CreateFooterCommentModelBodyToJSONTyped(json, false);
}

export function CreateFooterCommentModelBodyToJSONTyped(value?: CreateFooterCommentModelBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfCommentBodyWrite(value)) {
        return CommentBodyWriteToJSON(value as CommentBodyWrite);
    }
    if (instanceOfCommentNestedBodyWrite(value)) {
        return CommentNestedBodyWriteToJSON(value as CommentNestedBodyWrite);
    }
    return {};
}

