/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreatePageRequestBody } from './CreatePageRequestBody';
import {
    CreatePageRequestBodyFromJSON,
    CreatePageRequestBodyFromJSONTyped,
    CreatePageRequestBodyToJSON,
    CreatePageRequestBodyToJSONTyped,
} from './CreatePageRequestBody';

/**
 * 
 * @export
 * @interface CreatePageRequest
 */
export interface CreatePageRequest {
    /**
     * ID of the space.
     * @type {string}
     * @memberof CreatePageRequest
     */
    spaceId: string;
    /**
     * The status of the page, published or draft.
     * @type {string}
     * @memberof CreatePageRequest
     */
    status?: CreatePageRequestStatusEnum;
    /**
     * Title of the page, required if page status is not draft.
     * @type {string}
     * @memberof CreatePageRequest
     */
    title?: string;
    /**
     * The parent content ID of the page. If the `root-level` query parameter is set to false and a value is 
     * not supplied for this parameter, then the space homepage's ID will be used. If the `root-level` query 
     * parameter is set to true, then a value may not be supplied for this parameter.
     * @type {string}
     * @memberof CreatePageRequest
     */
    parentId?: string;
    /**
     * 
     * @type {CreatePageRequestBody}
     * @memberof CreatePageRequest
     */
    body?: CreatePageRequestBody;
    /**
     * The subtype of the page. Provide the subtype live to create a live doc or no subtype to create a page.
     * @type {string}
     * @memberof CreatePageRequest
     */
    subtype?: CreatePageRequestSubtypeEnum;
}


/**
 * @export
 */
export const CreatePageRequestStatusEnum = {
    Current: 'current',
    Draft: 'draft'
} as const;
export type CreatePageRequestStatusEnum = typeof CreatePageRequestStatusEnum[keyof typeof CreatePageRequestStatusEnum];

/**
 * @export
 */
export const CreatePageRequestSubtypeEnum = {
    Live: 'live'
} as const;
export type CreatePageRequestSubtypeEnum = typeof CreatePageRequestSubtypeEnum[keyof typeof CreatePageRequestSubtypeEnum];


/**
 * Check if a given object implements the CreatePageRequest interface.
 */
export function instanceOfCreatePageRequest(value: object): value is CreatePageRequest {
    if (!('spaceId' in value) || value['spaceId'] === undefined) return false;
    return true;
}

export function CreatePageRequestFromJSON(json: any): CreatePageRequest {
    return CreatePageRequestFromJSONTyped(json, false);
}

export function CreatePageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'spaceId': json['spaceId'],
        'status': json['status'] == null ? undefined : json['status'],
        'title': json['title'] == null ? undefined : json['title'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'body': json['body'] == null ? undefined : CreatePageRequestBodyFromJSON(json['body']),
        'subtype': json['subtype'] == null ? undefined : json['subtype'],
    };
}

export function CreatePageRequestToJSON(json: any): CreatePageRequest {
    return CreatePageRequestToJSONTyped(json, false);
}

export function CreatePageRequestToJSONTyped(value?: CreatePageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'spaceId': value['spaceId'],
        'status': value['status'],
        'title': value['title'],
        'parentId': value['parentId'],
        'body': CreatePageRequestBodyToJSON(value['body']),
        'subtype': value['subtype'],
    };
}

