/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWhiteboardRequest
 */
export interface CreateWhiteboardRequest {
    /**
     * ID of the space.
     * @type {string}
     * @memberof CreateWhiteboardRequest
     */
    spaceId: string;
    /**
     * Title of the whiteboard.
     * @type {string}
     * @memberof CreateWhiteboardRequest
     */
    title?: string;
    /**
     * The parent content ID of the whiteboard.
     * @type {string}
     * @memberof CreateWhiteboardRequest
     */
    parentId?: string;
    /**
     * Providing a template key will add that template to the new whiteboard.
     * @type {string}
     * @memberof CreateWhiteboardRequest
     */
    templateKey?: CreateWhiteboardRequestTemplateKeyEnum;
    /**
     * If templateKey is provided, locale will decide which language the template will be created with. If locale is omitted, the user's locale will be used.
     * @type {string}
     * @memberof CreateWhiteboardRequest
     */
    locale?: CreateWhiteboardRequestLocaleEnum;
}


/**
 * @export
 */
export const CreateWhiteboardRequestTemplateKeyEnum = {
    _2x2Prioritization: '2x2-prioritization',
    _4lsRetro: '4ls-retro',
    AnnualCalendar: 'annual-calendar',
    Brainwriting: 'brainwriting',
    ConceptMap: 'concept-map',
    Crazy8s: 'crazy-8s',
    DailySync: 'daily-sync',
    DisruptiveBrainstorm: 'disruptive-brainstorm',
    DotVoting: 'dot-voting',
    ElevatorPitch: 'elevator-pitch',
    FlowChart: 'flow-chart',
    GapAnalysis: 'gap-analysis',
    IceBreakers: 'ice-breakers',
    IncidentPostmortem: 'incident-postmortem',
    JourneyMappingKit: 'journey-mapping-kit',
    KanbanBoard: 'kanban-board',
    LeanCoffee: 'lean-coffee',
    NetworkOfTeams: 'network-of-teams',
    OrgChart: 'org-chart',
    PiPlanning: 'pi-planning',
    Prioritization: 'prioritization',
    PrioritizationExperiment: 'prioritization-experiment',
    ProductRoadmap: 'product-roadmap',
    ProductVisionBoard: 'product-vision-board',
    Rice: 'rice',
    SailboatRetro: 'sailboat-retro',
    ServiceBlueprint: 'service-blueprint',
    SimpleRetrospective: 'simple-retrospective',
    SprintPlanning: 'sprint-planning',
    StickyNotePack: 'sticky-note-pack',
    Swimlanes: 'swimlanes',
    TeamFormationGuide: 'team-formation-guide',
    Timeline: 'timeline',
    TimelineWorkflow: 'timeline-workflow',
    UserStoryMap: 'user-story-map',
    Workflow: 'workflow',
    VisionBoard: 'vision-board',
    VennDiagram: 'venn-diagram',
    Storyboard: 'storyboard',
    ActionPlan: 'action-plan',
    RootCauseAnalysis: 'root-cause-analysis',
    ExecutiveSummary: 'executive-summary',
    StakeholderMapping: 'stakeholder-mapping',
    AnnualCalendar20252026: 'annual-calendar-2025-2026',
    HealthMonitor: 'health-monitor',
    OkrPlanning: 'okr-planning',
    SwotAnalysis: 'swot-analysis',
    PokerPlanning: 'poker-planning',
    FishboneDiagram: 'fishbone-diagram',
    RiskAssessment: 'risk-assessment',
    BoundedContext: 'bounded-context',
    HopesAndFears: 'hopes-and-fears',
    SwimlaneVertical: 'swimlane-vertical'
} as const;
export type CreateWhiteboardRequestTemplateKeyEnum = typeof CreateWhiteboardRequestTemplateKeyEnum[keyof typeof CreateWhiteboardRequestTemplateKeyEnum];

/**
 * @export
 */
export const CreateWhiteboardRequestLocaleEnum = {
    DeDe: 'de-DE',
    CsCz: 'cs-CZ',
    KoKr: 'ko-KR',
    FrFr: 'fr-FR',
    ItIt: 'it-IT',
    JaJp: 'ja-JP',
    NlNl: 'nl-NL',
    NbNo: 'nb-NO',
    DaDk: 'da-DK',
    SvSe: 'sv-SE',
    FiFi: 'fi-FI',
    RuRu: 'ru-RU',
    PlPl: 'pl-PL',
    TrTr: 'tr-TR',
    HuHu: 'hu-HU',
    EnGb: 'en-GB',
    EnUs: 'en-US',
    PtBr: 'pt-BR',
    ZhCn: 'zh-CN',
    ZhTw: 'zh-TW',
    EsEs: 'es-ES'
} as const;
export type CreateWhiteboardRequestLocaleEnum = typeof CreateWhiteboardRequestLocaleEnum[keyof typeof CreateWhiteboardRequestLocaleEnum];


/**
 * Check if a given object implements the CreateWhiteboardRequest interface.
 */
export function instanceOfCreateWhiteboardRequest(value: object): value is CreateWhiteboardRequest {
    if (!('spaceId' in value) || value['spaceId'] === undefined) return false;
    return true;
}

export function CreateWhiteboardRequestFromJSON(json: any): CreateWhiteboardRequest {
    return CreateWhiteboardRequestFromJSONTyped(json, false);
}

export function CreateWhiteboardRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWhiteboardRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'spaceId': json['spaceId'],
        'title': json['title'] == null ? undefined : json['title'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'templateKey': json['templateKey'] == null ? undefined : json['templateKey'],
        'locale': json['locale'] == null ? undefined : json['locale'],
    };
}

export function CreateWhiteboardRequestToJSON(json: any): CreateWhiteboardRequest {
    return CreateWhiteboardRequestToJSONTyped(json, false);
}

export function CreateWhiteboardRequestToJSONTyped(value?: CreateWhiteboardRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'spaceId': value['spaceId'],
        'title': value['title'],
        'parentId': value['parentId'],
        'templateKey': value['templateKey'],
        'locale': value['locale'],
    };
}

