/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Version } from './Version';
import {
    VersionFromJSON,
    VersionFromJSONTyped,
    VersionToJSON,
    VersionToJSONTyped,
} from './Version';
import type { GetAttachmentById200ResponseAllOfLinks } from './GetAttachmentById200ResponseAllOfLinks';
import {
    GetAttachmentById200ResponseAllOfLinksFromJSON,
    GetAttachmentById200ResponseAllOfLinksFromJSONTyped,
    GetAttachmentById200ResponseAllOfLinksToJSON,
    GetAttachmentById200ResponseAllOfLinksToJSONTyped,
} from './GetAttachmentById200ResponseAllOfLinks';
import type { ParentContentType } from './ParentContentType';
import {
    ParentContentTypeFromJSON,
    ParentContentTypeFromJSONTyped,
    ParentContentTypeToJSON,
    ParentContentTypeToJSONTyped,
} from './ParentContentType';
import type { ContentStatus } from './ContentStatus';
import {
    ContentStatusFromJSON,
    ContentStatusFromJSONTyped,
    ContentStatusToJSON,
    ContentStatusToJSONTyped,
} from './ContentStatus';

/**
 * 
 * @export
 * @interface CreateDatabase200Response
 */
export interface CreateDatabase200Response {
    /**
     * ID of the database.
     * @type {string}
     * @memberof CreateDatabase200Response
     */
    id?: string;
    /**
     * The content type of the object.
     * @type {string}
     * @memberof CreateDatabase200Response
     */
    type?: string;
    /**
     * 
     * @type {ContentStatus}
     * @memberof CreateDatabase200Response
     */
    status?: ContentStatus;
    /**
     * Title of the database.
     * @type {string}
     * @memberof CreateDatabase200Response
     */
    title?: string;
    /**
     * ID of the parent content, or null if there is no parent content.
     * @type {string}
     * @memberof CreateDatabase200Response
     */
    parentId?: string;
    /**
     * 
     * @type {ParentContentType}
     * @memberof CreateDatabase200Response
     */
    parentType?: ParentContentType;
    /**
     * Position of the database within the given parent page tree.
     * @type {number}
     * @memberof CreateDatabase200Response
     */
    position?: number | null;
    /**
     * The account ID of the user who created this database originally.
     * @type {string}
     * @memberof CreateDatabase200Response
     */
    authorId?: string;
    /**
     * The account ID of the user who owns this database.
     * @type {string}
     * @memberof CreateDatabase200Response
     */
    ownerId?: string;
    /**
     * Date and time when the database was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ".
     * @type {Date}
     * @memberof CreateDatabase200Response
     */
    createdAt?: Date;
    /**
     * ID of the space the database is in.
     * @type {string}
     * @memberof CreateDatabase200Response
     */
    spaceId?: string;
    /**
     * 
     * @type {Version}
     * @memberof CreateDatabase200Response
     */
    version?: Version;
    /**
     * 
     * @type {GetAttachmentById200ResponseAllOfLinks}
     * @memberof CreateDatabase200Response
     */
    links?: GetAttachmentById200ResponseAllOfLinks;
}



/**
 * Check if a given object implements the CreateDatabase200Response interface.
 */
export function instanceOfCreateDatabase200Response(value: object): value is CreateDatabase200Response {
    return true;
}

export function CreateDatabase200ResponseFromJSON(json: any): CreateDatabase200Response {
    return CreateDatabase200ResponseFromJSONTyped(json, false);
}

export function CreateDatabase200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDatabase200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'status': json['status'] == null ? undefined : ContentStatusFromJSON(json['status']),
        'title': json['title'] == null ? undefined : json['title'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'parentType': json['parentType'] == null ? undefined : ParentContentTypeFromJSON(json['parentType']),
        'position': json['position'] == null ? undefined : json['position'],
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'spaceId': json['spaceId'] == null ? undefined : json['spaceId'],
        'version': json['version'] == null ? undefined : VersionFromJSON(json['version']),
        'links': json['_links'] == null ? undefined : GetAttachmentById200ResponseAllOfLinksFromJSON(json['_links']),
    };
}

export function CreateDatabase200ResponseToJSON(json: any): CreateDatabase200Response {
    return CreateDatabase200ResponseToJSONTyped(json, false);
}

export function CreateDatabase200ResponseToJSONTyped(value?: CreateDatabase200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'status': ContentStatusToJSON(value['status']),
        'title': value['title'],
        'parentId': value['parentId'],
        'parentType': ParentContentTypeToJSON(value['parentType']),
        'position': value['position'],
        'authorId': value['authorId'],
        'ownerId': value['ownerId'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'spaceId': value['spaceId'],
        'version': VersionToJSON(value['version']),
        '_links': GetAttachmentById200ResponseAllOfLinksToJSON(value['links']),
    };
}

