/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomContentBodyWrite
 */
export interface CustomContentBodyWrite {
    /**
     * Type of content representation used for the value field.
     * @type {string}
     * @memberof CustomContentBodyWrite
     */
    representation?: CustomContentBodyWriteRepresentationEnum;
    /**
     * Body of the custom content, in the format found in the representation field.
     * @type {string}
     * @memberof CustomContentBodyWrite
     */
    value?: string;
}


/**
 * @export
 */
export const CustomContentBodyWriteRepresentationEnum = {
    Storage: 'storage',
    AtlasDocFormat: 'atlas_doc_format',
    Raw: 'raw'
} as const;
export type CustomContentBodyWriteRepresentationEnum = typeof CustomContentBodyWriteRepresentationEnum[keyof typeof CustomContentBodyWriteRepresentationEnum];


/**
 * Check if a given object implements the CustomContentBodyWrite interface.
 */
export function instanceOfCustomContentBodyWrite(value: object): value is CustomContentBodyWrite {
    return true;
}

export function CustomContentBodyWriteFromJSON(json: any): CustomContentBodyWrite {
    return CustomContentBodyWriteFromJSONTyped(json, false);
}

export function CustomContentBodyWriteFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomContentBodyWrite {
    if (json == null) {
        return json;
    }
    return {
        
        'representation': json['representation'] == null ? undefined : json['representation'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function CustomContentBodyWriteToJSON(json: any): CustomContentBodyWrite {
    return CustomContentBodyWriteToJSONTyped(json, false);
}

export function CustomContentBodyWriteToJSONTyped(value?: CustomContentBodyWrite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'representation': value['representation'],
        'value': value['value'],
    };
}

