/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Version } from './Version';
import {
    VersionFromJSON,
    VersionFromJSONTyped,
    VersionToJSON,
    VersionToJSONTyped,
} from './Version';
import type { CustomContentLinks } from './CustomContentLinks';
import {
    CustomContentLinksFromJSON,
    CustomContentLinksFromJSONTyped,
    CustomContentLinksToJSON,
    CustomContentLinksToJSONTyped,
} from './CustomContentLinks';
import type { ContentStatus } from './ContentStatus';
import {
    ContentStatusFromJSON,
    ContentStatusFromJSONTyped,
    ContentStatusToJSON,
    ContentStatusToJSONTyped,
} from './ContentStatus';
import type { CustomContentBodyBulk } from './CustomContentBodyBulk';
import {
    CustomContentBodyBulkFromJSON,
    CustomContentBodyBulkFromJSONTyped,
    CustomContentBodyBulkToJSON,
    CustomContentBodyBulkToJSONTyped,
} from './CustomContentBodyBulk';

/**
 * 
 * @export
 * @interface CustomContentBulk
 */
export interface CustomContentBulk {
    /**
     * ID of the custom content.
     * @type {string}
     * @memberof CustomContentBulk
     */
    id?: string;
    /**
     * The type of custom content.
     * @type {string}
     * @memberof CustomContentBulk
     */
    type?: string;
    /**
     * 
     * @type {ContentStatus}
     * @memberof CustomContentBulk
     */
    status?: ContentStatus;
    /**
     * Title of the custom content.
     * @type {string}
     * @memberof CustomContentBulk
     */
    title?: string;
    /**
     * ID of the space the custom content is in.
     * 
     * Note: This is always returned, regardless of if the custom content has a container that is a space.
     * @type {string}
     * @memberof CustomContentBulk
     */
    spaceId?: string;
    /**
     * ID of the containing page.
     * 
     * Note: This is only returned if the custom content has a container that is a page.
     * @type {string}
     * @memberof CustomContentBulk
     */
    pageId?: string;
    /**
     * ID of the containing blog post.
     * 
     * Note: This is only returned if the custom content has a container that is a blog post.
     * @type {string}
     * @memberof CustomContentBulk
     */
    blogPostId?: string;
    /**
     * ID of the containing custom content.
     * 
     * Note: This is only returned if the custom content has a container that is custom content.
     * @type {string}
     * @memberof CustomContentBulk
     */
    customContentId?: string;
    /**
     * The account ID of the user who created this custom content originally.
     * @type {string}
     * @memberof CustomContentBulk
     */
    authorId?: string;
    /**
     * Date and time when the custom content was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ".
     * @type {Date}
     * @memberof CustomContentBulk
     */
    createdAt?: Date;
    /**
     * 
     * @type {Version}
     * @memberof CustomContentBulk
     */
    version?: Version;
    /**
     * 
     * @type {CustomContentBodyBulk}
     * @memberof CustomContentBulk
     */
    body?: CustomContentBodyBulk;
    /**
     * 
     * @type {CustomContentLinks}
     * @memberof CustomContentBulk
     */
    links?: CustomContentLinks;
}



/**
 * Check if a given object implements the CustomContentBulk interface.
 */
export function instanceOfCustomContentBulk(value: object): value is CustomContentBulk {
    return true;
}

export function CustomContentBulkFromJSON(json: any): CustomContentBulk {
    return CustomContentBulkFromJSONTyped(json, false);
}

export function CustomContentBulkFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomContentBulk {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'status': json['status'] == null ? undefined : ContentStatusFromJSON(json['status']),
        'title': json['title'] == null ? undefined : json['title'],
        'spaceId': json['spaceId'] == null ? undefined : json['spaceId'],
        'pageId': json['pageId'] == null ? undefined : json['pageId'],
        'blogPostId': json['blogPostId'] == null ? undefined : json['blogPostId'],
        'customContentId': json['customContentId'] == null ? undefined : json['customContentId'],
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'version': json['version'] == null ? undefined : VersionFromJSON(json['version']),
        'body': json['body'] == null ? undefined : CustomContentBodyBulkFromJSON(json['body']),
        'links': json['_links'] == null ? undefined : CustomContentLinksFromJSON(json['_links']),
    };
}

export function CustomContentBulkToJSON(json: any): CustomContentBulk {
    return CustomContentBulkToJSONTyped(json, false);
}

export function CustomContentBulkToJSONTyped(value?: CustomContentBulk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'status': ContentStatusToJSON(value['status']),
        'title': value['title'],
        'spaceId': value['spaceId'],
        'pageId': value['pageId'],
        'blogPostId': value['blogPostId'],
        'customContentId': value['customContentId'],
        'authorId': value['authorId'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'version': VersionToJSON(value['version']),
        'body': CustomContentBodyBulkToJSON(value['body']),
        '_links': CustomContentLinksToJSON(value['links']),
    };
}

