/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BodyType } from './BodyType';
import {
    BodyTypeFromJSON,
    BodyTypeFromJSONTyped,
    BodyTypeToJSON,
    BodyTypeToJSONTyped,
} from './BodyType';

/**
 * Contains fields for each representation type requested.
 * @export
 * @interface CustomContentBodyBulk
 */
export interface CustomContentBodyBulk {
    /**
     * 
     * @type {BodyType}
     * @memberof CustomContentBodyBulk
     */
    raw?: BodyType;
    /**
     * 
     * @type {BodyType}
     * @memberof CustomContentBodyBulk
     */
    storage?: BodyType;
    /**
     * 
     * @type {BodyType}
     * @memberof CustomContentBodyBulk
     */
    atlasDocFormat?: BodyType;
}

/**
 * Check if a given object implements the CustomContentBodyBulk interface.
 */
export function instanceOfCustomContentBodyBulk(value: object): value is CustomContentBodyBulk {
    return true;
}

export function CustomContentBodyBulkFromJSON(json: any): CustomContentBodyBulk {
    return CustomContentBodyBulkFromJSONTyped(json, false);
}

export function CustomContentBodyBulkFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomContentBodyBulk {
    if (json == null) {
        return json;
    }
    return {
        
        'raw': json['raw'] == null ? undefined : BodyTypeFromJSON(json['raw']),
        'storage': json['storage'] == null ? undefined : BodyTypeFromJSON(json['storage']),
        'atlasDocFormat': json['atlas_doc_format'] == null ? undefined : BodyTypeFromJSON(json['atlas_doc_format']),
    };
}

export function CustomContentBodyBulkToJSON(json: any): CustomContentBodyBulk {
    return CustomContentBodyBulkToJSONTyped(json, false);
}

export function CustomContentBodyBulkToJSONTyped(value?: CustomContentBodyBulk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'raw': BodyTypeToJSON(value['raw']),
        'storage': BodyTypeToJSON(value['storage']),
        'atlas_doc_format': BodyTypeToJSON(value['atlasDocFormat']),
    };
}

