/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomContentBodyWrite } from './CustomContentBodyWrite';
import {
    CustomContentBodyWriteFromJSON,
    CustomContentBodyWriteFromJSONTyped,
    CustomContentBodyWriteToJSON,
    CustomContentBodyWriteToJSONTyped,
} from './CustomContentBodyWrite';

/**
 * Body of the custom content. Only one body format should be specified as the property
 * for this object, e.g. `storage`.
 * @export
 * @interface CustomContentNestedBodyWrite
 */
export interface CustomContentNestedBodyWrite {
    /**
     * 
     * @type {CustomContentBodyWrite}
     * @memberof CustomContentNestedBodyWrite
     */
    storage?: CustomContentBodyWrite;
    /**
     * 
     * @type {CustomContentBodyWrite}
     * @memberof CustomContentNestedBodyWrite
     */
    atlasDocFormat?: CustomContentBodyWrite;
    /**
     * 
     * @type {CustomContentBodyWrite}
     * @memberof CustomContentNestedBodyWrite
     */
    raw?: CustomContentBodyWrite;
}

/**
 * Check if a given object implements the CustomContentNestedBodyWrite interface.
 */
export function instanceOfCustomContentNestedBodyWrite(value: object): value is CustomContentNestedBodyWrite {
    return true;
}

export function CustomContentNestedBodyWriteFromJSON(json: any): CustomContentNestedBodyWrite {
    return CustomContentNestedBodyWriteFromJSONTyped(json, false);
}

export function CustomContentNestedBodyWriteFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomContentNestedBodyWrite {
    if (json == null) {
        return json;
    }
    return {
        
        'storage': json['storage'] == null ? undefined : CustomContentBodyWriteFromJSON(json['storage']),
        'atlasDocFormat': json['atlas_doc_format'] == null ? undefined : CustomContentBodyWriteFromJSON(json['atlas_doc_format']),
        'raw': json['raw'] == null ? undefined : CustomContentBodyWriteFromJSON(json['raw']),
    };
}

export function CustomContentNestedBodyWriteToJSON(json: any): CustomContentNestedBodyWrite {
    return CustomContentNestedBodyWriteToJSONTyped(json, false);
}

export function CustomContentNestedBodyWriteToJSONTyped(value?: CustomContentNestedBodyWrite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'storage': CustomContentBodyWriteToJSON(value['storage']),
        'atlas_doc_format': CustomContentBodyWriteToJSON(value['atlasDocFormat']),
        'raw': CustomContentBodyWriteToJSON(value['raw']),
    };
}

