/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Version } from './Version';
import {
    VersionFromJSON,
    VersionFromJSONTyped,
    VersionToJSON,
    VersionToJSONTyped,
} from './Version';
import type { BodySingle } from './BodySingle';
import {
    BodySingleFromJSON,
    BodySingleFromJSONTyped,
    BodySingleToJSON,
    BodySingleToJSONTyped,
} from './BodySingle';
import type { CommentLinks } from './CommentLinks';
import {
    CommentLinksFromJSON,
    CommentLinksFromJSONTyped,
    CommentLinksToJSON,
    CommentLinksToJSONTyped,
} from './CommentLinks';
import type { ContentStatus } from './ContentStatus';
import {
    ContentStatusFromJSON,
    ContentStatusFromJSONTyped,
    ContentStatusToJSON,
    ContentStatusToJSONTyped,
} from './ContentStatus';

/**
 * 
 * @export
 * @interface CustomContentCommentModel
 */
export interface CustomContentCommentModel {
    /**
     * ID of the comment.
     * @type {string}
     * @memberof CustomContentCommentModel
     */
    id?: string;
    /**
     * 
     * @type {ContentStatus}
     * @memberof CustomContentCommentModel
     */
    status?: ContentStatus;
    /**
     * Title of the comment.
     * @type {string}
     * @memberof CustomContentCommentModel
     */
    title?: string;
    /**
     * ID of the custom content containing the comment.
     * @type {string}
     * @memberof CustomContentCommentModel
     */
    customContentId?: string;
    /**
     * 
     * @type {Version}
     * @memberof CustomContentCommentModel
     */
    version?: Version;
    /**
     * 
     * @type {BodySingle}
     * @memberof CustomContentCommentModel
     */
    body?: BodySingle;
    /**
     * 
     * @type {CommentLinks}
     * @memberof CustomContentCommentModel
     */
    links?: CommentLinks;
}



/**
 * Check if a given object implements the CustomContentCommentModel interface.
 */
export function instanceOfCustomContentCommentModel(value: object): value is CustomContentCommentModel {
    return true;
}

export function CustomContentCommentModelFromJSON(json: any): CustomContentCommentModel {
    return CustomContentCommentModelFromJSONTyped(json, false);
}

export function CustomContentCommentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomContentCommentModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : ContentStatusFromJSON(json['status']),
        'title': json['title'] == null ? undefined : json['title'],
        'customContentId': json['customContentId'] == null ? undefined : json['customContentId'],
        'version': json['version'] == null ? undefined : VersionFromJSON(json['version']),
        'body': json['body'] == null ? undefined : BodySingleFromJSON(json['body']),
        'links': json['_links'] == null ? undefined : CommentLinksFromJSON(json['_links']),
    };
}

export function CustomContentCommentModelToJSON(json: any): CustomContentCommentModel {
    return CustomContentCommentModelToJSONTyped(json, false);
}

export function CustomContentCommentModelToJSONTyped(value?: CustomContentCommentModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': ContentStatusToJSON(value['status']),
        'title': value['title'],
        'customContentId': value['customContentId'],
        'version': VersionToJSON(value['version']),
        'body': BodySingleToJSON(value['body']),
        '_links': CommentLinksToJSON(value['links']),
    };
}

