/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The formats a custom content body can be represented as. A subset of BodyRepresentation.
 * @export
 */
export const CustomContentBodyRepresentation = {
    Raw: 'raw',
    Storage: 'storage',
    AtlasDocFormat: 'atlas_doc_format'
} as const;
export type CustomContentBodyRepresentation = typeof CustomContentBodyRepresentation[keyof typeof CustomContentBodyRepresentation];


export function instanceOfCustomContentBodyRepresentation(value: any): boolean {
    for (const key in CustomContentBodyRepresentation) {
        if (Object.prototype.hasOwnProperty.call(CustomContentBodyRepresentation, key)) {
            if (CustomContentBodyRepresentation[key as keyof typeof CustomContentBodyRepresentation] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CustomContentBodyRepresentationFromJSON(json: any): CustomContentBodyRepresentation {
    return CustomContentBodyRepresentationFromJSONTyped(json, false);
}

export function CustomContentBodyRepresentationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomContentBodyRepresentation {
    return json as CustomContentBodyRepresentation;
}

export function CustomContentBodyRepresentationToJSON(value?: CustomContentBodyRepresentation | null): any {
    return value as any;
}

export function CustomContentBodyRepresentationToJSONTyped(value: any, ignoreDiscriminator: boolean): CustomContentBodyRepresentation {
    return value as CustomContentBodyRepresentation;
}

