/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataPolicySpaceDataPolicy
 */
export interface DataPolicySpaceDataPolicy {
    /**
     * Whether the space contains any content blocked for (inaccessible to) the requesting client application.
     * @type {boolean}
     * @memberof DataPolicySpaceDataPolicy
     */
    readonly anyContentBlocked?: boolean;
}

/**
 * Check if a given object implements the DataPolicySpaceDataPolicy interface.
 */
export function instanceOfDataPolicySpaceDataPolicy(value: object): value is DataPolicySpaceDataPolicy {
    return true;
}

export function DataPolicySpaceDataPolicyFromJSON(json: any): DataPolicySpaceDataPolicy {
    return DataPolicySpaceDataPolicyFromJSONTyped(json, false);
}

export function DataPolicySpaceDataPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataPolicySpaceDataPolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'anyContentBlocked': json['anyContentBlocked'] == null ? undefined : json['anyContentBlocked'],
    };
}

export function DataPolicySpaceDataPolicyToJSON(json: any): DataPolicySpaceDataPolicy {
    return DataPolicySpaceDataPolicyToJSONTyped(json, false);
}

export function DataPolicySpaceDataPolicyToJSONTyped(value?: Omit<DataPolicySpaceDataPolicy, 'anyContentBlocked'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

