/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpaceDescription } from './SpaceDescription';
import {
    SpaceDescriptionFromJSON,
    SpaceDescriptionFromJSONTyped,
    SpaceDescriptionToJSON,
    SpaceDescriptionToJSONTyped,
} from './SpaceDescription';
import type { SpaceLinks } from './SpaceLinks';
import {
    SpaceLinksFromJSON,
    SpaceLinksFromJSONTyped,
    SpaceLinksToJSON,
    SpaceLinksToJSONTyped,
} from './SpaceLinks';
import type { SpaceIcon } from './SpaceIcon';
import {
    SpaceIconFromJSON,
    SpaceIconFromJSONTyped,
    SpaceIconToJSON,
    SpaceIconToJSONTyped,
} from './SpaceIcon';
import type { DataPolicySpaceDataPolicy } from './DataPolicySpaceDataPolicy';
import {
    DataPolicySpaceDataPolicyFromJSON,
    DataPolicySpaceDataPolicyFromJSONTyped,
    DataPolicySpaceDataPolicyToJSON,
    DataPolicySpaceDataPolicyToJSONTyped,
} from './DataPolicySpaceDataPolicy';

/**
 * 
 * @export
 * @interface DataPolicySpace
 */
export interface DataPolicySpace {
    /**
     * ID of the space.
     * @type {string}
     * @memberof DataPolicySpace
     */
    id?: string;
    /**
     * Key of the space.
     * @type {string}
     * @memberof DataPolicySpace
     */
    key?: string;
    /**
     * Name of the space.
     * @type {string}
     * @memberof DataPolicySpace
     */
    name?: string;
    /**
     * 
     * @type {SpaceDescription}
     * @memberof DataPolicySpace
     */
    description?: SpaceDescription;
    /**
     * 
     * @type {DataPolicySpaceDataPolicy}
     * @memberof DataPolicySpace
     */
    dataPolicy?: DataPolicySpaceDataPolicy;
    /**
     * 
     * @type {SpaceIcon}
     * @memberof DataPolicySpace
     */
    icon?: SpaceIcon;
    /**
     * 
     * @type {SpaceLinks}
     * @memberof DataPolicySpace
     */
    links?: SpaceLinks;
}

/**
 * Check if a given object implements the DataPolicySpace interface.
 */
export function instanceOfDataPolicySpace(value: object): value is DataPolicySpace {
    return true;
}

export function DataPolicySpaceFromJSON(json: any): DataPolicySpace {
    return DataPolicySpaceFromJSONTyped(json, false);
}

export function DataPolicySpaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataPolicySpace {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : SpaceDescriptionFromJSON(json['description']),
        'dataPolicy': json['dataPolicy'] == null ? undefined : DataPolicySpaceDataPolicyFromJSON(json['dataPolicy']),
        'icon': json['icon'] == null ? undefined : SpaceIconFromJSON(json['icon']),
        'links': json['_links'] == null ? undefined : SpaceLinksFromJSON(json['_links']),
    };
}

export function DataPolicySpaceToJSON(json: any): DataPolicySpace {
    return DataPolicySpaceToJSONTyped(json, false);
}

export function DataPolicySpaceToJSONTyped(value?: DataPolicySpace | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'key': value['key'],
        'name': value['name'],
        'description': SpaceDescriptionToJSON(value['description']),
        'dataPolicy': DataPolicySpaceDataPolicyToJSON(value['dataPolicy']),
        'icon': SpaceIconToJSON(value['icon']),
        '_links': SpaceLinksToJSON(value['links']),
    };
}

