/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteSpaceRoleResponse
 */
export interface DeleteSpaceRoleResponse {
    /**
     * Id of the task to update the space permissions associated with the space role
     * @type {string}
     * @memberof DeleteSpaceRoleResponse
     */
    taskId?: string;
}

/**
 * Check if a given object implements the DeleteSpaceRoleResponse interface.
 */
export function instanceOfDeleteSpaceRoleResponse(value: object): value is DeleteSpaceRoleResponse {
    return true;
}

export function DeleteSpaceRoleResponseFromJSON(json: any): DeleteSpaceRoleResponse {
    return DeleteSpaceRoleResponseFromJSONTyped(json, false);
}

export function DeleteSpaceRoleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteSpaceRoleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
    };
}

export function DeleteSpaceRoleResponseToJSON(json: any): DeleteSpaceRoleResponse {
    return DeleteSpaceRoleResponseToJSONTyped(json, false);
}

export function DeleteSpaceRoleResponseToJSONTyped(value?: DeleteSpaceRoleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taskId': value['taskId'],
    };
}

