/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OnlyArchivedAndCurrentContentStatus } from './OnlyArchivedAndCurrentContentStatus';
import {
    OnlyArchivedAndCurrentContentStatusFromJSON,
    OnlyArchivedAndCurrentContentStatusFromJSONTyped,
    OnlyArchivedAndCurrentContentStatusToJSON,
    OnlyArchivedAndCurrentContentStatusToJSONTyped,
} from './OnlyArchivedAndCurrentContentStatus';

/**
 * 
 * @export
 * @interface DescendantsResponse
 */
export interface DescendantsResponse {
    /**
     * ID of the descendant.
     * @type {string}
     * @memberof DescendantsResponse
     */
    id?: string;
    /**
     * 
     * @type {OnlyArchivedAndCurrentContentStatus}
     * @memberof DescendantsResponse
     */
    status?: OnlyArchivedAndCurrentContentStatus;
    /**
     * Title of the descendant.
     * @type {string}
     * @memberof DescendantsResponse
     */
    title?: string;
    /**
     * Hierarchical content type (database/embed/folder/page/whiteboard).
     * @type {string}
     * @memberof DescendantsResponse
     */
    type?: string;
    /**
     * ID of the parent content.
     * @type {string}
     * @memberof DescendantsResponse
     */
    parentId?: string;
    /**
     * Depth of the descendant in the content tree relative to the content specified in the request.
     * @type {number}
     * @memberof DescendantsResponse
     */
    depth?: number;
    /**
     * Numerical value indicating position of the content relative to its siblings (with the same parentId) within the content tree.
     * If the content is sorted by childPosition, it will reflect the default content ordering within the content tree.
     * @type {number}
     * @memberof DescendantsResponse
     */
    childPosition?: number | null;
}



/**
 * Check if a given object implements the DescendantsResponse interface.
 */
export function instanceOfDescendantsResponse(value: object): value is DescendantsResponse {
    return true;
}

export function DescendantsResponseFromJSON(json: any): DescendantsResponse {
    return DescendantsResponseFromJSONTyped(json, false);
}

export function DescendantsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DescendantsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : OnlyArchivedAndCurrentContentStatusFromJSON(json['status']),
        'title': json['title'] == null ? undefined : json['title'],
        'type': json['type'] == null ? undefined : json['type'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'depth': json['depth'] == null ? undefined : json['depth'],
        'childPosition': json['childPosition'] == null ? undefined : json['childPosition'],
    };
}

export function DescendantsResponseToJSON(json: any): DescendantsResponse {
    return DescendantsResponseToJSONTyped(json, false);
}

export function DescendantsResponseToJSONTyped(value?: DescendantsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': OnlyArchivedAndCurrentContentStatusToJSON(value['status']),
        'title': value['title'],
        'type': value['type'],
        'parentId': value['parentId'],
        'depth': value['depth'],
        'childPosition': value['childPosition'],
    };
}

