/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DetailedVersion
 */
export interface DetailedVersion {
    /**
     * The current version number.
     * @type {number}
     * @memberof DetailedVersion
     */
    number?: number;
    /**
     * The account ID of the user who created this version.
     * @type {string}
     * @memberof DetailedVersion
     */
    authorId?: string;
    /**
     * Message associated with the current version.
     * @type {string}
     * @memberof DetailedVersion
     */
    message?: string;
    /**
     * Date and time when the version was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ".
     * @type {Date}
     * @memberof DetailedVersion
     */
    createdAt?: Date;
    /**
     * Describes if this version is a minor version. Email notifications and activity stream updates are not created for minor versions.
     * @type {boolean}
     * @memberof DetailedVersion
     */
    minorEdit?: boolean;
    /**
     * Describes if the content type is modified in this version (e.g. page to blog)
     * @type {boolean}
     * @memberof DetailedVersion
     */
    contentTypeModified?: boolean;
    /**
     * The account IDs of users that collaborated on this version.
     * @type {Array<string>}
     * @memberof DetailedVersion
     */
    collaborators?: Array<string>;
    /**
     * The version number of the version prior to this current content update.
     * @type {number}
     * @memberof DetailedVersion
     */
    prevVersion?: number;
    /**
     * The version number of the version after this current content update.
     * @type {number}
     * @memberof DetailedVersion
     */
    nextVersion?: number;
}

/**
 * Check if a given object implements the DetailedVersion interface.
 */
export function instanceOfDetailedVersion(value: object): value is DetailedVersion {
    return true;
}

export function DetailedVersionFromJSON(json: any): DetailedVersion {
    return DetailedVersionFromJSONTyped(json, false);
}

export function DetailedVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailedVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'number': json['number'] == null ? undefined : json['number'],
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
        'message': json['message'] == null ? undefined : json['message'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'minorEdit': json['minorEdit'] == null ? undefined : json['minorEdit'],
        'contentTypeModified': json['contentTypeModified'] == null ? undefined : json['contentTypeModified'],
        'collaborators': json['collaborators'] == null ? undefined : json['collaborators'],
        'prevVersion': json['prevVersion'] == null ? undefined : json['prevVersion'],
        'nextVersion': json['nextVersion'] == null ? undefined : json['nextVersion'],
    };
}

export function DetailedVersionToJSON(json: any): DetailedVersion {
    return DetailedVersionToJSONTyped(json, false);
}

export function DetailedVersionToJSONTyped(value?: DetailedVersion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'number': value['number'],
        'authorId': value['authorId'],
        'message': value['message'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'minorEdit': value['minorEdit'],
        'contentTypeModified': value['contentTypeModified'],
        'collaborators': value['collaborators'],
        'prevVersion': value['prevVersion'],
        'nextVersion': value['nextVersion'],
    };
}

