/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAttachmentById200ResponseAllOfLinks
 */
export interface GetAttachmentById200ResponseAllOfLinks {
    /**
     * Base url of the Confluence site.
     * @type {string}
     * @memberof GetAttachmentById200ResponseAllOfLinks
     */
    base?: string;
}

/**
 * Check if a given object implements the GetAttachmentById200ResponseAllOfLinks interface.
 */
export function instanceOfGetAttachmentById200ResponseAllOfLinks(value: object): value is GetAttachmentById200ResponseAllOfLinks {
    return true;
}

export function GetAttachmentById200ResponseAllOfLinksFromJSON(json: any): GetAttachmentById200ResponseAllOfLinks {
    return GetAttachmentById200ResponseAllOfLinksFromJSONTyped(json, false);
}

export function GetAttachmentById200ResponseAllOfLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAttachmentById200ResponseAllOfLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'base': json['base'] == null ? undefined : json['base'],
    };
}

export function GetAttachmentById200ResponseAllOfLinksToJSON(json: any): GetAttachmentById200ResponseAllOfLinks {
    return GetAttachmentById200ResponseAllOfLinksToJSONTyped(json, false);
}

export function GetAttachmentById200ResponseAllOfLinksToJSONTyped(value?: GetAttachmentById200ResponseAllOfLinks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base': value['base'],
    };
}

