/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetForgeAppProperty200Response
 */
export interface GetForgeAppProperty200Response {
    /**
     * The key of the property
     * @type {string}
     * @memberof GetForgeAppProperty200Response
     */
    key?: string;
    /**
     * The value of the property
     * @type {object}
     * @memberof GetForgeAppProperty200Response
     */
    value?: object;
}

/**
 * Check if a given object implements the GetForgeAppProperty200Response interface.
 */
export function instanceOfGetForgeAppProperty200Response(value: object): value is GetForgeAppProperty200Response {
    return true;
}

export function GetForgeAppProperty200ResponseFromJSON(json: any): GetForgeAppProperty200Response {
    return GetForgeAppProperty200ResponseFromJSONTyped(json, false);
}

export function GetForgeAppProperty200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetForgeAppProperty200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function GetForgeAppProperty200ResponseToJSON(json: any): GetForgeAppProperty200Response {
    return GetForgeAppProperty200ResponseToJSONTyped(json, false);
}

export function GetForgeAppProperty200ResponseToJSONTyped(value?: GetForgeAppProperty200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

