/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSpaceRoleMode200Response
 */
export interface GetSpaceRoleMode200Response {
    /**
     * The space role mode.
     * @type {string}
     * @memberof GetSpaceRoleMode200Response
     */
    mode?: GetSpaceRoleMode200ResponseModeEnum;
}


/**
 * @export
 */
export const GetSpaceRoleMode200ResponseModeEnum = {
    PreRoles: 'PRE_ROLES',
    RolesTransition: 'ROLES_TRANSITION',
    Roles: 'ROLES'
} as const;
export type GetSpaceRoleMode200ResponseModeEnum = typeof GetSpaceRoleMode200ResponseModeEnum[keyof typeof GetSpaceRoleMode200ResponseModeEnum];


/**
 * Check if a given object implements the GetSpaceRoleMode200Response interface.
 */
export function instanceOfGetSpaceRoleMode200Response(value: object): value is GetSpaceRoleMode200Response {
    return true;
}

export function GetSpaceRoleMode200ResponseFromJSON(json: any): GetSpaceRoleMode200Response {
    return GetSpaceRoleMode200ResponseFromJSONTyped(json, false);
}

export function GetSpaceRoleMode200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSpaceRoleMode200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'] == null ? undefined : json['mode'],
    };
}

export function GetSpaceRoleMode200ResponseToJSON(json: any): GetSpaceRoleMode200Response {
    return GetSpaceRoleMode200ResponseToJSONTyped(json, false);
}

export function GetSpaceRoleMode200ResponseToJSONTyped(value?: GetSpaceRoleMode200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
    };
}

