/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoleType } from './RoleType';
import {
    RoleTypeFromJSON,
    RoleTypeFromJSONTyped,
    RoleTypeToJSON,
    RoleTypeToJSONTyped,
} from './RoleType';
import type { GetAttachmentById200ResponseAllOfLinks } from './GetAttachmentById200ResponseAllOfLinks';
import {
    GetAttachmentById200ResponseAllOfLinksFromJSON,
    GetAttachmentById200ResponseAllOfLinksFromJSONTyped,
    GetAttachmentById200ResponseAllOfLinksToJSON,
    GetAttachmentById200ResponseAllOfLinksToJSONTyped,
} from './GetAttachmentById200ResponseAllOfLinks';

/**
 * 
 * @export
 * @interface GetSpaceRolesById200Response
 */
export interface GetSpaceRolesById200Response {
    /**
     * The identifier for the space role.
     * @type {string}
     * @memberof GetSpaceRolesById200Response
     */
    id?: string;
    /**
     * 
     * @type {RoleType}
     * @memberof GetSpaceRolesById200Response
     */
    type?: RoleType;
    /**
     * The name for the space role.
     * @type {string}
     * @memberof GetSpaceRolesById200Response
     */
    name?: string;
    /**
     * The description for the space role’s usage.
     * @type {string}
     * @memberof GetSpaceRolesById200Response
     */
    description?: string;
    /**
     * The space permissions the space role is comprised of.
     * @type {Array<string>}
     * @memberof GetSpaceRolesById200Response
     */
    spacePermissions?: Array<string>;
    /**
     * 
     * @type {GetAttachmentById200ResponseAllOfLinks}
     * @memberof GetSpaceRolesById200Response
     */
    links?: GetAttachmentById200ResponseAllOfLinks;
}



/**
 * Check if a given object implements the GetSpaceRolesById200Response interface.
 */
export function instanceOfGetSpaceRolesById200Response(value: object): value is GetSpaceRolesById200Response {
    return true;
}

export function GetSpaceRolesById200ResponseFromJSON(json: any): GetSpaceRolesById200Response {
    return GetSpaceRolesById200ResponseFromJSONTyped(json, false);
}

export function GetSpaceRolesById200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSpaceRolesById200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : RoleTypeFromJSON(json['type']),
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'spacePermissions': json['spacePermissions'] == null ? undefined : json['spacePermissions'],
        'links': json['_links'] == null ? undefined : GetAttachmentById200ResponseAllOfLinksFromJSON(json['_links']),
    };
}

export function GetSpaceRolesById200ResponseToJSON(json: any): GetSpaceRolesById200Response {
    return GetSpaceRolesById200ResponseToJSONTyped(json, false);
}

export function GetSpaceRolesById200ResponseToJSONTyped(value?: GetSpaceRolesById200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': RoleTypeToJSON(value['type']),
        'name': value['name'],
        'description': value['description'],
        'spacePermissions': value['spacePermissions'],
        '_links': GetAttachmentById200ResponseAllOfLinksToJSON(value['links']),
    };
}

