/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * This object represents an icon. If used as a profilePicture, this may be returned as null, depending on the user's privacy setting.
 * @export
 * @interface Icon
 */
export interface Icon {
    /**
     * 
     * @type {string}
     * @memberof Icon
     */
    path: string;
    /**
     * 
     * @type {boolean}
     * @memberof Icon
     */
    isDefault: boolean;
}

/**
 * Check if a given object implements the Icon interface.
 */
export function instanceOfIcon(value: object): value is Icon {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('isDefault' in value) || value['isDefault'] === undefined) return false;
    return true;
}

export function IconFromJSON(json: any): Icon {
    return IconFromJSONTyped(json, false);
}

export function IconFromJSONTyped(json: any, ignoreDiscriminator: boolean): Icon {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'isDefault': json['isDefault'],
    };
}

export function IconToJSON(json: any): Icon {
    return IconToJSONTyped(json, false);
}

export function IconToJSONTyped(value?: Icon | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'isDefault': value['isDefault'],
    };
}

