/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentProperty } from './ContentProperty';
import {
    ContentPropertyFromJSON,
    ContentPropertyFromJSONTyped,
    ContentPropertyToJSON,
    ContentPropertyToJSONTyped,
} from './ContentProperty';
import type { OptionalFieldLinks } from './OptionalFieldLinks';
import {
    OptionalFieldLinksFromJSON,
    OptionalFieldLinksFromJSONTyped,
    OptionalFieldLinksToJSON,
    OptionalFieldLinksToJSONTyped,
} from './OptionalFieldLinks';
import type { OptionalFieldMeta } from './OptionalFieldMeta';
import {
    OptionalFieldMetaFromJSON,
    OptionalFieldMetaFromJSONTyped,
    OptionalFieldMetaToJSON,
    OptionalFieldMetaToJSONTyped,
} from './OptionalFieldMeta';

/**
 * 
 * @export
 * @interface InlineCommentModelProperties
 */
export interface InlineCommentModelProperties {
    /**
     * 
     * @type {Array<ContentProperty>}
     * @memberof InlineCommentModelProperties
     */
    results?: Array<ContentProperty>;
    /**
     * 
     * @type {OptionalFieldMeta}
     * @memberof InlineCommentModelProperties
     */
    meta?: OptionalFieldMeta;
    /**
     * 
     * @type {OptionalFieldLinks}
     * @memberof InlineCommentModelProperties
     */
    links?: OptionalFieldLinks;
    /**
     * Property value used to reference the highlighted element in DOM.
     * @type {string}
     * @memberof InlineCommentModelProperties
     */
    inlineMarkerRef?: string;
    /**
     * Text that is highlighted.
     * @type {string}
     * @memberof InlineCommentModelProperties
     */
    inlineOriginalSelection?: string;
}

/**
 * Check if a given object implements the InlineCommentModelProperties interface.
 */
export function instanceOfInlineCommentModelProperties(value: object): value is InlineCommentModelProperties {
    return true;
}

export function InlineCommentModelPropertiesFromJSON(json: any): InlineCommentModelProperties {
    return InlineCommentModelPropertiesFromJSONTyped(json, false);
}

export function InlineCommentModelPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineCommentModelProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(ContentPropertyFromJSON)),
        'meta': json['meta'] == null ? undefined : OptionalFieldMetaFromJSON(json['meta']),
        'links': json['_links'] == null ? undefined : OptionalFieldLinksFromJSON(json['_links']),
        'inlineMarkerRef': json['inlineMarkerRef'] == null ? undefined : json['inlineMarkerRef'],
        'inlineOriginalSelection': json['inlineOriginalSelection'] == null ? undefined : json['inlineOriginalSelection'],
    };
}

export function InlineCommentModelPropertiesToJSON(json: any): InlineCommentModelProperties {
    return InlineCommentModelPropertiesToJSONTyped(json, false);
}

export function InlineCommentModelPropertiesToJSONTyped(value?: InlineCommentModelProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(ContentPropertyToJSON)),
        'meta': OptionalFieldMetaToJSON(value['meta']),
        '_links': OptionalFieldLinksToJSON(value['links']),
        'inlineMarkerRef': value['inlineMarkerRef'],
        'inlineOriginalSelection': value['inlineOriginalSelection'],
    };
}

