/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelInteger
 */
export interface ModelInteger {
    /**
     * The count number
     * @type {number}
     * @memberof ModelInteger
     */
    count?: number;
}

/**
 * Check if a given object implements the ModelInteger interface.
 */
export function instanceOfModelInteger(value: object): value is ModelInteger {
    return true;
}

export function ModelIntegerFromJSON(json: any): ModelInteger {
    return ModelIntegerFromJSONTyped(json, false);
}

export function ModelIntegerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelInteger {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function ModelIntegerToJSON(json: any): ModelInteger {
    return ModelIntegerToJSONTyped(json, false);
}

export function ModelIntegerToJSONTyped(value?: ModelInteger | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
    };
}

