/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpaceBulk } from './SpaceBulk';
import {
    SpaceBulkFromJSON,
    SpaceBulkFromJSONTyped,
    SpaceBulkToJSON,
    SpaceBulkToJSONTyped,
} from './SpaceBulk';
import type { MultiEntityLinks } from './MultiEntityLinks';
import {
    MultiEntityLinksFromJSON,
    MultiEntityLinksFromJSONTyped,
    MultiEntityLinksToJSON,
    MultiEntityLinksToJSONTyped,
} from './MultiEntityLinks';

/**
 * 
 * @export
 * @interface MultiEntityResultSpace
 */
export interface MultiEntityResultSpace {
    /**
     * 
     * @type {Array<SpaceBulk>}
     * @memberof MultiEntityResultSpace
     */
    results?: Array<SpaceBulk>;
    /**
     * 
     * @type {MultiEntityLinks}
     * @memberof MultiEntityResultSpace
     */
    links?: MultiEntityLinks;
}

/**
 * Check if a given object implements the MultiEntityResultSpace interface.
 */
export function instanceOfMultiEntityResultSpace(value: object): value is MultiEntityResultSpace {
    return true;
}

export function MultiEntityResultSpaceFromJSON(json: any): MultiEntityResultSpace {
    return MultiEntityResultSpaceFromJSONTyped(json, false);
}

export function MultiEntityResultSpaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiEntityResultSpace {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(SpaceBulkFromJSON)),
        'links': json['_links'] == null ? undefined : MultiEntityLinksFromJSON(json['_links']),
    };
}

export function MultiEntityResultSpaceToJSON(json: any): MultiEntityResultSpace {
    return MultiEntityResultSpaceToJSONTyped(json, false);
}

export function MultiEntityResultSpaceToJSONTyped(value?: MultiEntityResultSpace | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(SpaceBulkToJSON)),
        '_links': MultiEntityLinksToJSON(value['links']),
    };
}

