/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DescendantsResponse } from './DescendantsResponse';
import {
    DescendantsResponseFromJSON,
    DescendantsResponseFromJSONTyped,
    DescendantsResponseToJSON,
    DescendantsResponseToJSONTyped,
} from './DescendantsResponse';
import type { MultiEntityLinks } from './MultiEntityLinks';
import {
    MultiEntityLinksFromJSON,
    MultiEntityLinksFromJSONTyped,
    MultiEntityLinksToJSON,
    MultiEntityLinksToJSONTyped,
} from './MultiEntityLinks';

/**
 * 
 * @export
 * @interface MultiEntityResultDescendantsResponse
 */
export interface MultiEntityResultDescendantsResponse {
    /**
     * 
     * @type {Array<DescendantsResponse>}
     * @memberof MultiEntityResultDescendantsResponse
     */
    results?: Array<DescendantsResponse>;
    /**
     * 
     * @type {MultiEntityLinks}
     * @memberof MultiEntityResultDescendantsResponse
     */
    links?: MultiEntityLinks;
}

/**
 * Check if a given object implements the MultiEntityResultDescendantsResponse interface.
 */
export function instanceOfMultiEntityResultDescendantsResponse(value: object): value is MultiEntityResultDescendantsResponse {
    return true;
}

export function MultiEntityResultDescendantsResponseFromJSON(json: any): MultiEntityResultDescendantsResponse {
    return MultiEntityResultDescendantsResponseFromJSONTyped(json, false);
}

export function MultiEntityResultDescendantsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiEntityResultDescendantsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(DescendantsResponseFromJSON)),
        'links': json['_links'] == null ? undefined : MultiEntityLinksFromJSON(json['_links']),
    };
}

export function MultiEntityResultDescendantsResponseToJSON(json: any): MultiEntityResultDescendantsResponse {
    return MultiEntityResultDescendantsResponseToJSONTyped(json, false);
}

export function MultiEntityResultDescendantsResponseToJSONTyped(value?: MultiEntityResultDescendantsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(DescendantsResponseToJSON)),
        '_links': MultiEntityLinksToJSON(value['links']),
    };
}

