/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FooterCommentModel } from './FooterCommentModel';
import {
    FooterCommentModelFromJSON,
    FooterCommentModelFromJSONTyped,
    FooterCommentModelToJSON,
    FooterCommentModelToJSONTyped,
} from './FooterCommentModel';
import type { MultiEntityLinks } from './MultiEntityLinks';
import {
    MultiEntityLinksFromJSON,
    MultiEntityLinksFromJSONTyped,
    MultiEntityLinksToJSON,
    MultiEntityLinksToJSONTyped,
} from './MultiEntityLinks';

/**
 * 
 * @export
 * @interface MultiEntityResultFooterCommentModel
 */
export interface MultiEntityResultFooterCommentModel {
    /**
     * 
     * @type {Array<FooterCommentModel>}
     * @memberof MultiEntityResultFooterCommentModel
     */
    results?: Array<FooterCommentModel>;
    /**
     * 
     * @type {MultiEntityLinks}
     * @memberof MultiEntityResultFooterCommentModel
     */
    links?: MultiEntityLinks;
}

/**
 * Check if a given object implements the MultiEntityResultFooterCommentModel interface.
 */
export function instanceOfMultiEntityResultFooterCommentModel(value: object): value is MultiEntityResultFooterCommentModel {
    return true;
}

export function MultiEntityResultFooterCommentModelFromJSON(json: any): MultiEntityResultFooterCommentModel {
    return MultiEntityResultFooterCommentModelFromJSONTyped(json, false);
}

export function MultiEntityResultFooterCommentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiEntityResultFooterCommentModel {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(FooterCommentModelFromJSON)),
        'links': json['_links'] == null ? undefined : MultiEntityLinksFromJSON(json['_links']),
    };
}

export function MultiEntityResultFooterCommentModelToJSON(json: any): MultiEntityResultFooterCommentModel {
    return MultiEntityResultFooterCommentModelToJSONTyped(json, false);
}

export function MultiEntityResultFooterCommentModelToJSONTyped(value?: MultiEntityResultFooterCommentModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(FooterCommentModelToJSON)),
        '_links': MultiEntityLinksToJSON(value['links']),
    };
}

