/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpacePermission } from './SpacePermission';
import {
    SpacePermissionFromJSON,
    SpacePermissionFromJSONTyped,
    SpacePermissionToJSON,
    SpacePermissionToJSONTyped,
} from './SpacePermission';
import type { MultiEntityLinks } from './MultiEntityLinks';
import {
    MultiEntityLinksFromJSON,
    MultiEntityLinksFromJSONTyped,
    MultiEntityLinksToJSON,
    MultiEntityLinksToJSONTyped,
} from './MultiEntityLinks';

/**
 * 
 * @export
 * @interface MultiEntityResultSpacePermission
 */
export interface MultiEntityResultSpacePermission {
    /**
     * 
     * @type {Array<SpacePermission>}
     * @memberof MultiEntityResultSpacePermission
     */
    results?: Array<SpacePermission>;
    /**
     * 
     * @type {MultiEntityLinks}
     * @memberof MultiEntityResultSpacePermission
     */
    links?: MultiEntityLinks;
}

/**
 * Check if a given object implements the MultiEntityResultSpacePermission interface.
 */
export function instanceOfMultiEntityResultSpacePermission(value: object): value is MultiEntityResultSpacePermission {
    return true;
}

export function MultiEntityResultSpacePermissionFromJSON(json: any): MultiEntityResultSpacePermission {
    return MultiEntityResultSpacePermissionFromJSONTyped(json, false);
}

export function MultiEntityResultSpacePermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiEntityResultSpacePermission {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(SpacePermissionFromJSON)),
        'links': json['_links'] == null ? undefined : MultiEntityLinksFromJSON(json['_links']),
    };
}

export function MultiEntityResultSpacePermissionToJSON(json: any): MultiEntityResultSpacePermission {
    return MultiEntityResultSpacePermissionToJSONTyped(json, false);
}

export function MultiEntityResultSpacePermissionToJSONTyped(value?: MultiEntityResultSpacePermission | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(SpacePermissionToJSON)),
        '_links': MultiEntityLinksToJSON(value['links']),
    };
}

