/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlogPostInlineCommentModel } from './BlogPostInlineCommentModel';
import {
    BlogPostInlineCommentModelFromJSON,
    BlogPostInlineCommentModelFromJSONTyped,
    BlogPostInlineCommentModelToJSON,
    BlogPostInlineCommentModelToJSONTyped,
} from './BlogPostInlineCommentModel';
import type { MultiEntityLinks } from './MultiEntityLinks';
import {
    MultiEntityLinksFromJSON,
    MultiEntityLinksFromJSONTyped,
    MultiEntityLinksToJSON,
    MultiEntityLinksToJSONTyped,
} from './MultiEntityLinks';

/**
 * 
 * @export
 * @interface MultiEntityResultBlogPostInlineCommentModel
 */
export interface MultiEntityResultBlogPostInlineCommentModel {
    /**
     * 
     * @type {Array<BlogPostInlineCommentModel>}
     * @memberof MultiEntityResultBlogPostInlineCommentModel
     */
    results?: Array<BlogPostInlineCommentModel>;
    /**
     * 
     * @type {MultiEntityLinks}
     * @memberof MultiEntityResultBlogPostInlineCommentModel
     */
    links?: MultiEntityLinks;
}

/**
 * Check if a given object implements the MultiEntityResultBlogPostInlineCommentModel interface.
 */
export function instanceOfMultiEntityResultBlogPostInlineCommentModel(value: object): value is MultiEntityResultBlogPostInlineCommentModel {
    return true;
}

export function MultiEntityResultBlogPostInlineCommentModelFromJSON(json: any): MultiEntityResultBlogPostInlineCommentModel {
    return MultiEntityResultBlogPostInlineCommentModelFromJSONTyped(json, false);
}

export function MultiEntityResultBlogPostInlineCommentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiEntityResultBlogPostInlineCommentModel {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(BlogPostInlineCommentModelFromJSON)),
        'links': json['_links'] == null ? undefined : MultiEntityLinksFromJSON(json['_links']),
    };
}

export function MultiEntityResultBlogPostInlineCommentModelToJSON(json: any): MultiEntityResultBlogPostInlineCommentModel {
    return MultiEntityResultBlogPostInlineCommentModelToJSONTyped(json, false);
}

export function MultiEntityResultBlogPostInlineCommentModelToJSONTyped(value?: MultiEntityResultBlogPostInlineCommentModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(BlogPostInlineCommentModelToJSON)),
        '_links': MultiEntityLinksToJSON(value['links']),
    };
}

