/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomContentCommentModel } from './CustomContentCommentModel';
import {
    CustomContentCommentModelFromJSON,
    CustomContentCommentModelFromJSONTyped,
    CustomContentCommentModelToJSON,
    CustomContentCommentModelToJSONTyped,
} from './CustomContentCommentModel';
import type { MultiEntityLinks } from './MultiEntityLinks';
import {
    MultiEntityLinksFromJSON,
    MultiEntityLinksFromJSONTyped,
    MultiEntityLinksToJSON,
    MultiEntityLinksToJSONTyped,
} from './MultiEntityLinks';

/**
 * 
 * @export
 * @interface MultiEntityResultCustomContentCommentModel
 */
export interface MultiEntityResultCustomContentCommentModel {
    /**
     * 
     * @type {Array<CustomContentCommentModel>}
     * @memberof MultiEntityResultCustomContentCommentModel
     */
    results?: Array<CustomContentCommentModel>;
    /**
     * 
     * @type {MultiEntityLinks}
     * @memberof MultiEntityResultCustomContentCommentModel
     */
    links?: MultiEntityLinks;
}

/**
 * Check if a given object implements the MultiEntityResultCustomContentCommentModel interface.
 */
export function instanceOfMultiEntityResultCustomContentCommentModel(value: object): value is MultiEntityResultCustomContentCommentModel {
    return true;
}

export function MultiEntityResultCustomContentCommentModelFromJSON(json: any): MultiEntityResultCustomContentCommentModel {
    return MultiEntityResultCustomContentCommentModelFromJSONTyped(json, false);
}

export function MultiEntityResultCustomContentCommentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiEntityResultCustomContentCommentModel {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(CustomContentCommentModelFromJSON)),
        'links': json['_links'] == null ? undefined : MultiEntityLinksFromJSON(json['_links']),
    };
}

export function MultiEntityResultCustomContentCommentModelToJSON(json: any): MultiEntityResultCustomContentCommentModel {
    return MultiEntityResultCustomContentCommentModelToJSONTyped(json, false);
}

export function MultiEntityResultCustomContentCommentModelToJSONTyped(value?: MultiEntityResultCustomContentCommentModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(CustomContentCommentModelToJSON)),
        '_links': MultiEntityLinksToJSON(value['links']),
    };
}

