/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageCommentModel } from './PageCommentModel';
import {
    PageCommentModelFromJSON,
    PageCommentModelFromJSONTyped,
    PageCommentModelToJSON,
    PageCommentModelToJSONTyped,
} from './PageCommentModel';
import type { MultiEntityLinks } from './MultiEntityLinks';
import {
    MultiEntityLinksFromJSON,
    MultiEntityLinksFromJSONTyped,
    MultiEntityLinksToJSON,
    MultiEntityLinksToJSONTyped,
} from './MultiEntityLinks';

/**
 * 
 * @export
 * @interface MultiEntityResultPageCommentModel
 */
export interface MultiEntityResultPageCommentModel {
    /**
     * 
     * @type {Array<PageCommentModel>}
     * @memberof MultiEntityResultPageCommentModel
     */
    results?: Array<PageCommentModel>;
    /**
     * 
     * @type {MultiEntityLinks}
     * @memberof MultiEntityResultPageCommentModel
     */
    links?: MultiEntityLinks;
}

/**
 * Check if a given object implements the MultiEntityResultPageCommentModel interface.
 */
export function instanceOfMultiEntityResultPageCommentModel(value: object): value is MultiEntityResultPageCommentModel {
    return true;
}

export function MultiEntityResultPageCommentModelFromJSON(json: any): MultiEntityResultPageCommentModel {
    return MultiEntityResultPageCommentModelFromJSONTyped(json, false);
}

export function MultiEntityResultPageCommentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiEntityResultPageCommentModel {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(PageCommentModelFromJSON)),
        'links': json['_links'] == null ? undefined : MultiEntityLinksFromJSON(json['_links']),
    };
}

export function MultiEntityResultPageCommentModelToJSON(json: any): MultiEntityResultPageCommentModel {
    return MultiEntityResultPageCommentModelToJSONTyped(json, false);
}

export function MultiEntityResultPageCommentModelToJSONTyped(value?: MultiEntityResultPageCommentModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(PageCommentModelToJSON)),
        '_links': MultiEntityLinksToJSON(value['links']),
    };
}

