/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MultiEntityLinks
 */
export interface MultiEntityLinks {
    /**
     * Used for pagination. Contains the relative URL for the next set of results, using a cursor query parameter.
     * This property will not be present if there is no additional data available.
     * @type {string}
     * @memberof MultiEntityLinks
     */
    next?: string;
    /**
     * Base url of the Confluence site.
     * @type {string}
     * @memberof MultiEntityLinks
     */
    base?: string;
}

/**
 * Check if a given object implements the MultiEntityLinks interface.
 */
export function instanceOfMultiEntityLinks(value: object): value is MultiEntityLinks {
    return true;
}

export function MultiEntityLinksFromJSON(json: any): MultiEntityLinks {
    return MultiEntityLinksFromJSONTyped(json, false);
}

export function MultiEntityLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiEntityLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'next': json['next'] == null ? undefined : json['next'],
        'base': json['base'] == null ? undefined : json['base'],
    };
}

export function MultiEntityLinksToJSON(json: any): MultiEntityLinks {
    return MultiEntityLinksToJSONTyped(json, false);
}

export function MultiEntityLinksToJSONTyped(value?: MultiEntityLinks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'next': value['next'],
        'base': value['base'],
    };
}

