/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomContentBulk } from './CustomContentBulk';
import {
    CustomContentBulkFromJSON,
    CustomContentBulkFromJSONTyped,
    CustomContentBulkToJSON,
    CustomContentBulkToJSONTyped,
} from './CustomContentBulk';
import type { MultiEntityLinks } from './MultiEntityLinks';
import {
    MultiEntityLinksFromJSON,
    MultiEntityLinksFromJSONTyped,
    MultiEntityLinksToJSON,
    MultiEntityLinksToJSONTyped,
} from './MultiEntityLinks';

/**
 * 
 * @export
 * @interface MultiEntityResultCustomContent
 */
export interface MultiEntityResultCustomContent {
    /**
     * 
     * @type {Array<CustomContentBulk>}
     * @memberof MultiEntityResultCustomContent
     */
    results?: Array<CustomContentBulk>;
    /**
     * 
     * @type {MultiEntityLinks}
     * @memberof MultiEntityResultCustomContent
     */
    links?: MultiEntityLinks;
}

/**
 * Check if a given object implements the MultiEntityResultCustomContent interface.
 */
export function instanceOfMultiEntityResultCustomContent(value: object): value is MultiEntityResultCustomContent {
    return true;
}

export function MultiEntityResultCustomContentFromJSON(json: any): MultiEntityResultCustomContent {
    return MultiEntityResultCustomContentFromJSONTyped(json, false);
}

export function MultiEntityResultCustomContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiEntityResultCustomContent {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(CustomContentBulkFromJSON)),
        'links': json['_links'] == null ? undefined : MultiEntityLinksFromJSON(json['_links']),
    };
}

export function MultiEntityResultCustomContentToJSON(json: any): MultiEntityResultCustomContent {
    return MultiEntityResultCustomContentToJSONTyped(json, false);
}

export function MultiEntityResultCustomContentToJSONTyped(value?: MultiEntityResultCustomContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(CustomContentBulkToJSON)),
        '_links': MultiEntityLinksToJSON(value['links']),
    };
}

