/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Like } from './Like';
import {
    LikeFromJSON,
    LikeFromJSONTyped,
    LikeToJSON,
    LikeToJSONTyped,
} from './Like';
import type { MultiEntityLinks } from './MultiEntityLinks';
import {
    MultiEntityLinksFromJSON,
    MultiEntityLinksFromJSONTyped,
    MultiEntityLinksToJSON,
    MultiEntityLinksToJSONTyped,
} from './MultiEntityLinks';

/**
 * 
 * @export
 * @interface MultiEntityResultString
 */
export interface MultiEntityResultString {
    /**
     * 
     * @type {Array<Like>}
     * @memberof MultiEntityResultString
     */
    results?: Array<Like>;
    /**
     * 
     * @type {MultiEntityLinks}
     * @memberof MultiEntityResultString
     */
    links?: MultiEntityLinks;
}

/**
 * Check if a given object implements the MultiEntityResultString interface.
 */
export function instanceOfMultiEntityResultString(value: object): value is MultiEntityResultString {
    return true;
}

export function MultiEntityResultStringFromJSON(json: any): MultiEntityResultString {
    return MultiEntityResultStringFromJSONTyped(json, false);
}

export function MultiEntityResultStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiEntityResultString {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(LikeFromJSON)),
        'links': json['_links'] == null ? undefined : MultiEntityLinksFromJSON(json['_links']),
    };
}

export function MultiEntityResultStringToJSON(json: any): MultiEntityResultString {
    return MultiEntityResultStringToJSONTyped(json, false);
}

export function MultiEntityResultStringToJSONTyped(value?: MultiEntityResultString | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(LikeToJSON)),
        '_links': MultiEntityLinksToJSON(value['links']),
    };
}

