/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Ancestor } from './Ancestor';
import {
    AncestorFromJSON,
    AncestorFromJSONTyped,
    AncestorToJSON,
    AncestorToJSONTyped,
} from './Ancestor';

/**
 * 
 * @export
 * @interface MultiEntityResultAncestor
 */
export interface MultiEntityResultAncestor {
    /**
     * 
     * @type {Array<Ancestor>}
     * @memberof MultiEntityResultAncestor
     */
    results?: Array<Ancestor>;
}

/**
 * Check if a given object implements the MultiEntityResultAncestor interface.
 */
export function instanceOfMultiEntityResultAncestor(value: object): value is MultiEntityResultAncestor {
    return true;
}

export function MultiEntityResultAncestorFromJSON(json: any): MultiEntityResultAncestor {
    return MultiEntityResultAncestorFromJSONTyped(json, false);
}

export function MultiEntityResultAncestorFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiEntityResultAncestor {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(AncestorFromJSON)),
    };
}

export function MultiEntityResultAncestorToJSON(json: any): MultiEntityResultAncestor {
    return MultiEntityResultAncestorToJSONTyped(json, false);
}

export function MultiEntityResultAncestorToJSONTyped(value?: MultiEntityResultAncestor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(AncestorToJSON)),
    };
}

