/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageBulk } from './PageBulk';
import {
    PageBulkFromJSON,
    PageBulkFromJSONTyped,
    PageBulkToJSON,
    PageBulkToJSONTyped,
} from './PageBulk';
import type { MultiEntityLinks } from './MultiEntityLinks';
import {
    MultiEntityLinksFromJSON,
    MultiEntityLinksFromJSONTyped,
    MultiEntityLinksToJSON,
    MultiEntityLinksToJSONTyped,
} from './MultiEntityLinks';

/**
 * 
 * @export
 * @interface MultiEntityResultPage
 */
export interface MultiEntityResultPage {
    /**
     * 
     * @type {Array<PageBulk>}
     * @memberof MultiEntityResultPage
     */
    results?: Array<PageBulk>;
    /**
     * 
     * @type {MultiEntityLinks}
     * @memberof MultiEntityResultPage
     */
    links?: MultiEntityLinks;
}

/**
 * Check if a given object implements the MultiEntityResultPage interface.
 */
export function instanceOfMultiEntityResultPage(value: object): value is MultiEntityResultPage {
    return true;
}

export function MultiEntityResultPageFromJSON(json: any): MultiEntityResultPage {
    return MultiEntityResultPageFromJSONTyped(json, false);
}

export function MultiEntityResultPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiEntityResultPage {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(PageBulkFromJSON)),
        'links': json['_links'] == null ? undefined : MultiEntityLinksFromJSON(json['_links']),
    };
}

export function MultiEntityResultPageToJSON(json: any): MultiEntityResultPage {
    return MultiEntityResultPageToJSONTyped(json, false);
}

export function MultiEntityResultPageToJSONTyped(value?: MultiEntityResultPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(PageBulkToJSON)),
        '_links': MultiEntityLinksToJSON(value['links']),
    };
}

