/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChildCustomContent } from './ChildCustomContent';
import {
    ChildCustomContentFromJSON,
    ChildCustomContentFromJSONTyped,
    ChildCustomContentToJSON,
    ChildCustomContentToJSONTyped,
} from './ChildCustomContent';
import type { MultiEntityLinks } from './MultiEntityLinks';
import {
    MultiEntityLinksFromJSON,
    MultiEntityLinksFromJSONTyped,
    MultiEntityLinksToJSON,
    MultiEntityLinksToJSONTyped,
} from './MultiEntityLinks';

/**
 * 
 * @export
 * @interface MultiEntityResultChildCustomContent
 */
export interface MultiEntityResultChildCustomContent {
    /**
     * 
     * @type {Array<ChildCustomContent>}
     * @memberof MultiEntityResultChildCustomContent
     */
    results?: Array<ChildCustomContent>;
    /**
     * 
     * @type {MultiEntityLinks}
     * @memberof MultiEntityResultChildCustomContent
     */
    links?: MultiEntityLinks;
}

/**
 * Check if a given object implements the MultiEntityResultChildCustomContent interface.
 */
export function instanceOfMultiEntityResultChildCustomContent(value: object): value is MultiEntityResultChildCustomContent {
    return true;
}

export function MultiEntityResultChildCustomContentFromJSON(json: any): MultiEntityResultChildCustomContent {
    return MultiEntityResultChildCustomContentFromJSONTyped(json, false);
}

export function MultiEntityResultChildCustomContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiEntityResultChildCustomContent {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(ChildCustomContentFromJSON)),
        'links': json['_links'] == null ? undefined : MultiEntityLinksFromJSON(json['_links']),
    };
}

export function MultiEntityResultChildCustomContentToJSON(json: any): MultiEntityResultChildCustomContent {
    return MultiEntityResultChildCustomContentToJSONTyped(json, false);
}

export function MultiEntityResultChildCustomContentToJSONTyped(value?: MultiEntityResultChildCustomContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(ChildCustomContentToJSON)),
        '_links': MultiEntityLinksToJSON(value['links']),
    };
}

