/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Label } from './Label';
import {
    LabelFromJSON,
    LabelFromJSONTyped,
    LabelToJSON,
    LabelToJSONTyped,
} from './Label';
import type { MultiEntityLinks } from './MultiEntityLinks';
import {
    MultiEntityLinksFromJSON,
    MultiEntityLinksFromJSONTyped,
    MultiEntityLinksToJSON,
    MultiEntityLinksToJSONTyped,
} from './MultiEntityLinks';

/**
 * 
 * @export
 * @interface MultiEntityResultLabel
 */
export interface MultiEntityResultLabel {
    /**
     * 
     * @type {Array<Label>}
     * @memberof MultiEntityResultLabel
     */
    results?: Array<Label>;
    /**
     * 
     * @type {MultiEntityLinks}
     * @memberof MultiEntityResultLabel
     */
    links?: MultiEntityLinks;
}

/**
 * Check if a given object implements the MultiEntityResultLabel interface.
 */
export function instanceOfMultiEntityResultLabel(value: object): value is MultiEntityResultLabel {
    return true;
}

export function MultiEntityResultLabelFromJSON(json: any): MultiEntityResultLabel {
    return MultiEntityResultLabelFromJSONTyped(json, false);
}

export function MultiEntityResultLabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiEntityResultLabel {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(LabelFromJSON)),
        'links': json['_links'] == null ? undefined : MultiEntityLinksFromJSON(json['_links']),
    };
}

export function MultiEntityResultLabelToJSON(json: any): MultiEntityResultLabel {
    return MultiEntityResultLabelToJSONTyped(json, false);
}

export function MultiEntityResultLabelToJSONTyped(value?: MultiEntityResultLabel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(LabelToJSON)),
        '_links': MultiEntityLinksToJSON(value['links']),
    };
}

