/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InlineCommentModel } from './InlineCommentModel';
import {
    InlineCommentModelFromJSON,
    InlineCommentModelFromJSONTyped,
    InlineCommentModelToJSON,
    InlineCommentModelToJSONTyped,
} from './InlineCommentModel';
import type { MultiEntityLinks } from './MultiEntityLinks';
import {
    MultiEntityLinksFromJSON,
    MultiEntityLinksFromJSONTyped,
    MultiEntityLinksToJSON,
    MultiEntityLinksToJSONTyped,
} from './MultiEntityLinks';

/**
 * 
 * @export
 * @interface MultiEntityResultInlineCommentModel
 */
export interface MultiEntityResultInlineCommentModel {
    /**
     * 
     * @type {Array<InlineCommentModel>}
     * @memberof MultiEntityResultInlineCommentModel
     */
    results?: Array<InlineCommentModel>;
    /**
     * 
     * @type {MultiEntityLinks}
     * @memberof MultiEntityResultInlineCommentModel
     */
    links?: MultiEntityLinks;
}

/**
 * Check if a given object implements the MultiEntityResultInlineCommentModel interface.
 */
export function instanceOfMultiEntityResultInlineCommentModel(value: object): value is MultiEntityResultInlineCommentModel {
    return true;
}

export function MultiEntityResultInlineCommentModelFromJSON(json: any): MultiEntityResultInlineCommentModel {
    return MultiEntityResultInlineCommentModelFromJSONTyped(json, false);
}

export function MultiEntityResultInlineCommentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiEntityResultInlineCommentModel {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(InlineCommentModelFromJSON)),
        'links': json['_links'] == null ? undefined : MultiEntityLinksFromJSON(json['_links']),
    };
}

export function MultiEntityResultInlineCommentModelToJSON(json: any): MultiEntityResultInlineCommentModel {
    return MultiEntityResultInlineCommentModelToJSONTyped(json, false);
}

export function MultiEntityResultInlineCommentModelToJSONTyped(value?: MultiEntityResultInlineCommentModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(InlineCommentModelToJSON)),
        '_links': MultiEntityLinksToJSON(value['links']),
    };
}

