/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { MultiEntityLinks } from './MultiEntityLinks';
import {
    MultiEntityLinksFromJSON,
    MultiEntityLinksFromJSONTyped,
    MultiEntityLinksToJSON,
    MultiEntityLinksToJSONTyped,
} from './MultiEntityLinks';

/**
 * 
 * @export
 * @interface MultiEntityResultUser
 */
export interface MultiEntityResultUser {
    /**
     * 
     * @type {Array<User>}
     * @memberof MultiEntityResultUser
     */
    results?: Array<User>;
    /**
     * 
     * @type {MultiEntityLinks}
     * @memberof MultiEntityResultUser
     */
    links?: MultiEntityLinks;
}

/**
 * Check if a given object implements the MultiEntityResultUser interface.
 */
export function instanceOfMultiEntityResultUser(value: object): value is MultiEntityResultUser {
    return true;
}

export function MultiEntityResultUserFromJSON(json: any): MultiEntityResultUser {
    return MultiEntityResultUserFromJSONTyped(json, false);
}

export function MultiEntityResultUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiEntityResultUser {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(UserFromJSON)),
        'links': json['_links'] == null ? undefined : MultiEntityLinksFromJSON(json['_links']),
    };
}

export function MultiEntityResultUserToJSON(json: any): MultiEntityResultUser {
    return MultiEntityResultUserToJSONTyped(json, false);
}

export function MultiEntityResultUserToJSONTyped(value?: MultiEntityResultUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(UserToJSON)),
        '_links': MultiEntityLinksToJSON(value['links']),
    };
}

