/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MultiEntityResultAppPropertyResultsInner
 */
export interface MultiEntityResultAppPropertyResultsInner {
    /**
     * The key of the property
     * @type {string}
     * @memberof MultiEntityResultAppPropertyResultsInner
     */
    key?: string;
    /**
     * The value of the property
     * @type {object}
     * @memberof MultiEntityResultAppPropertyResultsInner
     */
    value?: object;
}

/**
 * Check if a given object implements the MultiEntityResultAppPropertyResultsInner interface.
 */
export function instanceOfMultiEntityResultAppPropertyResultsInner(value: object): value is MultiEntityResultAppPropertyResultsInner {
    return true;
}

export function MultiEntityResultAppPropertyResultsInnerFromJSON(json: any): MultiEntityResultAppPropertyResultsInner {
    return MultiEntityResultAppPropertyResultsInnerFromJSONTyped(json, false);
}

export function MultiEntityResultAppPropertyResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiEntityResultAppPropertyResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function MultiEntityResultAppPropertyResultsInnerToJSON(json: any): MultiEntityResultAppPropertyResultsInner {
    return MultiEntityResultAppPropertyResultsInnerToJSONTyped(json, false);
}

export function MultiEntityResultAppPropertyResultsInnerToJSONTyped(value?: MultiEntityResultAppPropertyResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

