/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InlineCommentChildrenModel } from './InlineCommentChildrenModel';
import {
    InlineCommentChildrenModelFromJSON,
    InlineCommentChildrenModelFromJSONTyped,
    InlineCommentChildrenModelToJSON,
    InlineCommentChildrenModelToJSONTyped,
} from './InlineCommentChildrenModel';
import type { MultiEntityLinks } from './MultiEntityLinks';
import {
    MultiEntityLinksFromJSON,
    MultiEntityLinksFromJSONTyped,
    MultiEntityLinksToJSON,
    MultiEntityLinksToJSONTyped,
} from './MultiEntityLinks';

/**
 * 
 * @export
 * @interface MultiEntityResultInlineCommentChildrenModel
 */
export interface MultiEntityResultInlineCommentChildrenModel {
    /**
     * 
     * @type {Array<InlineCommentChildrenModel>}
     * @memberof MultiEntityResultInlineCommentChildrenModel
     */
    results?: Array<InlineCommentChildrenModel>;
    /**
     * 
     * @type {MultiEntityLinks}
     * @memberof MultiEntityResultInlineCommentChildrenModel
     */
    links?: MultiEntityLinks;
}

/**
 * Check if a given object implements the MultiEntityResultInlineCommentChildrenModel interface.
 */
export function instanceOfMultiEntityResultInlineCommentChildrenModel(value: object): value is MultiEntityResultInlineCommentChildrenModel {
    return true;
}

export function MultiEntityResultInlineCommentChildrenModelFromJSON(json: any): MultiEntityResultInlineCommentChildrenModel {
    return MultiEntityResultInlineCommentChildrenModelFromJSONTyped(json, false);
}

export function MultiEntityResultInlineCommentChildrenModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiEntityResultInlineCommentChildrenModel {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(InlineCommentChildrenModelFromJSON)),
        'links': json['_links'] == null ? undefined : MultiEntityLinksFromJSON(json['_links']),
    };
}

export function MultiEntityResultInlineCommentChildrenModelToJSON(json: any): MultiEntityResultInlineCommentChildrenModel {
    return MultiEntityResultInlineCommentChildrenModelToJSONTyped(json, false);
}

export function MultiEntityResultInlineCommentChildrenModelToJSONTyped(value?: MultiEntityResultInlineCommentChildrenModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(InlineCommentChildrenModelToJSON)),
        '_links': MultiEntityLinksToJSON(value['links']),
    };
}

