/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The status of the content.
 * @export
 */
export const OnlyArchivedAndCurrentContentStatus = {
    Current: 'current',
    Archived: 'archived'
} as const;
export type OnlyArchivedAndCurrentContentStatus = typeof OnlyArchivedAndCurrentContentStatus[keyof typeof OnlyArchivedAndCurrentContentStatus];


export function instanceOfOnlyArchivedAndCurrentContentStatus(value: any): boolean {
    for (const key in OnlyArchivedAndCurrentContentStatus) {
        if (Object.prototype.hasOwnProperty.call(OnlyArchivedAndCurrentContentStatus, key)) {
            if (OnlyArchivedAndCurrentContentStatus[key as keyof typeof OnlyArchivedAndCurrentContentStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OnlyArchivedAndCurrentContentStatusFromJSON(json: any): OnlyArchivedAndCurrentContentStatus {
    return OnlyArchivedAndCurrentContentStatusFromJSONTyped(json, false);
}

export function OnlyArchivedAndCurrentContentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnlyArchivedAndCurrentContentStatus {
    return json as OnlyArchivedAndCurrentContentStatus;
}

export function OnlyArchivedAndCurrentContentStatusToJSON(value?: OnlyArchivedAndCurrentContentStatus | null): any {
    return value as any;
}

export function OnlyArchivedAndCurrentContentStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): OnlyArchivedAndCurrentContentStatus {
    return value as OnlyArchivedAndCurrentContentStatus;
}

