/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Operation
 */
export interface Operation {
    /**
     * The type of operation.
     * @type {string}
     * @memberof Operation
     */
    operation?: string;
    /**
     * The type of entity the operation type targets.
     * @type {string}
     * @memberof Operation
     */
    targetType?: string;
}

/**
 * Check if a given object implements the Operation interface.
 */
export function instanceOfOperation(value: object): value is Operation {
    return true;
}

export function OperationFromJSON(json: any): Operation {
    return OperationFromJSONTyped(json, false);
}

export function OperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Operation {
    if (json == null) {
        return json;
    }
    return {
        
        'operation': json['operation'] == null ? undefined : json['operation'],
        'targetType': json['targetType'] == null ? undefined : json['targetType'],
    };
}

export function OperationToJSON(json: any): Operation {
    return OperationToJSONTyped(json, false);
}

export function OperationToJSONTyped(value?: Operation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operation': value['operation'],
        'targetType': value['targetType'],
    };
}

