/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OptionalFieldLinks
 */
export interface OptionalFieldLinks {
    /**
     * A relative URL that can be used to fetch results beyond what this include parameter retrieves.
     * @type {string}
     * @memberof OptionalFieldLinks
     */
    self?: string;
}

/**
 * Check if a given object implements the OptionalFieldLinks interface.
 */
export function instanceOfOptionalFieldLinks(value: object): value is OptionalFieldLinks {
    return true;
}

export function OptionalFieldLinksFromJSON(json: any): OptionalFieldLinks {
    return OptionalFieldLinksFromJSONTyped(json, false);
}

export function OptionalFieldLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionalFieldLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'self': json['self'] == null ? undefined : json['self'],
    };
}

export function OptionalFieldLinksToJSON(json: any): OptionalFieldLinks {
    return OptionalFieldLinksToJSONTyped(json, false);
}

export function OptionalFieldLinksToJSONTyped(value?: OptionalFieldLinks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'self': value['self'],
    };
}

