/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OptionalFieldMeta
 */
export interface OptionalFieldMeta {
    /**
     * Indicates if there are more available results that can be fetched.
     * @type {boolean}
     * @memberof OptionalFieldMeta
     */
    hasMore?: boolean;
    /**
     * A token that can be used in the query parameter of the endpoint returned in the `_links` property to retrieve the next set of results.
     * @type {string}
     * @memberof OptionalFieldMeta
     */
    cursor?: string;
}

/**
 * Check if a given object implements the OptionalFieldMeta interface.
 */
export function instanceOfOptionalFieldMeta(value: object): value is OptionalFieldMeta {
    return true;
}

export function OptionalFieldMetaFromJSON(json: any): OptionalFieldMeta {
    return OptionalFieldMetaFromJSONTyped(json, false);
}

export function OptionalFieldMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionalFieldMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'hasMore': json['hasMore'] == null ? undefined : json['hasMore'],
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
    };
}

export function OptionalFieldMetaToJSON(json: any): OptionalFieldMeta {
    return OptionalFieldMetaToJSONTyped(json, false);
}

export function OptionalFieldMetaToJSONTyped(value?: OptionalFieldMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hasMore': value['hasMore'],
        'cursor': value['cursor'],
    };
}

