/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageBodyWrite } from './PageBodyWrite';
import {
    PageBodyWriteFromJSON,
    PageBodyWriteFromJSONTyped,
    PageBodyWriteToJSON,
    PageBodyWriteToJSONTyped,
} from './PageBodyWrite';

/**
 * Body of the page. Only one body format should be specified as the property
 * for this object, e.g. `storage`.
 * @export
 * @interface PageNestedBodyWrite
 */
export interface PageNestedBodyWrite {
    /**
     * 
     * @type {PageBodyWrite}
     * @memberof PageNestedBodyWrite
     */
    storage?: PageBodyWrite;
    /**
     * 
     * @type {PageBodyWrite}
     * @memberof PageNestedBodyWrite
     */
    atlasDocFormat?: PageBodyWrite;
    /**
     * 
     * @type {PageBodyWrite}
     * @memberof PageNestedBodyWrite
     */
    wiki?: PageBodyWrite;
}

/**
 * Check if a given object implements the PageNestedBodyWrite interface.
 */
export function instanceOfPageNestedBodyWrite(value: object): value is PageNestedBodyWrite {
    return true;
}

export function PageNestedBodyWriteFromJSON(json: any): PageNestedBodyWrite {
    return PageNestedBodyWriteFromJSONTyped(json, false);
}

export function PageNestedBodyWriteFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageNestedBodyWrite {
    if (json == null) {
        return json;
    }
    return {
        
        'storage': json['storage'] == null ? undefined : PageBodyWriteFromJSON(json['storage']),
        'atlasDocFormat': json['atlas_doc_format'] == null ? undefined : PageBodyWriteFromJSON(json['atlas_doc_format']),
        'wiki': json['wiki'] == null ? undefined : PageBodyWriteFromJSON(json['wiki']),
    };
}

export function PageNestedBodyWriteToJSON(json: any): PageNestedBodyWrite {
    return PageNestedBodyWriteToJSONTyped(json, false);
}

export function PageNestedBodyWriteToJSONTyped(value?: PageNestedBodyWrite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'storage': PageBodyWriteToJSON(value['storage']),
        'atlas_doc_format': PageBodyWriteToJSON(value['atlasDocFormat']),
        'wiki': PageBodyWriteToJSON(value['wiki']),
    };
}

