/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Version } from './Version';
import {
    VersionFromJSON,
    VersionFromJSONTyped,
    VersionToJSON,
    VersionToJSONTyped,
} from './Version';
import type { InlineCommentProperties } from './InlineCommentProperties';
import {
    InlineCommentPropertiesFromJSON,
    InlineCommentPropertiesFromJSONTyped,
    InlineCommentPropertiesToJSON,
    InlineCommentPropertiesToJSONTyped,
} from './InlineCommentProperties';
import type { InlineCommentResolutionStatus } from './InlineCommentResolutionStatus';
import {
    InlineCommentResolutionStatusFromJSON,
    InlineCommentResolutionStatusFromJSONTyped,
    InlineCommentResolutionStatusToJSON,
    InlineCommentResolutionStatusToJSONTyped,
} from './InlineCommentResolutionStatus';
import type { BodyBulk } from './BodyBulk';
import {
    BodyBulkFromJSON,
    BodyBulkFromJSONTyped,
    BodyBulkToJSON,
    BodyBulkToJSONTyped,
} from './BodyBulk';
import type { CommentLinks } from './CommentLinks';
import {
    CommentLinksFromJSON,
    CommentLinksFromJSONTyped,
    CommentLinksToJSON,
    CommentLinksToJSONTyped,
} from './CommentLinks';
import type { ContentStatus } from './ContentStatus';
import {
    ContentStatusFromJSON,
    ContentStatusFromJSONTyped,
    ContentStatusToJSON,
    ContentStatusToJSONTyped,
} from './ContentStatus';

/**
 * 
 * @export
 * @interface PageInlineCommentModel
 */
export interface PageInlineCommentModel {
    /**
     * ID of the comment.
     * @type {string}
     * @memberof PageInlineCommentModel
     */
    id?: string;
    /**
     * 
     * @type {ContentStatus}
     * @memberof PageInlineCommentModel
     */
    status?: ContentStatus;
    /**
     * Title of the comment.
     * @type {string}
     * @memberof PageInlineCommentModel
     */
    title?: string;
    /**
     * ID of the page the comment is in.
     * @type {string}
     * @memberof PageInlineCommentModel
     */
    pageId?: string;
    /**
     * 
     * @type {Version}
     * @memberof PageInlineCommentModel
     */
    version?: Version;
    /**
     * 
     * @type {BodyBulk}
     * @memberof PageInlineCommentModel
     */
    body?: BodyBulk;
    /**
     * 
     * @type {InlineCommentResolutionStatus}
     * @memberof PageInlineCommentModel
     */
    resolutionStatus?: InlineCommentResolutionStatus;
    /**
     * 
     * @type {InlineCommentProperties}
     * @memberof PageInlineCommentModel
     */
    properties?: InlineCommentProperties;
    /**
     * 
     * @type {CommentLinks}
     * @memberof PageInlineCommentModel
     */
    links?: CommentLinks;
}



/**
 * Check if a given object implements the PageInlineCommentModel interface.
 */
export function instanceOfPageInlineCommentModel(value: object): value is PageInlineCommentModel {
    return true;
}

export function PageInlineCommentModelFromJSON(json: any): PageInlineCommentModel {
    return PageInlineCommentModelFromJSONTyped(json, false);
}

export function PageInlineCommentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageInlineCommentModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : ContentStatusFromJSON(json['status']),
        'title': json['title'] == null ? undefined : json['title'],
        'pageId': json['pageId'] == null ? undefined : json['pageId'],
        'version': json['version'] == null ? undefined : VersionFromJSON(json['version']),
        'body': json['body'] == null ? undefined : BodyBulkFromJSON(json['body']),
        'resolutionStatus': json['resolutionStatus'] == null ? undefined : InlineCommentResolutionStatusFromJSON(json['resolutionStatus']),
        'properties': json['properties'] == null ? undefined : InlineCommentPropertiesFromJSON(json['properties']),
        'links': json['_links'] == null ? undefined : CommentLinksFromJSON(json['_links']),
    };
}

export function PageInlineCommentModelToJSON(json: any): PageInlineCommentModel {
    return PageInlineCommentModelToJSONTyped(json, false);
}

export function PageInlineCommentModelToJSONTyped(value?: PageInlineCommentModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': ContentStatusToJSON(value['status']),
        'title': value['title'],
        'pageId': value['pageId'],
        'version': VersionToJSON(value['version']),
        'body': BodyBulkToJSON(value['body']),
        'resolutionStatus': InlineCommentResolutionStatusToJSON(value['resolutionStatus']),
        'properties': InlineCommentPropertiesToJSON(value['properties']),
        '_links': CommentLinksToJSON(value['links']),
    };
}

