/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageBodyWrite
 */
export interface PageBodyWrite {
    /**
     * Type of content representation used for the value field.
     * @type {string}
     * @memberof PageBodyWrite
     */
    representation?: PageBodyWriteRepresentationEnum;
    /**
     * Body of the page, in the format found in the representation field.
     * @type {string}
     * @memberof PageBodyWrite
     */
    value?: string;
}


/**
 * @export
 */
export const PageBodyWriteRepresentationEnum = {
    Storage: 'storage',
    AtlasDocFormat: 'atlas_doc_format',
    Wiki: 'wiki'
} as const;
export type PageBodyWriteRepresentationEnum = typeof PageBodyWriteRepresentationEnum[keyof typeof PageBodyWriteRepresentationEnum];


/**
 * Check if a given object implements the PageBodyWrite interface.
 */
export function instanceOfPageBodyWrite(value: object): value is PageBodyWrite {
    return true;
}

export function PageBodyWriteFromJSON(json: any): PageBodyWrite {
    return PageBodyWriteFromJSONTyped(json, false);
}

export function PageBodyWriteFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageBodyWrite {
    if (json == null) {
        return json;
    }
    return {
        
        'representation': json['representation'] == null ? undefined : json['representation'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function PageBodyWriteToJSON(json: any): PageBodyWrite {
    return PageBodyWriteToJSONTyped(json, false);
}

export function PageBodyWriteToJSONTyped(value?: PageBodyWrite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'representation': value['representation'],
        'value': value['value'],
    };
}

