/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AbstractPageLinks } from './AbstractPageLinks';
import {
    AbstractPageLinksFromJSON,
    AbstractPageLinksFromJSONTyped,
    AbstractPageLinksToJSON,
    AbstractPageLinksToJSONTyped,
} from './AbstractPageLinks';
import type { Version } from './Version';
import {
    VersionFromJSON,
    VersionFromJSONTyped,
    VersionToJSON,
    VersionToJSONTyped,
} from './Version';
import type { BodyBulk } from './BodyBulk';
import {
    BodyBulkFromJSON,
    BodyBulkFromJSONTyped,
    BodyBulkToJSON,
    BodyBulkToJSONTyped,
} from './BodyBulk';
import type { ParentContentType } from './ParentContentType';
import {
    ParentContentTypeFromJSON,
    ParentContentTypeFromJSONTyped,
    ParentContentTypeToJSON,
    ParentContentTypeToJSONTyped,
} from './ParentContentType';
import type { ContentStatus } from './ContentStatus';
import {
    ContentStatusFromJSON,
    ContentStatusFromJSONTyped,
    ContentStatusToJSON,
    ContentStatusToJSONTyped,
} from './ContentStatus';

/**
 * 
 * @export
 * @interface PageBulk
 */
export interface PageBulk {
    /**
     * ID of the page.
     * @type {string}
     * @memberof PageBulk
     */
    id?: string;
    /**
     * 
     * @type {ContentStatus}
     * @memberof PageBulk
     */
    status?: ContentStatus;
    /**
     * Title of the page.
     * @type {string}
     * @memberof PageBulk
     */
    title?: string;
    /**
     * ID of the space the page is in.
     * @type {string}
     * @memberof PageBulk
     */
    spaceId?: string;
    /**
     * ID of the parent page, or null if there is no parent page.
     * @type {string}
     * @memberof PageBulk
     */
    parentId?: string;
    /**
     * 
     * @type {ParentContentType}
     * @memberof PageBulk
     */
    parentType?: ParentContentType;
    /**
     * Position of child page within the given parent page tree.
     * @type {number}
     * @memberof PageBulk
     */
    position?: number | null;
    /**
     * The account ID of the user who created this page originally.
     * @type {string}
     * @memberof PageBulk
     */
    authorId?: string;
    /**
     * The account ID of the user who owns this page.
     * @type {string}
     * @memberof PageBulk
     */
    ownerId?: string | null;
    /**
     * The account ID of the user who owned this page previously, or null if there is no previous owner.
     * @type {string}
     * @memberof PageBulk
     */
    lastOwnerId?: string | null;
    /**
     * The subtype of the page.
     * @type {string}
     * @memberof PageBulk
     */
    subtype?: string | null;
    /**
     * Date and time when the page was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ".
     * @type {Date}
     * @memberof PageBulk
     */
    createdAt?: Date;
    /**
     * 
     * @type {Version}
     * @memberof PageBulk
     */
    version?: Version;
    /**
     * 
     * @type {BodyBulk}
     * @memberof PageBulk
     */
    body?: BodyBulk;
    /**
     * 
     * @type {AbstractPageLinks}
     * @memberof PageBulk
     */
    links?: AbstractPageLinks;
}



/**
 * Check if a given object implements the PageBulk interface.
 */
export function instanceOfPageBulk(value: object): value is PageBulk {
    return true;
}

export function PageBulkFromJSON(json: any): PageBulk {
    return PageBulkFromJSONTyped(json, false);
}

export function PageBulkFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageBulk {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : ContentStatusFromJSON(json['status']),
        'title': json['title'] == null ? undefined : json['title'],
        'spaceId': json['spaceId'] == null ? undefined : json['spaceId'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'parentType': json['parentType'] == null ? undefined : ParentContentTypeFromJSON(json['parentType']),
        'position': json['position'] == null ? undefined : json['position'],
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
        'lastOwnerId': json['lastOwnerId'] == null ? undefined : json['lastOwnerId'],
        'subtype': json['subtype'] == null ? undefined : json['subtype'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'version': json['version'] == null ? undefined : VersionFromJSON(json['version']),
        'body': json['body'] == null ? undefined : BodyBulkFromJSON(json['body']),
        'links': json['_links'] == null ? undefined : AbstractPageLinksFromJSON(json['_links']),
    };
}

export function PageBulkToJSON(json: any): PageBulk {
    return PageBulkToJSONTyped(json, false);
}

export function PageBulkToJSONTyped(value?: PageBulk | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': ContentStatusToJSON(value['status']),
        'title': value['title'],
        'spaceId': value['spaceId'],
        'parentId': value['parentId'],
        'parentType': ParentContentTypeToJSON(value['parentType']),
        'position': value['position'],
        'authorId': value['authorId'],
        'ownerId': value['ownerId'],
        'lastOwnerId': value['lastOwnerId'],
        'subtype': value['subtype'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'version': VersionToJSON(value['version']),
        'body': BodyBulkToJSON(value['body']),
        '_links': AbstractPageLinksToJSON(value['links']),
    };
}

