/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Content type of the parent, or null if there is no parent.
 * @export
 */
export const ParentContentType = {
    Page: 'page',
    Whiteboard: 'whiteboard',
    Database: 'database',
    Embed: 'embed',
    Folder: 'folder'
} as const;
export type ParentContentType = typeof ParentContentType[keyof typeof ParentContentType];


export function instanceOfParentContentType(value: any): boolean {
    for (const key in ParentContentType) {
        if (Object.prototype.hasOwnProperty.call(ParentContentType, key)) {
            if (ParentContentType[key as keyof typeof ParentContentType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ParentContentTypeFromJSON(json: any): ParentContentType {
    return ParentContentTypeFromJSONTyped(json, false);
}

export function ParentContentTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParentContentType {
    return json as ParentContentType;
}

export function ParentContentTypeToJSON(value?: ParentContentType | null): any {
    return value as any;
}

export function ParentContentTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ParentContentType {
    return value as ParentContentType;
}

