/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostWhiteboardClassificationLevelRequest
 */
export interface PostWhiteboardClassificationLevelRequest {
    /**
     * Status of the content.
     * @type {string}
     * @memberof PostWhiteboardClassificationLevelRequest
     */
    status: PostWhiteboardClassificationLevelRequestStatusEnum;
}


/**
 * @export
 */
export const PostWhiteboardClassificationLevelRequestStatusEnum = {
    Current: 'current'
} as const;
export type PostWhiteboardClassificationLevelRequestStatusEnum = typeof PostWhiteboardClassificationLevelRequestStatusEnum[keyof typeof PostWhiteboardClassificationLevelRequestStatusEnum];


/**
 * Check if a given object implements the PostWhiteboardClassificationLevelRequest interface.
 */
export function instanceOfPostWhiteboardClassificationLevelRequest(value: object): value is PostWhiteboardClassificationLevelRequest {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function PostWhiteboardClassificationLevelRequestFromJSON(json: any): PostWhiteboardClassificationLevelRequest {
    return PostWhiteboardClassificationLevelRequestFromJSONTyped(json, false);
}

export function PostWhiteboardClassificationLevelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostWhiteboardClassificationLevelRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function PostWhiteboardClassificationLevelRequestToJSON(json: any): PostWhiteboardClassificationLevelRequest {
    return PostWhiteboardClassificationLevelRequestToJSONTyped(json, false);
}

export function PostWhiteboardClassificationLevelRequestToJSONTyped(value?: PostWhiteboardClassificationLevelRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

