/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostPageClassificationLevelRequest
 */
export interface PostPageClassificationLevelRequest {
    /**
     * Status of the content.
     * @type {string}
     * @memberof PostPageClassificationLevelRequest
     */
    status: PostPageClassificationLevelRequestStatusEnum;
}


/**
 * @export
 */
export const PostPageClassificationLevelRequestStatusEnum = {
    Current: 'current',
    Draft: 'draft'
} as const;
export type PostPageClassificationLevelRequestStatusEnum = typeof PostPageClassificationLevelRequestStatusEnum[keyof typeof PostPageClassificationLevelRequestStatusEnum];


/**
 * Check if a given object implements the PostPageClassificationLevelRequest interface.
 */
export function instanceOfPostPageClassificationLevelRequest(value: object): value is PostPageClassificationLevelRequest {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function PostPageClassificationLevelRequestFromJSON(json: any): PostPageClassificationLevelRequest {
    return PostPageClassificationLevelRequestFromJSONTyped(json, false);
}

export function PostPageClassificationLevelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPageClassificationLevelRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function PostPageClassificationLevelRequestToJSON(json: any): PostPageClassificationLevelRequest {
    return PostPageClassificationLevelRequestToJSONTyped(json, false);
}

export function PostPageClassificationLevelRequestToJSONTyped(value?: PostPageClassificationLevelRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

