/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RedactionPointer } from './RedactionPointer';
import {
    RedactionPointerFromJSON,
    RedactionPointerFromJSONTyped,
    RedactionPointerToJSON,
    RedactionPointerToJSONTyped,
} from './RedactionPointer';

/**
 * 
 * @export
 * @interface PostRedactPageRequestBody
 */
export interface PostRedactPageRequestBody {
    /**
     * 
     * @type {Array<RedactionPointer>}
     * @memberof PostRedactPageRequestBody
     */
    redactions?: Array<RedactionPointer>;
}

/**
 * Check if a given object implements the PostRedactPageRequestBody interface.
 */
export function instanceOfPostRedactPageRequestBody(value: object): value is PostRedactPageRequestBody {
    return true;
}

export function PostRedactPageRequestBodyFromJSON(json: any): PostRedactPageRequestBody {
    return PostRedactPageRequestBodyFromJSONTyped(json, false);
}

export function PostRedactPageRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostRedactPageRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'redactions': json['redactions'] == null ? undefined : ((json['redactions'] as Array<any>).map(RedactionPointerFromJSON)),
    };
}

export function PostRedactPageRequestBodyToJSON(json: any): PostRedactPageRequestBody {
    return PostRedactPageRequestBodyToJSONTyped(json, false);
}

export function PostRedactPageRequestBodyToJSONTyped(value?: PostRedactPageRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'redactions': value['redactions'] == null ? undefined : ((value['redactions'] as Array<any>).map(RedactionPointerToJSON)),
    };
}

