/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The primary formats a body can be represented as. A subset of BodyRepresentation. These formats are the only allowed formats in certain use cases.
 * @export
 */
export const PrimaryBodyRepresentation = {
    Storage: 'storage',
    AtlasDocFormat: 'atlas_doc_format'
} as const;
export type PrimaryBodyRepresentation = typeof PrimaryBodyRepresentation[keyof typeof PrimaryBodyRepresentation];


export function instanceOfPrimaryBodyRepresentation(value: any): boolean {
    for (const key in PrimaryBodyRepresentation) {
        if (Object.prototype.hasOwnProperty.call(PrimaryBodyRepresentation, key)) {
            if (PrimaryBodyRepresentation[key as keyof typeof PrimaryBodyRepresentation] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PrimaryBodyRepresentationFromJSON(json: any): PrimaryBodyRepresentation {
    return PrimaryBodyRepresentationFromJSONTyped(json, false);
}

export function PrimaryBodyRepresentationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrimaryBodyRepresentation {
    return json as PrimaryBodyRepresentation;
}

export function PrimaryBodyRepresentationToJSON(value?: PrimaryBodyRepresentation | null): any {
    return value as any;
}

export function PrimaryBodyRepresentationToJSONTyped(value: any, ignoreDiscriminator: boolean): PrimaryBodyRepresentation {
    return value as PrimaryBodyRepresentation;
}

