/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PrincipalType } from './PrincipalType';
import {
    PrincipalTypeFromJSON,
    PrincipalTypeFromJSONTyped,
    PrincipalTypeToJSON,
    PrincipalTypeToJSONTyped,
} from './PrincipalType';

/**
 * The principal of the role assignment.
 * @export
 * @interface Principal
 */
export interface Principal {
    /**
     * 
     * @type {PrincipalType}
     * @memberof Principal
     */
    principalType?: PrincipalType;
    /**
     * The principal ID.
     * @type {string}
     * @memberof Principal
     */
    principalId?: string;
}



/**
 * Check if a given object implements the Principal interface.
 */
export function instanceOfPrincipal(value: object): value is Principal {
    return true;
}

export function PrincipalFromJSON(json: any): Principal {
    return PrincipalFromJSONTyped(json, false);
}

export function PrincipalFromJSONTyped(json: any, ignoreDiscriminator: boolean): Principal {
    if (json == null) {
        return json;
    }
    return {
        
        'principalType': json['principalType'] == null ? undefined : PrincipalTypeFromJSON(json['principalType']),
        'principalId': json['principalId'] == null ? undefined : json['principalId'],
    };
}

export function PrincipalToJSON(json: any): Principal {
    return PrincipalToJSONTyped(json, false);
}

export function PrincipalToJSONTyped(value?: Principal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'principalType': PrincipalTypeToJSON(value['principalType']),
        'principalId': value['principalId'],
    };
}

