/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The principal type.
 * @export
 */
export const PrincipalType = {
    User: 'USER',
    Group: 'GROUP',
    AccessClass: 'ACCESS_CLASS'
} as const;
export type PrincipalType = typeof PrincipalType[keyof typeof PrincipalType];


export function instanceOfPrincipalType(value: any): boolean {
    for (const key in PrincipalType) {
        if (Object.prototype.hasOwnProperty.call(PrincipalType, key)) {
            if (PrincipalType[key as keyof typeof PrincipalType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PrincipalTypeFromJSON(json: any): PrincipalType {
    return PrincipalTypeFromJSONTyped(json, false);
}

export function PrincipalTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrincipalType {
    return json as PrincipalType;
}

export function PrincipalTypeToJSON(value?: PrincipalType | null): any {
    return value as any;
}

export function PrincipalTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): PrincipalType {
    return value as PrincipalType;
}

