/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutPageClassificationLevelRequest
 */
export interface PutPageClassificationLevelRequest {
    /**
     * The ID of the classification level.
     * @type {string}
     * @memberof PutPageClassificationLevelRequest
     */
    id: string;
    /**
     * Status of the content.
     * @type {string}
     * @memberof PutPageClassificationLevelRequest
     */
    status: PutPageClassificationLevelRequestStatusEnum;
}


/**
 * @export
 */
export const PutPageClassificationLevelRequestStatusEnum = {
    Current: 'current',
    Draft: 'draft'
} as const;
export type PutPageClassificationLevelRequestStatusEnum = typeof PutPageClassificationLevelRequestStatusEnum[keyof typeof PutPageClassificationLevelRequestStatusEnum];


/**
 * Check if a given object implements the PutPageClassificationLevelRequest interface.
 */
export function instanceOfPutPageClassificationLevelRequest(value: object): value is PutPageClassificationLevelRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function PutPageClassificationLevelRequestFromJSON(json: any): PutPageClassificationLevelRequest {
    return PutPageClassificationLevelRequestFromJSONTyped(json, false);
}

export function PutPageClassificationLevelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutPageClassificationLevelRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
    };
}

export function PutPageClassificationLevelRequestToJSON(json: any): PutPageClassificationLevelRequest {
    return PutPageClassificationLevelRequestToJSONTyped(json, false);
}

export function PutPageClassificationLevelRequestToJSONTyped(value?: PutPageClassificationLevelRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
    };
}

