/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutSpaceDefaultClassificationLevelRequest
 */
export interface PutSpaceDefaultClassificationLevelRequest {
    /**
     * The ID of the classification level.
     * @type {string}
     * @memberof PutSpaceDefaultClassificationLevelRequest
     */
    id: string;
}

/**
 * Check if a given object implements the PutSpaceDefaultClassificationLevelRequest interface.
 */
export function instanceOfPutSpaceDefaultClassificationLevelRequest(value: object): value is PutSpaceDefaultClassificationLevelRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function PutSpaceDefaultClassificationLevelRequestFromJSON(json: any): PutSpaceDefaultClassificationLevelRequest {
    return PutSpaceDefaultClassificationLevelRequestFromJSONTyped(json, false);
}

export function PutSpaceDefaultClassificationLevelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutSpaceDefaultClassificationLevelRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function PutSpaceDefaultClassificationLevelRequestToJSON(json: any): PutSpaceDefaultClassificationLevelRequest {
    return PutSpaceDefaultClassificationLevelRequestToJSONTyped(json, false);
}

export function PutSpaceDefaultClassificationLevelRequestToJSONTyped(value?: PutSpaceDefaultClassificationLevelRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

