/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutWhiteboardClassificationLevelRequest
 */
export interface PutWhiteboardClassificationLevelRequest {
    /**
     * The ID of the classification level.
     * @type {string}
     * @memberof PutWhiteboardClassificationLevelRequest
     */
    id: string;
    /**
     * Status of the content.
     * @type {string}
     * @memberof PutWhiteboardClassificationLevelRequest
     */
    status: PutWhiteboardClassificationLevelRequestStatusEnum;
}


/**
 * @export
 */
export const PutWhiteboardClassificationLevelRequestStatusEnum = {
    Current: 'current'
} as const;
export type PutWhiteboardClassificationLevelRequestStatusEnum = typeof PutWhiteboardClassificationLevelRequestStatusEnum[keyof typeof PutWhiteboardClassificationLevelRequestStatusEnum];


/**
 * Check if a given object implements the PutWhiteboardClassificationLevelRequest interface.
 */
export function instanceOfPutWhiteboardClassificationLevelRequest(value: object): value is PutWhiteboardClassificationLevelRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function PutWhiteboardClassificationLevelRequestFromJSON(json: any): PutWhiteboardClassificationLevelRequest {
    return PutWhiteboardClassificationLevelRequestFromJSONTyped(json, false);
}

export function PutWhiteboardClassificationLevelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutWhiteboardClassificationLevelRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
    };
}

export function PutWhiteboardClassificationLevelRequestToJSON(json: any): PutWhiteboardClassificationLevelRequest {
    return PutWhiteboardClassificationLevelRequestToJSONTyped(json, false);
}

export function PutWhiteboardClassificationLevelRequestToJSONTyped(value?: PutWhiteboardClassificationLevelRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
    };
}

