/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RedactionPointer } from './RedactionPointer';
import {
    RedactionPointerFromJSON,
    RedactionPointerFromJSONTyped,
    RedactionPointerToJSON,
    RedactionPointerToJSONTyped,
} from './RedactionPointer';

/**
 * 
 * @export
 * @interface Redaction
 */
export interface Redaction {
    /**
     * List of specific text ranges to redact within this section
     * @type {Array<RedactionPointer>}
     * @memberof Redaction
     */
    redactions?: Array<RedactionPointer>;
}

/**
 * Check if a given object implements the Redaction interface.
 */
export function instanceOfRedaction(value: object): value is Redaction {
    return true;
}

export function RedactionFromJSON(json: any): Redaction {
    return RedactionFromJSONTyped(json, false);
}

export function RedactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Redaction {
    if (json == null) {
        return json;
    }
    return {
        
        'redactions': json['redactions'] == null ? undefined : ((json['redactions'] as Array<any>).map(RedactionPointerFromJSON)),
    };
}

export function RedactionToJSON(json: any): Redaction {
    return RedactionToJSONTyped(json, false);
}

export function RedactionToJSONTyped(value?: Redaction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'redactions': value['redactions'] == null ? undefined : ((value['redactions'] as Array<any>).map(RedactionPointerToJSON)),
    };
}

