/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RedactionPointerResponse
 */
export interface RedactionPointerResponse {
    /**
     * JSON pointer indicating where the redaction was applied
     * @type {string}
     * @memberof RedactionPointerResponse
     */
    pointer?: string;
    /**
     * Starting character index where redaction was applied
     * @type {number}
     * @memberof RedactionPointerResponse
     */
    from?: number;
    /**
     * Ending character index where redaction was applied
     * @type {number}
     * @memberof RedactionPointerResponse
     */
    to?: number;
    /**
     * Reason for the redaction
     * @type {string}
     * @memberof RedactionPointerResponse
     */
    reason?: string;
    /**
     * Unique identifier for this redaction. Can be used to restore the redacted content later.
     * 
     * @type {string}
     * @memberof RedactionPointerResponse
     */
    redactionId?: string;
}

/**
 * Check if a given object implements the RedactionPointerResponse interface.
 */
export function instanceOfRedactionPointerResponse(value: object): value is RedactionPointerResponse {
    return true;
}

export function RedactionPointerResponseFromJSON(json: any): RedactionPointerResponse {
    return RedactionPointerResponseFromJSONTyped(json, false);
}

export function RedactionPointerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RedactionPointerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'pointer': json['pointer'] == null ? undefined : json['pointer'],
        'from': json['from'] == null ? undefined : json['from'],
        'to': json['to'] == null ? undefined : json['to'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'redactionId': json['redactionId'] == null ? undefined : json['redactionId'],
    };
}

export function RedactionPointerResponseToJSON(json: any): RedactionPointerResponse {
    return RedactionPointerResponseToJSONTyped(json, false);
}

export function RedactionPointerResponseToJSONTyped(value?: RedactionPointerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pointer': value['pointer'],
        'from': value['from'],
        'to': value['to'],
        'reason': value['reason'],
        'redactionId': value['redactionId'],
    };
}

