/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The role type.
 * @export
 */
export const RoleType = {
    System: 'SYSTEM',
    Custom: 'CUSTOM'
} as const;
export type RoleType = typeof RoleType[keyof typeof RoleType];


export function instanceOfRoleType(value: any): boolean {
    for (const key in RoleType) {
        if (Object.prototype.hasOwnProperty.call(RoleType, key)) {
            if (RoleType[key as keyof typeof RoleType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RoleTypeFromJSON(json: any): RoleType {
    return RoleTypeFromJSONTyped(json, false);
}

export function RoleTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleType {
    return json as RoleType;
}

export function RoleTypeToJSON(value?: RoleType | null): any {
    return value as any;
}

export function RoleTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): RoleType {
    return value as RoleType;
}

