/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Version } from './Version';
import {
    VersionFromJSON,
    VersionFromJSONTyped,
    VersionToJSON,
    VersionToJSONTyped,
} from './Version';
import type { SmartLinkLinks } from './SmartLinkLinks';
import {
    SmartLinkLinksFromJSON,
    SmartLinkLinksFromJSONTyped,
    SmartLinkLinksToJSON,
    SmartLinkLinksToJSONTyped,
} from './SmartLinkLinks';
import type { ParentContentType } from './ParentContentType';
import {
    ParentContentTypeFromJSON,
    ParentContentTypeFromJSONTyped,
    ParentContentTypeToJSON,
    ParentContentTypeToJSONTyped,
} from './ParentContentType';
import type { ContentStatus } from './ContentStatus';
import {
    ContentStatusFromJSON,
    ContentStatusFromJSONTyped,
    ContentStatusToJSON,
    ContentStatusToJSONTyped,
} from './ContentStatus';

/**
 * 
 * @export
 * @interface SmartLinkSingle
 */
export interface SmartLinkSingle {
    /**
     * ID of the Smart Link in the content tree.
     * @type {string}
     * @memberof SmartLinkSingle
     */
    id?: string;
    /**
     * The content type of the object.
     * @type {string}
     * @memberof SmartLinkSingle
     */
    type?: string;
    /**
     * 
     * @type {ContentStatus}
     * @memberof SmartLinkSingle
     */
    status?: ContentStatus;
    /**
     * Title of the Smart Link in the content tree.
     * @type {string}
     * @memberof SmartLinkSingle
     */
    title?: string;
    /**
     * ID of the parent content, or null if there is no parent content.
     * @type {string}
     * @memberof SmartLinkSingle
     */
    parentId?: string;
    /**
     * 
     * @type {ParentContentType}
     * @memberof SmartLinkSingle
     */
    parentType?: ParentContentType;
    /**
     * Position of the Smart Link within the given parent page tree.
     * @type {number}
     * @memberof SmartLinkSingle
     */
    position?: number | null;
    /**
     * The account ID of the user who created this Smart Link in the content tree originally.
     * @type {string}
     * @memberof SmartLinkSingle
     */
    authorId?: string;
    /**
     * The account ID of the user who owns this Smart Link in the content tree.
     * @type {string}
     * @memberof SmartLinkSingle
     */
    ownerId?: string;
    /**
     * Date and time when the Smart Link in the content tree was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ".
     * @type {Date}
     * @memberof SmartLinkSingle
     */
    createdAt?: Date;
    /**
     * The embedded URL of the Smart Link. If the Smart Link does not have an embedded URL, this property will not be included in the response.
     * @type {string}
     * @memberof SmartLinkSingle
     */
    embedUrl?: string;
    /**
     * ID of the space the Smart Link is in.
     * @type {string}
     * @memberof SmartLinkSingle
     */
    spaceId?: string;
    /**
     * 
     * @type {Version}
     * @memberof SmartLinkSingle
     */
    version?: Version;
    /**
     * 
     * @type {SmartLinkLinks}
     * @memberof SmartLinkSingle
     */
    links?: SmartLinkLinks;
}



/**
 * Check if a given object implements the SmartLinkSingle interface.
 */
export function instanceOfSmartLinkSingle(value: object): value is SmartLinkSingle {
    return true;
}

export function SmartLinkSingleFromJSON(json: any): SmartLinkSingle {
    return SmartLinkSingleFromJSONTyped(json, false);
}

export function SmartLinkSingleFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmartLinkSingle {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'status': json['status'] == null ? undefined : ContentStatusFromJSON(json['status']),
        'title': json['title'] == null ? undefined : json['title'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'parentType': json['parentType'] == null ? undefined : ParentContentTypeFromJSON(json['parentType']),
        'position': json['position'] == null ? undefined : json['position'],
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'embedUrl': json['embedUrl'] == null ? undefined : json['embedUrl'],
        'spaceId': json['spaceId'] == null ? undefined : json['spaceId'],
        'version': json['version'] == null ? undefined : VersionFromJSON(json['version']),
        'links': json['_links'] == null ? undefined : SmartLinkLinksFromJSON(json['_links']),
    };
}

export function SmartLinkSingleToJSON(json: any): SmartLinkSingle {
    return SmartLinkSingleToJSONTyped(json, false);
}

export function SmartLinkSingleToJSONTyped(value?: SmartLinkSingle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'status': ContentStatusToJSON(value['status']),
        'title': value['title'],
        'parentId': value['parentId'],
        'parentType': ParentContentTypeToJSON(value['parentType']),
        'position': value['position'],
        'authorId': value['authorId'],
        'ownerId': value['ownerId'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'embedUrl': value['embedUrl'],
        'spaceId': value['spaceId'],
        'version': VersionToJSON(value['version']),
        '_links': SmartLinkLinksToJSON(value['links']),
    };
}

