/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpacePropertyVersion } from './SpacePropertyVersion';
import {
    SpacePropertyVersionFromJSON,
    SpacePropertyVersionFromJSONTyped,
    SpacePropertyVersionToJSON,
    SpacePropertyVersionToJSONTyped,
} from './SpacePropertyVersion';

/**
 * 
 * @export
 * @interface SpaceProperty
 */
export interface SpaceProperty {
    /**
     * ID of the space property.
     * @type {string}
     * @memberof SpaceProperty
     */
    id?: string;
    /**
     * Key of the space property.
     * @type {string}
     * @memberof SpaceProperty
     */
    key?: string;
    /**
     * Value of the space property.
     * @type {any}
     * @memberof SpaceProperty
     */
    value?: any | null;
    /**
     * RFC3339 compliant date time at which the property was created.
     * @type {Date}
     * @memberof SpaceProperty
     */
    createdAt?: Date;
    /**
     * Atlassian account ID of the user that created the space property.
     * @type {string}
     * @memberof SpaceProperty
     */
    createdBy?: string;
    /**
     * 
     * @type {SpacePropertyVersion}
     * @memberof SpaceProperty
     */
    version?: SpacePropertyVersion;
}

/**
 * Check if a given object implements the SpaceProperty interface.
 */
export function instanceOfSpaceProperty(value: object): value is SpaceProperty {
    return true;
}

export function SpacePropertyFromJSON(json: any): SpaceProperty {
    return SpacePropertyFromJSONTyped(json, false);
}

export function SpacePropertyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpaceProperty {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'version': json['version'] == null ? undefined : SpacePropertyVersionFromJSON(json['version']),
    };
}

export function SpacePropertyToJSON(json: any): SpaceProperty {
    return SpacePropertyToJSONTyped(json, false);
}

export function SpacePropertyToJSONTyped(value?: SpaceProperty | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'key': value['key'],
        'value': value['value'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'createdBy': value['createdBy'],
        'version': SpacePropertyVersionToJSON(value['version']),
    };
}

