/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of space.
 * @export
 */
export const SpaceType = {
    Global: 'global',
    Collaboration: 'collaboration',
    KnowledgeBase: 'knowledge_base',
    Personal: 'personal',
    System: 'system',
    Onboarding: 'onboarding',
    XflowSampleSpace: 'xflow_sample_space'
} as const;
export type SpaceType = typeof SpaceType[keyof typeof SpaceType];


export function instanceOfSpaceType(value: any): boolean {
    for (const key in SpaceType) {
        if (Object.prototype.hasOwnProperty.call(SpaceType, key)) {
            if (SpaceType[key as keyof typeof SpaceType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SpaceTypeFromJSON(json: any): SpaceType {
    return SpaceTypeFromJSONTyped(json, false);
}

export function SpaceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpaceType {
    return json as SpaceType;
}

export function SpaceTypeToJSON(value?: SpaceType | null): any {
    return value as any;
}

export function SpaceTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): SpaceType {
    return value as SpaceType;
}

