/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpacePropertyVersion
 */
export interface SpacePropertyVersion {
    /**
     * RFC3339 compliant date time at which the property's current version was created.
     * @type {Date}
     * @memberof SpacePropertyVersion
     */
    createdAt?: Date;
    /**
     * Atlassian account ID of the user that created the space property's current version.
     * @type {string}
     * @memberof SpacePropertyVersion
     */
    createdBy?: string;
    /**
     * Message associated with the current version.
     * @type {string}
     * @memberof SpacePropertyVersion
     */
    message?: string;
    /**
     * The space property's current version number.
     * @type {number}
     * @memberof SpacePropertyVersion
     */
    number?: number;
}

/**
 * Check if a given object implements the SpacePropertyVersion interface.
 */
export function instanceOfSpacePropertyVersion(value: object): value is SpacePropertyVersion {
    return true;
}

export function SpacePropertyVersionFromJSON(json: any): SpacePropertyVersion {
    return SpacePropertyVersionFromJSONTyped(json, false);
}

export function SpacePropertyVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpacePropertyVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'message': json['message'] == null ? undefined : json['message'],
        'number': json['number'] == null ? undefined : json['number'],
    };
}

export function SpacePropertyVersionToJSON(json: any): SpacePropertyVersion {
    return SpacePropertyVersionToJSONTyped(json, false);
}

export function SpacePropertyVersionToJSONTyped(value?: SpacePropertyVersion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'createdBy': value['createdBy'],
        'message': value['message'],
        'number': value['number'],
    };
}

