/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpacePermissionAssignmentPrincipal } from './SpacePermissionAssignmentPrincipal';
import {
    SpacePermissionAssignmentPrincipalFromJSON,
    SpacePermissionAssignmentPrincipalFromJSONTyped,
    SpacePermissionAssignmentPrincipalToJSON,
    SpacePermissionAssignmentPrincipalToJSONTyped,
} from './SpacePermissionAssignmentPrincipal';
import type { SpacePermissionAssignmentOperation } from './SpacePermissionAssignmentOperation';
import {
    SpacePermissionAssignmentOperationFromJSON,
    SpacePermissionAssignmentOperationFromJSONTyped,
    SpacePermissionAssignmentOperationToJSON,
    SpacePermissionAssignmentOperationToJSONTyped,
} from './SpacePermissionAssignmentOperation';

/**
 * 
 * @export
 * @interface SpacePermissionAssignment
 */
export interface SpacePermissionAssignment {
    /**
     * ID of the space permission.
     * @type {string}
     * @memberof SpacePermissionAssignment
     */
    id?: string;
    /**
     * 
     * @type {SpacePermissionAssignmentPrincipal}
     * @memberof SpacePermissionAssignment
     */
    principal?: SpacePermissionAssignmentPrincipal;
    /**
     * 
     * @type {SpacePermissionAssignmentOperation}
     * @memberof SpacePermissionAssignment
     */
    operation?: SpacePermissionAssignmentOperation;
}

/**
 * Check if a given object implements the SpacePermissionAssignment interface.
 */
export function instanceOfSpacePermissionAssignment(value: object): value is SpacePermissionAssignment {
    return true;
}

export function SpacePermissionAssignmentFromJSON(json: any): SpacePermissionAssignment {
    return SpacePermissionAssignmentFromJSONTyped(json, false);
}

export function SpacePermissionAssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpacePermissionAssignment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'principal': json['principal'] == null ? undefined : SpacePermissionAssignmentPrincipalFromJSON(json['principal']),
        'operation': json['operation'] == null ? undefined : SpacePermissionAssignmentOperationFromJSON(json['operation']),
    };
}

export function SpacePermissionAssignmentToJSON(json: any): SpacePermissionAssignment {
    return SpacePermissionAssignmentToJSONTyped(json, false);
}

export function SpacePermissionAssignmentToJSONTyped(value?: SpacePermissionAssignment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'principal': SpacePermissionAssignmentPrincipalToJSON(value['principal']),
        'operation': SpacePermissionAssignmentOperationToJSON(value['operation']),
    };
}

