/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The formats a space description can be represented as. A subset of BodyRepresentation.
 * @export
 */
export const SpaceDescriptionBodyRepresentation = {
    Plain: 'plain',
    View: 'view'
} as const;
export type SpaceDescriptionBodyRepresentation = typeof SpaceDescriptionBodyRepresentation[keyof typeof SpaceDescriptionBodyRepresentation];


export function instanceOfSpaceDescriptionBodyRepresentation(value: any): boolean {
    for (const key in SpaceDescriptionBodyRepresentation) {
        if (Object.prototype.hasOwnProperty.call(SpaceDescriptionBodyRepresentation, key)) {
            if (SpaceDescriptionBodyRepresentation[key as keyof typeof SpaceDescriptionBodyRepresentation] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SpaceDescriptionBodyRepresentationFromJSON(json: any): SpaceDescriptionBodyRepresentation {
    return SpaceDescriptionBodyRepresentationFromJSONTyped(json, false);
}

export function SpaceDescriptionBodyRepresentationFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpaceDescriptionBodyRepresentation {
    return json as SpaceDescriptionBodyRepresentation;
}

export function SpaceDescriptionBodyRepresentationToJSON(value?: SpaceDescriptionBodyRepresentation | null): any {
    return value as any;
}

export function SpaceDescriptionBodyRepresentationToJSONTyped(value: any, ignoreDiscriminator: boolean): SpaceDescriptionBodyRepresentation {
    return value as SpaceDescriptionBodyRepresentation;
}

