/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoleType } from './RoleType';
import {
    RoleTypeFromJSON,
    RoleTypeFromJSONTyped,
    RoleTypeToJSON,
    RoleTypeToJSONTyped,
} from './RoleType';

/**
 * 
 * @export
 * @interface SpaceRole
 */
export interface SpaceRole {
    /**
     * The identifier for the space role.
     * @type {string}
     * @memberof SpaceRole
     */
    id?: string;
    /**
     * 
     * @type {RoleType}
     * @memberof SpaceRole
     */
    type?: RoleType;
    /**
     * The name for the space role.
     * @type {string}
     * @memberof SpaceRole
     */
    name?: string;
    /**
     * The description for the space role’s usage.
     * @type {string}
     * @memberof SpaceRole
     */
    description?: string;
    /**
     * The space permissions the space role is comprised of.
     * @type {Array<string>}
     * @memberof SpaceRole
     */
    spacePermissions?: Array<string>;
}



/**
 * Check if a given object implements the SpaceRole interface.
 */
export function instanceOfSpaceRole(value: object): value is SpaceRole {
    return true;
}

export function SpaceRoleFromJSON(json: any): SpaceRole {
    return SpaceRoleFromJSONTyped(json, false);
}

export function SpaceRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpaceRole {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : RoleTypeFromJSON(json['type']),
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'spacePermissions': json['spacePermissions'] == null ? undefined : json['spacePermissions'],
    };
}

export function SpaceRoleToJSON(json: any): SpaceRole {
    return SpaceRoleToJSONTyped(json, false);
}

export function SpaceRoleToJSONTyped(value?: SpaceRole | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': RoleTypeToJSON(value['type']),
        'name': value['name'],
        'description': value['description'],
        'spacePermissions': value['spacePermissions'],
    };
}

