/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentPropertyUpdateRequestVersion } from './ContentPropertyUpdateRequestVersion';
import {
    ContentPropertyUpdateRequestVersionFromJSON,
    ContentPropertyUpdateRequestVersionFromJSONTyped,
    ContentPropertyUpdateRequestVersionToJSON,
    ContentPropertyUpdateRequestVersionToJSONTyped,
} from './ContentPropertyUpdateRequestVersion';

/**
 * 
 * @export
 * @interface SpacePropertyUpdateRequest
 */
export interface SpacePropertyUpdateRequest {
    /**
     * Key of the space property
     * @type {string}
     * @memberof SpacePropertyUpdateRequest
     */
    key?: string;
    /**
     * Value of the space property.
     * @type {any}
     * @memberof SpacePropertyUpdateRequest
     */
    value?: any | null;
    /**
     * 
     * @type {ContentPropertyUpdateRequestVersion}
     * @memberof SpacePropertyUpdateRequest
     */
    version?: ContentPropertyUpdateRequestVersion;
}

/**
 * Check if a given object implements the SpacePropertyUpdateRequest interface.
 */
export function instanceOfSpacePropertyUpdateRequest(value: object): value is SpacePropertyUpdateRequest {
    return true;
}

export function SpacePropertyUpdateRequestFromJSON(json: any): SpacePropertyUpdateRequest {
    return SpacePropertyUpdateRequestFromJSONTyped(json, false);
}

export function SpacePropertyUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpacePropertyUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
        'version': json['version'] == null ? undefined : ContentPropertyUpdateRequestVersionFromJSON(json['version']),
    };
}

export function SpacePropertyUpdateRequestToJSON(json: any): SpacePropertyUpdateRequest {
    return SpacePropertyUpdateRequestToJSONTyped(json, false);
}

export function SpacePropertyUpdateRequestToJSONTyped(value?: SpacePropertyUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': value['value'],
        'version': ContentPropertyUpdateRequestVersionToJSON(value['version']),
    };
}

