/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpacePermissionAssignment } from './SpacePermissionAssignment';
import {
    SpacePermissionAssignmentFromJSON,
    SpacePermissionAssignmentFromJSONTyped,
    SpacePermissionAssignmentToJSON,
    SpacePermissionAssignmentToJSONTyped,
} from './SpacePermissionAssignment';
import type { OptionalFieldLinks } from './OptionalFieldLinks';
import {
    OptionalFieldLinksFromJSON,
    OptionalFieldLinksFromJSONTyped,
    OptionalFieldLinksToJSON,
    OptionalFieldLinksToJSONTyped,
} from './OptionalFieldLinks';
import type { OptionalFieldMeta } from './OptionalFieldMeta';
import {
    OptionalFieldMetaFromJSON,
    OptionalFieldMetaFromJSONTyped,
    OptionalFieldMetaToJSON,
    OptionalFieldMetaToJSONTyped,
} from './OptionalFieldMeta';

/**
 * 
 * @export
 * @interface SpaceSinglePermissions
 */
export interface SpaceSinglePermissions {
    /**
     * 
     * @type {Array<SpacePermissionAssignment>}
     * @memberof SpaceSinglePermissions
     */
    results?: Array<SpacePermissionAssignment>;
    /**
     * 
     * @type {OptionalFieldMeta}
     * @memberof SpaceSinglePermissions
     */
    meta?: OptionalFieldMeta;
    /**
     * 
     * @type {OptionalFieldLinks}
     * @memberof SpaceSinglePermissions
     */
    links?: OptionalFieldLinks;
}

/**
 * Check if a given object implements the SpaceSinglePermissions interface.
 */
export function instanceOfSpaceSinglePermissions(value: object): value is SpaceSinglePermissions {
    return true;
}

export function SpaceSinglePermissionsFromJSON(json: any): SpaceSinglePermissions {
    return SpaceSinglePermissionsFromJSONTyped(json, false);
}

export function SpaceSinglePermissionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpaceSinglePermissions {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(SpacePermissionAssignmentFromJSON)),
        'meta': json['meta'] == null ? undefined : OptionalFieldMetaFromJSON(json['meta']),
        'links': json['_links'] == null ? undefined : OptionalFieldLinksFromJSON(json['_links']),
    };
}

export function SpaceSinglePermissionsToJSON(json: any): SpaceSinglePermissions {
    return SpaceSinglePermissionsToJSONTyped(json, false);
}

export function SpaceSinglePermissionsToJSONTyped(value?: SpaceSinglePermissions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(SpacePermissionAssignmentToJSON)),
        'meta': OptionalFieldMetaToJSON(value['meta']),
        '_links': OptionalFieldLinksToJSON(value['links']),
    };
}

