/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The entity the space permissions corresponds to.
 * @export
 * @interface SpacePermissionAssignmentPrincipal
 */
export interface SpacePermissionAssignmentPrincipal {
    /**
     * 
     * @type {string}
     * @memberof SpacePermissionAssignmentPrincipal
     */
    type?: SpacePermissionAssignmentPrincipalTypeEnum;
    /**
     * ID of the entity.
     * @type {string}
     * @memberof SpacePermissionAssignmentPrincipal
     */
    id?: string;
}


/**
 * @export
 */
export const SpacePermissionAssignmentPrincipalTypeEnum = {
    User: 'user',
    Group: 'group',
    Role: 'role'
} as const;
export type SpacePermissionAssignmentPrincipalTypeEnum = typeof SpacePermissionAssignmentPrincipalTypeEnum[keyof typeof SpacePermissionAssignmentPrincipalTypeEnum];


/**
 * Check if a given object implements the SpacePermissionAssignmentPrincipal interface.
 */
export function instanceOfSpacePermissionAssignmentPrincipal(value: object): value is SpacePermissionAssignmentPrincipal {
    return true;
}

export function SpacePermissionAssignmentPrincipalFromJSON(json: any): SpacePermissionAssignmentPrincipal {
    return SpacePermissionAssignmentPrincipalFromJSONTyped(json, false);
}

export function SpacePermissionAssignmentPrincipalFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpacePermissionAssignmentPrincipal {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function SpacePermissionAssignmentPrincipalToJSON(json: any): SpacePermissionAssignmentPrincipal {
    return SpacePermissionAssignmentPrincipalToJSONTyped(json, false);
}

export function SpacePermissionAssignmentPrincipalToJSONTyped(value?: SpacePermissionAssignmentPrincipal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

