/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BodyType } from './BodyType';
import {
    BodyTypeFromJSON,
    BodyTypeFromJSONTyped,
    BodyTypeToJSON,
    BodyTypeToJSONTyped,
} from './BodyType';

/**
 * Contains fields for each representation type requested.
 * @export
 * @interface SpaceDescription
 */
export interface SpaceDescription {
    /**
     * 
     * @type {BodyType}
     * @memberof SpaceDescription
     */
    plain?: BodyType;
    /**
     * 
     * @type {BodyType}
     * @memberof SpaceDescription
     */
    view?: BodyType;
}

/**
 * Check if a given object implements the SpaceDescription interface.
 */
export function instanceOfSpaceDescription(value: object): value is SpaceDescription {
    return true;
}

export function SpaceDescriptionFromJSON(json: any): SpaceDescription {
    return SpaceDescriptionFromJSONTyped(json, false);
}

export function SpaceDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpaceDescription {
    if (json == null) {
        return json;
    }
    return {
        
        'plain': json['plain'] == null ? undefined : BodyTypeFromJSON(json['plain']),
        'view': json['view'] == null ? undefined : BodyTypeFromJSON(json['view']),
    };
}

export function SpaceDescriptionToJSON(json: any): SpaceDescription {
    return SpaceDescriptionToJSONTyped(json, false);
}

export function SpaceDescriptionToJSONTyped(value?: SpaceDescription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'plain': BodyTypeToJSON(value['plain']),
        'view': BodyTypeToJSON(value['view']),
    };
}

