/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The operation the space permission corresponds to.
 * @export
 * @interface SpacePermissionAssignmentOperation
 */
export interface SpacePermissionAssignmentOperation {
    /**
     * The type of operation.
     * @type {string}
     * @memberof SpacePermissionAssignmentOperation
     */
    key?: SpacePermissionAssignmentOperationKeyEnum;
    /**
     * The type of entity the operation type targets.
     * @type {string}
     * @memberof SpacePermissionAssignmentOperation
     */
    targetType?: SpacePermissionAssignmentOperationTargetTypeEnum;
}


/**
 * @export
 */
export const SpacePermissionAssignmentOperationKeyEnum = {
    Use: 'use',
    Create: 'create',
    Read: 'read',
    Update: 'update',
    Delete: 'delete',
    Copy: 'copy',
    Move: 'move',
    Export: 'export',
    Purge: 'purge',
    PurgeVersion: 'purge_version',
    Administer: 'administer',
    Restore: 'restore',
    CreateSpace: 'create_space',
    RestrictContent: 'restrict_content',
    Archive: 'archive'
} as const;
export type SpacePermissionAssignmentOperationKeyEnum = typeof SpacePermissionAssignmentOperationKeyEnum[keyof typeof SpacePermissionAssignmentOperationKeyEnum];

/**
 * @export
 */
export const SpacePermissionAssignmentOperationTargetTypeEnum = {
    Page: 'page',
    Blogpost: 'blogpost',
    Comment: 'comment',
    Attachment: 'attachment',
    Whiteboard: 'whiteboard',
    Database: 'database',
    Embed: 'embed',
    Folder: 'folder',
    Space: 'space',
    Application: 'application',
    UserProfile: 'userProfile'
} as const;
export type SpacePermissionAssignmentOperationTargetTypeEnum = typeof SpacePermissionAssignmentOperationTargetTypeEnum[keyof typeof SpacePermissionAssignmentOperationTargetTypeEnum];


/**
 * Check if a given object implements the SpacePermissionAssignmentOperation interface.
 */
export function instanceOfSpacePermissionAssignmentOperation(value: object): value is SpacePermissionAssignmentOperation {
    return true;
}

export function SpacePermissionAssignmentOperationFromJSON(json: any): SpacePermissionAssignmentOperation {
    return SpacePermissionAssignmentOperationFromJSONTyped(json, false);
}

export function SpacePermissionAssignmentOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpacePermissionAssignmentOperation {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'targetType': json['targetType'] == null ? undefined : json['targetType'],
    };
}

export function SpacePermissionAssignmentOperationToJSON(json: any): SpacePermissionAssignmentOperation {
    return SpacePermissionAssignmentOperationToJSONTyped(json, false);
}

export function SpacePermissionAssignmentOperationToJSONTyped(value?: SpacePermissionAssignmentOperation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'targetType': value['targetType'],
    };
}

