/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Principal } from './Principal';
import {
    PrincipalFromJSON,
    PrincipalFromJSONTyped,
    PrincipalToJSON,
    PrincipalToJSONTyped,
} from './Principal';

/**
 * 
 * @export
 * @interface SpaceRoleAssignment
 */
export interface SpaceRoleAssignment {
    /**
     * 
     * @type {Principal}
     * @memberof SpaceRoleAssignment
     */
    principal?: Principal;
    /**
     * The role to which the principal is assigned.
     * @type {string}
     * @memberof SpaceRoleAssignment
     */
    roleId?: string;
}

/**
 * Check if a given object implements the SpaceRoleAssignment interface.
 */
export function instanceOfSpaceRoleAssignment(value: object): value is SpaceRoleAssignment {
    return true;
}

export function SpaceRoleAssignmentFromJSON(json: any): SpaceRoleAssignment {
    return SpaceRoleAssignmentFromJSONTyped(json, false);
}

export function SpaceRoleAssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpaceRoleAssignment {
    if (json == null) {
        return json;
    }
    return {
        
        'principal': json['principal'] == null ? undefined : PrincipalFromJSON(json['principal']),
        'roleId': json['roleId'] == null ? undefined : json['roleId'],
    };
}

export function SpaceRoleAssignmentToJSON(json: any): SpaceRoleAssignment {
    return SpaceRoleAssignmentToJSONTyped(json, false);
}

export function SpaceRoleAssignmentToJSONTyped(value?: SpaceRoleAssignment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'principal': PrincipalToJSON(value['principal']),
        'roleId': value['roleId'],
    };
}

