/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpaceLinks
 */
export interface SpaceLinks {
    /**
     * Web UI link of the space.
     * @type {string}
     * @memberof SpaceLinks
     */
    webui?: string;
}

/**
 * Check if a given object implements the SpaceLinks interface.
 */
export function instanceOfSpaceLinks(value: object): value is SpaceLinks {
    return true;
}

export function SpaceLinksFromJSON(json: any): SpaceLinks {
    return SpaceLinksFromJSONTyped(json, false);
}

export function SpaceLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpaceLinks {
    if (json == null) {
        return json;
    }
    return {
        
        'webui': json['webui'] == null ? undefined : json['webui'],
    };
}

export function SpaceLinksToJSON(json: any): SpaceLinks {
    return SpaceLinksToJSONTyped(json, false);
}

export function SpaceLinksToJSONTyped(value?: SpaceLinks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'webui': value['webui'],
    };
}

