/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateFooterCommentModelBody } from './CreateFooterCommentModelBody';
import {
    CreateFooterCommentModelBodyFromJSON,
    CreateFooterCommentModelBodyFromJSONTyped,
    CreateFooterCommentModelBodyToJSON,
    CreateFooterCommentModelBodyToJSONTyped,
} from './CreateFooterCommentModelBody';
import type { UpdateFooterCommentModelVersion } from './UpdateFooterCommentModelVersion';
import {
    UpdateFooterCommentModelVersionFromJSON,
    UpdateFooterCommentModelVersionFromJSONTyped,
    UpdateFooterCommentModelVersionToJSON,
    UpdateFooterCommentModelVersionToJSONTyped,
} from './UpdateFooterCommentModelVersion';

/**
 * 
 * @export
 * @interface UpdateFooterCommentModel
 */
export interface UpdateFooterCommentModel {
    /**
     * 
     * @type {UpdateFooterCommentModelVersion}
     * @memberof UpdateFooterCommentModel
     */
    version?: UpdateFooterCommentModelVersion;
    /**
     * 
     * @type {CreateFooterCommentModelBody}
     * @memberof UpdateFooterCommentModel
     */
    body?: CreateFooterCommentModelBody;
}

/**
 * Check if a given object implements the UpdateFooterCommentModel interface.
 */
export function instanceOfUpdateFooterCommentModel(value: object): value is UpdateFooterCommentModel {
    return true;
}

export function UpdateFooterCommentModelFromJSON(json: any): UpdateFooterCommentModel {
    return UpdateFooterCommentModelFromJSONTyped(json, false);
}

export function UpdateFooterCommentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFooterCommentModel {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : UpdateFooterCommentModelVersionFromJSON(json['version']),
        'body': json['body'] == null ? undefined : CreateFooterCommentModelBodyFromJSON(json['body']),
    };
}

export function UpdateFooterCommentModelToJSON(json: any): UpdateFooterCommentModel {
    return UpdateFooterCommentModelToJSONTyped(json, false);
}

export function UpdateFooterCommentModelToJSONTyped(value?: UpdateFooterCommentModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': UpdateFooterCommentModelVersionToJSON(value['version']),
        'body': CreateFooterCommentModelBodyToJSON(value['body']),
    };
}

