/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSpaceRoleRequest
 */
export interface UpdateSpaceRoleRequest {
    /**
     * Name of the space role
     * @type {string}
     * @memberof UpdateSpaceRoleRequest
     */
    name: string;
    /**
     * Description for the space role
     * @type {string}
     * @memberof UpdateSpaceRoleRequest
     */
    description: string;
    /**
     * The ids of the space permissions associated with the space role. Sample value "read/space"; retrieve ids from responses returned by [GET /space-permissions](https://developer.atlassian.com/cloud/confluence/rest/v2/api-group-space-permissions/#api-space-permissions-get) endpoint
     * @type {Array<string>}
     * @memberof UpdateSpaceRoleRequest
     */
    spacePermissions: Array<string>;
    /**
     * If space anonymous access is assigned to the role being modified, the Id of a role to migrate those assignments to can be specified. Anonymous access role assignments left unchanged if unspecified.
     * @type {string}
     * @memberof UpdateSpaceRoleRequest
     */
    anonymousReassignmentRoleId?: string;
    /**
     * If guests are assigned to the role being modified, the Id of a role to migrate those assignments to can be specified. Guest role assignments left unchanged if unspecified.
     * @type {string}
     * @memberof UpdateSpaceRoleRequest
     */
    guestReassignmentRoleId?: string;
}

/**
 * Check if a given object implements the UpdateSpaceRoleRequest interface.
 */
export function instanceOfUpdateSpaceRoleRequest(value: object): value is UpdateSpaceRoleRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('spacePermissions' in value) || value['spacePermissions'] === undefined) return false;
    return true;
}

export function UpdateSpaceRoleRequestFromJSON(json: any): UpdateSpaceRoleRequest {
    return UpdateSpaceRoleRequestFromJSONTyped(json, false);
}

export function UpdateSpaceRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSpaceRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'spacePermissions': json['spacePermissions'],
        'anonymousReassignmentRoleId': json['anonymousReassignmentRoleId'] == null ? undefined : json['anonymousReassignmentRoleId'],
        'guestReassignmentRoleId': json['guestReassignmentRoleId'] == null ? undefined : json['guestReassignmentRoleId'],
    };
}

export function UpdateSpaceRoleRequestToJSON(json: any): UpdateSpaceRoleRequest {
    return UpdateSpaceRoleRequestToJSONTyped(json, false);
}

export function UpdateSpaceRoleRequestToJSONTyped(value?: UpdateSpaceRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'spacePermissions': value['spacePermissions'],
        'anonymousReassignmentRoleId': value['anonymousReassignmentRoleId'],
        'guestReassignmentRoleId': value['guestReassignmentRoleId'],
    };
}

