/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCustomContentRequestVersion
 */
export interface UpdateCustomContentRequestVersion {
    /**
     * The version number, must be incremented by one.
     * @type {number}
     * @memberof UpdateCustomContentRequestVersion
     */
    number?: number;
    /**
     * An optional message to be stored with the version.
     * @type {string}
     * @memberof UpdateCustomContentRequestVersion
     */
    message?: string;
}

/**
 * Check if a given object implements the UpdateCustomContentRequestVersion interface.
 */
export function instanceOfUpdateCustomContentRequestVersion(value: object): value is UpdateCustomContentRequestVersion {
    return true;
}

export function UpdateCustomContentRequestVersionFromJSON(json: any): UpdateCustomContentRequestVersion {
    return UpdateCustomContentRequestVersionFromJSONTyped(json, false);
}

export function UpdateCustomContentRequestVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCustomContentRequestVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'number': json['number'] == null ? undefined : json['number'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function UpdateCustomContentRequestVersionToJSON(json: any): UpdateCustomContentRequestVersion {
    return UpdateCustomContentRequestVersionToJSONTyped(json, false);
}

export function UpdateCustomContentRequestVersionToJSONTyped(value?: UpdateCustomContentRequestVersion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'number': value['number'],
        'message': value['message'],
    };
}

