/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateFooterCommentModelVersion
 */
export interface UpdateFooterCommentModelVersion {
    /**
     * Number of new version. Should be 1 higher than current version of the comment.
     * @type {number}
     * @memberof UpdateFooterCommentModelVersion
     */
    number?: number;
    /**
     * Optional message store for the new version.
     * @type {string}
     * @memberof UpdateFooterCommentModelVersion
     */
    message?: string;
}

/**
 * Check if a given object implements the UpdateFooterCommentModelVersion interface.
 */
export function instanceOfUpdateFooterCommentModelVersion(value: object): value is UpdateFooterCommentModelVersion {
    return true;
}

export function UpdateFooterCommentModelVersionFromJSON(json: any): UpdateFooterCommentModelVersion {
    return UpdateFooterCommentModelVersionFromJSONTyped(json, false);
}

export function UpdateFooterCommentModelVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFooterCommentModelVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'number': json['number'] == null ? undefined : json['number'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function UpdateFooterCommentModelVersionToJSON(json: any): UpdateFooterCommentModelVersion {
    return UpdateFooterCommentModelVersionToJSONTyped(json, false);
}

export function UpdateFooterCommentModelVersionToJSONTyped(value?: UpdateFooterCommentModelVersion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'number': value['number'],
        'message': value['message'],
    };
}

