/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateBlogPostRequestVersion
 */
export interface UpdateBlogPostRequestVersion {
    /**
     * The new version number of the updated blog post. 
     * Set this to the current version number plus one, unless you are updating the status to 'draft' which requires a version number of 1.
     * 
     * If you don't know the current version number, use Get blog post by id.
     * @type {number}
     * @memberof UpdateBlogPostRequestVersion
     */
    number?: number;
    /**
     * An optional message to be stored with the version.
     * @type {string}
     * @memberof UpdateBlogPostRequestVersion
     */
    message?: string;
}

/**
 * Check if a given object implements the UpdateBlogPostRequestVersion interface.
 */
export function instanceOfUpdateBlogPostRequestVersion(value: object): value is UpdateBlogPostRequestVersion {
    return true;
}

export function UpdateBlogPostRequestVersionFromJSON(json: any): UpdateBlogPostRequestVersion {
    return UpdateBlogPostRequestVersionFromJSONTyped(json, false);
}

export function UpdateBlogPostRequestVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBlogPostRequestVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'number': json['number'] == null ? undefined : json['number'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function UpdateBlogPostRequestVersionToJSON(json: any): UpdateBlogPostRequestVersion {
    return UpdateBlogPostRequestVersionToJSONTyped(json, false);
}

export function UpdateBlogPostRequestVersionToJSONTyped(value?: UpdateBlogPostRequestVersion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'number': value['number'],
        'message': value['message'],
    };
}

