/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateFooterCommentModelBody } from './CreateFooterCommentModelBody';
import {
    CreateFooterCommentModelBodyFromJSON,
    CreateFooterCommentModelBodyFromJSONTyped,
    CreateFooterCommentModelBodyToJSON,
    CreateFooterCommentModelBodyToJSONTyped,
} from './CreateFooterCommentModelBody';
import type { GetAttachmentById200ResponseAllOfLinks } from './GetAttachmentById200ResponseAllOfLinks';
import {
    GetAttachmentById200ResponseAllOfLinksFromJSON,
    GetAttachmentById200ResponseAllOfLinksFromJSONTyped,
    GetAttachmentById200ResponseAllOfLinksToJSON,
    GetAttachmentById200ResponseAllOfLinksToJSONTyped,
} from './GetAttachmentById200ResponseAllOfLinks';
import type { UpdateFooterCommentModelVersion } from './UpdateFooterCommentModelVersion';
import {
    UpdateFooterCommentModelVersionFromJSON,
    UpdateFooterCommentModelVersionFromJSONTyped,
    UpdateFooterCommentModelVersionToJSON,
    UpdateFooterCommentModelVersionToJSONTyped,
} from './UpdateFooterCommentModelVersion';

/**
 * 
 * @export
 * @interface UpdateFooterCommentRequest
 */
export interface UpdateFooterCommentRequest {
    /**
     * 
     * @type {UpdateFooterCommentModelVersion}
     * @memberof UpdateFooterCommentRequest
     */
    version?: UpdateFooterCommentModelVersion;
    /**
     * 
     * @type {CreateFooterCommentModelBody}
     * @memberof UpdateFooterCommentRequest
     */
    body?: CreateFooterCommentModelBody;
    /**
     * 
     * @type {GetAttachmentById200ResponseAllOfLinks}
     * @memberof UpdateFooterCommentRequest
     */
    links?: GetAttachmentById200ResponseAllOfLinks;
}

/**
 * Check if a given object implements the UpdateFooterCommentRequest interface.
 */
export function instanceOfUpdateFooterCommentRequest(value: object): value is UpdateFooterCommentRequest {
    return true;
}

export function UpdateFooterCommentRequestFromJSON(json: any): UpdateFooterCommentRequest {
    return UpdateFooterCommentRequestFromJSONTyped(json, false);
}

export function UpdateFooterCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFooterCommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : UpdateFooterCommentModelVersionFromJSON(json['version']),
        'body': json['body'] == null ? undefined : CreateFooterCommentModelBodyFromJSON(json['body']),
        'links': json['_links'] == null ? undefined : GetAttachmentById200ResponseAllOfLinksFromJSON(json['_links']),
    };
}

export function UpdateFooterCommentRequestToJSON(json: any): UpdateFooterCommentRequest {
    return UpdateFooterCommentRequestToJSONTyped(json, false);
}

export function UpdateFooterCommentRequestToJSONTyped(value?: UpdateFooterCommentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': UpdateFooterCommentModelVersionToJSON(value['version']),
        'body': CreateFooterCommentModelBodyToJSON(value['body']),
        '_links': GetAttachmentById200ResponseAllOfLinksToJSON(value['links']),
    };
}

