/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateBlogPostRequestBody } from './CreateBlogPostRequestBody';
import {
    CreateBlogPostRequestBodyFromJSON,
    CreateBlogPostRequestBodyFromJSONTyped,
    CreateBlogPostRequestBodyToJSON,
    CreateBlogPostRequestBodyToJSONTyped,
} from './CreateBlogPostRequestBody';
import type { UpdateBlogPostRequestVersion } from './UpdateBlogPostRequestVersion';
import {
    UpdateBlogPostRequestVersionFromJSON,
    UpdateBlogPostRequestVersionFromJSONTyped,
    UpdateBlogPostRequestVersionToJSON,
    UpdateBlogPostRequestVersionToJSONTyped,
} from './UpdateBlogPostRequestVersion';

/**
 * 
 * @export
 * @interface UpdateBlogPostRequest
 */
export interface UpdateBlogPostRequest {
    /**
     * Id of the blog post.
     * @type {string}
     * @memberof UpdateBlogPostRequest
     */
    id: string;
    /**
     * The updated status of the blog post.
     * 
     * Note, if you change the status of a blog post from 'current' to 'draft' and it has an existing draft, the existing draft will be deleted in favor of the updated draft.
     * Additionally, this endpoint can be used to restore a 'trashed' or 'deleted' blog post to 'current' status. For restoration, blog post contents will not be updated and only the blog post status will be changed.
     * @type {string}
     * @memberof UpdateBlogPostRequest
     */
    status: UpdateBlogPostRequestStatusEnum;
    /**
     * Title of the blog post.
     * @type {string}
     * @memberof UpdateBlogPostRequest
     */
    title: string;
    /**
     * ID of the containing space.
     * 
     * This currently **does not support moving the blog post to a different space**.
     * @type {string}
     * @memberof UpdateBlogPostRequest
     */
    spaceId?: string;
    /**
     * 
     * @type {CreateBlogPostRequestBody}
     * @memberof UpdateBlogPostRequest
     */
    body: CreateBlogPostRequestBody;
    /**
     * 
     * @type {UpdateBlogPostRequestVersion}
     * @memberof UpdateBlogPostRequest
     */
    version: UpdateBlogPostRequestVersion;
    /**
     * Created date of the blog post in the format of "yyyy-MM-ddTHH:mm:ss.SSSZ".
     * @type {string}
     * @memberof UpdateBlogPostRequest
     */
    createdAt?: string;
}


/**
 * @export
 */
export const UpdateBlogPostRequestStatusEnum = {
    Current: 'current',
    Draft: 'draft'
} as const;
export type UpdateBlogPostRequestStatusEnum = typeof UpdateBlogPostRequestStatusEnum[keyof typeof UpdateBlogPostRequestStatusEnum];


/**
 * Check if a given object implements the UpdateBlogPostRequest interface.
 */
export function instanceOfUpdateBlogPostRequest(value: object): value is UpdateBlogPostRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function UpdateBlogPostRequestFromJSON(json: any): UpdateBlogPostRequest {
    return UpdateBlogPostRequestFromJSONTyped(json, false);
}

export function UpdateBlogPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBlogPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'title': json['title'],
        'spaceId': json['spaceId'] == null ? undefined : json['spaceId'],
        'body': CreateBlogPostRequestBodyFromJSON(json['body']),
        'version': UpdateBlogPostRequestVersionFromJSON(json['version']),
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function UpdateBlogPostRequestToJSON(json: any): UpdateBlogPostRequest {
    return UpdateBlogPostRequestToJSONTyped(json, false);
}

export function UpdateBlogPostRequestToJSONTyped(value?: UpdateBlogPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'title': value['title'],
        'spaceId': value['spaceId'],
        'body': CreateBlogPostRequestBodyToJSON(value['body']),
        'version': UpdateBlogPostRequestVersionToJSON(value['version']),
        'createdAt': value['createdAt'],
    };
}

