/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateCustomContentRequestBody } from './CreateCustomContentRequestBody';
import {
    CreateCustomContentRequestBodyFromJSON,
    CreateCustomContentRequestBodyFromJSONTyped,
    CreateCustomContentRequestBodyToJSON,
    CreateCustomContentRequestBodyToJSONTyped,
} from './CreateCustomContentRequestBody';
import type { UpdateCustomContentRequestVersion } from './UpdateCustomContentRequestVersion';
import {
    UpdateCustomContentRequestVersionFromJSON,
    UpdateCustomContentRequestVersionFromJSONTyped,
    UpdateCustomContentRequestVersionToJSON,
    UpdateCustomContentRequestVersionToJSONTyped,
} from './UpdateCustomContentRequestVersion';

/**
 * 
 * @export
 * @interface UpdateCustomContentRequest
 */
export interface UpdateCustomContentRequest {
    /**
     * Id of custom content.
     * @type {string}
     * @memberof UpdateCustomContentRequest
     */
    id: string;
    /**
     * Type of custom content.
     * @type {string}
     * @memberof UpdateCustomContentRequest
     */
    type: string;
    /**
     * The status of the custom content.
     * @type {string}
     * @memberof UpdateCustomContentRequest
     */
    status: UpdateCustomContentRequestStatusEnum;
    /**
     * ID of the containing space (must be the same as the spaceId of the space the custom content was created in).
     * @type {string}
     * @memberof UpdateCustomContentRequest
     */
    spaceId?: string;
    /**
     * ID of the containing page.
     * @type {string}
     * @memberof UpdateCustomContentRequest
     */
    pageId?: string;
    /**
     * ID of the containing Blog Post.
     * @type {string}
     * @memberof UpdateCustomContentRequest
     */
    blogPostId?: string;
    /**
     * ID of the containing custom content.
     * @type {string}
     * @memberof UpdateCustomContentRequest
     */
    customContentId?: string;
    /**
     * Title of the custom content.
     * @type {string}
     * @memberof UpdateCustomContentRequest
     */
    title: string;
    /**
     * 
     * @type {CreateCustomContentRequestBody}
     * @memberof UpdateCustomContentRequest
     */
    body: CreateCustomContentRequestBody;
    /**
     * 
     * @type {UpdateCustomContentRequestVersion}
     * @memberof UpdateCustomContentRequest
     */
    version: UpdateCustomContentRequestVersion;
}


/**
 * @export
 */
export const UpdateCustomContentRequestStatusEnum = {
    Current: 'current'
} as const;
export type UpdateCustomContentRequestStatusEnum = typeof UpdateCustomContentRequestStatusEnum[keyof typeof UpdateCustomContentRequestStatusEnum];


/**
 * Check if a given object implements the UpdateCustomContentRequest interface.
 */
export function instanceOfUpdateCustomContentRequest(value: object): value is UpdateCustomContentRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function UpdateCustomContentRequestFromJSON(json: any): UpdateCustomContentRequest {
    return UpdateCustomContentRequestFromJSONTyped(json, false);
}

export function UpdateCustomContentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCustomContentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'status': json['status'],
        'spaceId': json['spaceId'] == null ? undefined : json['spaceId'],
        'pageId': json['pageId'] == null ? undefined : json['pageId'],
        'blogPostId': json['blogPostId'] == null ? undefined : json['blogPostId'],
        'customContentId': json['customContentId'] == null ? undefined : json['customContentId'],
        'title': json['title'],
        'body': CreateCustomContentRequestBodyFromJSON(json['body']),
        'version': UpdateCustomContentRequestVersionFromJSON(json['version']),
    };
}

export function UpdateCustomContentRequestToJSON(json: any): UpdateCustomContentRequest {
    return UpdateCustomContentRequestToJSONTyped(json, false);
}

export function UpdateCustomContentRequestToJSONTyped(value?: UpdateCustomContentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'status': value['status'],
        'spaceId': value['spaceId'],
        'pageId': value['pageId'],
        'blogPostId': value['blogPostId'],
        'customContentId': value['customContentId'],
        'title': value['title'],
        'body': CreateCustomContentRequestBodyToJSON(value['body']),
        'version': UpdateCustomContentRequestVersionToJSON(value['version']),
    };
}

