/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BodyBulk } from './BodyBulk';
import {
    BodyBulkFromJSON,
    BodyBulkFromJSONTyped,
    BodyBulkToJSON,
    BodyBulkToJSONTyped,
} from './BodyBulk';

/**
 * 
 * @export
 * @interface VersionedEntity
 */
export interface VersionedEntity {
    /**
     * Title of the entity.
     * @type {string}
     * @memberof VersionedEntity
     */
    title?: string;
    /**
     * ID of the entity.
     * @type {string}
     * @memberof VersionedEntity
     */
    id?: string;
    /**
     * 
     * @type {BodyBulk}
     * @memberof VersionedEntity
     */
    body?: BodyBulk;
}

/**
 * Check if a given object implements the VersionedEntity interface.
 */
export function instanceOfVersionedEntity(value: object): value is VersionedEntity {
    return true;
}

export function VersionedEntityFromJSON(json: any): VersionedEntity {
    return VersionedEntityFromJSONTyped(json, false);
}

export function VersionedEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionedEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'id': json['id'] == null ? undefined : json['id'],
        'body': json['body'] == null ? undefined : BodyBulkFromJSON(json['body']),
    };
}

export function VersionedEntityToJSON(json: any): VersionedEntity {
    return VersionedEntityToJSONTyped(json, false);
}

export function VersionedEntityToJSONTyped(value?: VersionedEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'id': value['id'],
        'body': BodyBulkToJSON(value['body']),
    };
}

