/* tslint:disable */
/* eslint-disable */
/**
 * The Confluence Cloud REST API v2
 * This document describes Confluence\'s v2 APIs. This is intended to be an iteration on the existing Confluence Cloud REST API with improvements in both endpoint definitions and performance.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Version
 */
export interface Version {
    /**
     * Date and time when the version was created. In format "YYYY-MM-DDTHH:mm:ss.sssZ".
     * @type {Date}
     * @memberof Version
     */
    createdAt?: Date;
    /**
     * Message associated with the current version.
     * @type {string}
     * @memberof Version
     */
    message?: string;
    /**
     * The version number.
     * @type {number}
     * @memberof Version
     */
    number?: number;
    /**
     * Describes if this version is a minor version. Email notifications and activity stream updates are not created for minor versions.
     * @type {boolean}
     * @memberof Version
     */
    minorEdit?: boolean;
    /**
     * The account ID of the user who created this version.
     * @type {string}
     * @memberof Version
     */
    authorId?: string;
}

/**
 * Check if a given object implements the Version interface.
 */
export function instanceOfVersion(value: object): value is Version {
    return true;
}

export function VersionFromJSON(json: any): Version {
    return VersionFromJSONTyped(json, false);
}

export function VersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Version {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'message': json['message'] == null ? undefined : json['message'],
        'number': json['number'] == null ? undefined : json['number'],
        'minorEdit': json['minorEdit'] == null ? undefined : json['minorEdit'],
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
    };
}

export function VersionToJSON(json: any): Version {
    return VersionToJSONTyped(json, false);
}

export function VersionToJSONTyped(value?: Version | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'message': value['message'],
        'number': value['number'],
        'minorEdit': value['minorEdit'],
        'authorId': value['authorId'],
    };
}

